### ISSUE TITLE
Creating a pull-request sometimes hangs

### ISSUE THREAD

**Issue by aaronjensen** [magit/forge#101]
I don't have a great repro for this yet, but I'm opening for now in case anyone else has a similar issue or if anyone has tips on how to track this down. 

When I C-c C-c after a `forge-create-pullreq` Emacs hangs/spins indefinitely until I C-g. This only appears to happen the first time I create a pull request in Emacs. I believe I've seen the PR succeed once, but usually it never actually creates.

```
GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.2 (Build 18C54)) of 2019-02-06
```

**Comment by tarsius** [comment]
> This only appears to happen the first time I create a pull request in Emacs.

Sounds like it could be related to https://github.com/magit/ghub/issues/81. That also only happens "the first time" I believe.

**Comment by aaronjensen** [comment]
Ah, very well could be. I do see that in my messages.

**Comment by tarsius** [comment]
Very likely then.
