### ISSUE TITLE
Forge remote.*.url must end with `.git` to work

### ISSUE THREAD

**Issue by yiufung** [magit/forge#106]
A GitLab repo path looks like "https://gitlab.com/group_name/project/". When clone with Magit, that is set as `remote.origin.url`. 

However, this schema is not recognized by Forge (Error: `Cannot determine forge repository.  https://gitlab.com/group_name/project/ isn’t a forge url`. ) and is needed to manually changed to `https://gitlab.com/group_name/project.git` to work.

**Comment by tarsius** [comment]
Removing the trailing slash would also work.

@kyleam @npostavs @vermiculus Should I allow a trailing slash? Personally I have gotten into the habit over never ending urls with a slash (even actively removing them when I copy from somewhere that uses such a slash). But that's for consistency, I don't think either way is right or wrong.

**Comment by vermiculus** [comment]
Is there a downside to it? It seems a reasonable assumption to make that it would work (since I imagine there are forges where you would copy the browser's URL as the remote name)

**Comment by kyleam** [comment]
My uninformed expectation would be that a trailing slash is allowed.

**Comment by npostavs** [comment]
> Is there a downside to it?

Yeah, I don't see any obvious reason to disallow it. 

Though I can't recall seeing URLs with a trailing slash anywhere myself.

**Comment by yiufung** [comment]
@npostavs Indeed, if I click through GitLab's pages, their url does *not* contain a trailing slash. However, in my Firefox, as I search through history in address bar, the default option I select *does* contain a trailing slash. Very odd as I don't recall ever changing the address.

**Comment by tarsius** [comment]
Done.
