### ISSUE TITLE
GitHub Enterprise Authentication issues

### ISSUE THREAD

**Issue by J3RN** [magit/forge#108]
Hey team! :wave: I've read through the other issues opened on this subject, and am aiming to detail the issue we GitHub Enterprise users are experiencing in the most complete yet concise way to hopefully help create a solution. Hear me out :smile:

I have tried a handful of different URLs for the `APIHOST` value of my company's GitHub Enterprise entry in the `forge-alist` variable. Here are my results:

- `git.my-company.com/api/v3`

  ### `forge-alist` entry
  ```
  ("git.my-company.com" "git.my-company.com/api/v3" "git.my-company.com" forge-github-repository)
  ```

  This comes from a history of using `magithub`—this URL is ultimately what worked for that package.

  ### Test
  Restart Emacs, open the `magit-status` page for a repository whose `origin` exists on my company's GitHub Enterprise instance,  and run `M-x forge-pull`.

  ### Results
  - Prompts for username
  - Creates a corresponding `.gitconfig` entry
  - Prompts to create new "Github API Token" with provided host
  - Prompts for username again
  - Prompts for password
  - Successfully creates a Personal Access Token on the GitHub Enterprise instance
  - Prompts to save auth info to `.authinfo`
  - Creates a `.authinfo` entry after I approve it to
  - Raises an error:
    ```
    ghub--signal-error: HTTP Error: 404, "Not found", "/api/v3/graphql", ((message . "Not Found") (documentation_url . "https://developer.github.com/enterprise/2.16/v3"))
    ```

- `git.my-company.com/api`

    ### `forge-alist` entry
    ```
    ("git.my-company.com" "git.my-company.com/api" "git.my-company.com" forge-github-repository)
    ```

  Figuring the `/v3` part of the URL was overly heavy-handed, I removed it. After all, [the GitHub Enterprise docs show the URL for GraphQL queries as `/api/graphql`](https://developer.github.com/enterprise/2.15/v4/guides/forming-calls/#the-graphql-endpoint).

  ### Test
  Restart Emacs, open the `magit-status` page for a repository whose `origin` exists on my company's GitHub Enterprise instance,  and run `M-x forge-pull`.

  ### Results
  - Prompts for username
  - Creates a corresponding `.gitconfig` entry
  - Prompts to create new "Github API Token" with provided host
  - Prompts for username again
  - Prompts for password
  - Raises error:
    ```
    ghub--confirm-create-token: HTTP Error: 422, "Unprocessable Entity (Added by DAV)", "/api/authorizations", ((message . "Your browser did something unexpected. Please contact us if the problem persists.") (documentation_url . "https://github.com/magit/ghub/wiki/Github-Errors"))
    ```

- `git.my-company.com`

  ### `forge-alist` entry
  ```
  ("git.my-company.com" "git.my-company.com" "git.my-company.com" forge-github-repository)
  ```

  Just for fun, I thought I'd try this as well.

  ### Test
  Restart Emacs, open the `magit-status` page for a repository whose `origin` exists on my company's GitHub Enterprise instance,  and run `M-x forge-pull`.

  ### Results
  - Prompts for username
  - Creates a corresponding `.gitconfig` entry
  - Prompts to create new "Github API Token" with provided host
  - Prompts for username again
  - Prompts for password
  - Raises error: 
    ```
    ghub--confirm-create-token: HTTP Error: 422, "Unprocessable Entity (Added by DAV)", "/authorizations", ((message . "Your browser did something unexpected. Please contact us if the problem persists.") (documentation_url . "https://github.com/magit/ghub/wiki/Github-Errors"))
    ```

I'd be happy to pair with anyone on solving this, if they're open to it :smile:

**Comment by nathanjsweet** [comment]
I had success with the following:

1. Forge `alist` entry:
```lisp
("git.my-company.com" "git.my-company.com/api" "git.my-company.com" forge-github-repository)
```
2. `.gitconfig` (make sure with `git config --get-regexp .+` that you don't have more of these hanging around then you need)
```sh
github.host git.my-company.com/api
github.git.my-company.com/api.user ${your_user_name}
```
3. `.authinfo`
```sh
machine git.my-company.com/api login ${user_name}^forge password ${your_token}
```

One thing that got me that WebDav error that your seeing is that I accidentally put my email address as my username instead of my short user name, I don't think user names in github are ever email addresses. Just thought I'd throw that out there in case you had the same issue as me.

**Comment by J3RN** [comment]
@nathanjsweet Thanks so much for sharing! I can verify that your solution works for me as well.

For all who come after, here are the exact steps I took based on what Nathan wrote above:
1. Add the forge-alist entry into my config for Forge. I use `use-package`, so it looks like this:
    ```elisp
    (use-package forge
      :config
      (add-to-list 'forge-alist '("git.my-company.com" "git.my-company.com/api" "git.my-company.com" forge-github-repository)))
    ```
2. Edit the `.git/config` file for the GitHub Enterprise repository I'm working on to have this at the bottom:
    ```
    [github]
    	host = git.my-company.com/api
    ```
3. Edit my `~/.gitconfig` file to have this entry:
    ```    
    [github "git.my-company.com/api"]
    	user = ${username}
    ```
4. Generate a token through the web interface of the GitHub Enterprise instance, and put it in my `~/.authinfo` file like so:
    ```
    machine git.my-company.com/api login ${username}^forge password ${token}
    ```

Voila! It works! :smile:

**Comment by tarsius** [comment]
I assume (4) means that using the wizard failed. Maybe it does so because your companies instance does not support basic authentication, hard to tell from here. :wink:

Anyway, I have added

> For some Github Enterprice instances ~/api~ instead of ~/api/v3~ as
> shown above. If the wizard fails in both cases, then try creating
> the token manually.

at the appropriate place in the `ghub` manual.
