### ISSUE TITLE
Forge Suffixes Don't Show Up In Magit Pop-ups

### ISSUE THREAD

**Issue by parhamdoustdar** [magit/forge#109]
I'm using the latest Melpa version of Forge, and I'm not doing anything extra about it in my init file (i.e. not using `require` explicitly because installed packages are automatically required).

However, transient suffixes are not showing up. For example, when I visit the branching buffer by pressing `b`, I don't see a `y` key for `forge-checkout-pullreq`. Maybe the autoload cookie is missing and that line (which i found in `forge.el`) is never being executed?

I've checked the info pages, but I'm not seeing anything about extra configuration steps. Am I missing something here?

Thanks!

**Comment by tarsius** [comment]
Yesterday I added this to the manual.  (Online version is awaiting cache invalidation.)

Loading Magit doesn't cause Forge to be loaded automatically.  Adding something like this to your init file takes care of this:

```emacs-lisp
(with-eval-after-load 'magit
  (require 'forge))

```

Or if you use ~use-package~:

```emacs-lisp
(use-package forge
  :after magit)

```

**Comment by tarsius** [comment]
/cc @kyleam @purcell

This keeps coming up and I am wondering whether we should just autoload the first form, similar to what Kyle has done for his extensions to Magit. Steve sometimes argues against packages imposing themselves just because they happen to be installed, but I feel this might be a different situation. Simply loading `forge` doesn't change anything (*) except adding key bindings, and `magit` still has to be loaded by the user; either explicitly using `require`, which is not recommended, or by invoking an autoloaded command such as `magit-status`.

(*) For the time being at least, but that might change. Some of Magit's fetch commands might be taught to *also* fetch the forge metadata (but would only do so for package whose forge metadata was previously fetched explicitly).

**Comment by parhamdoustdar** [comment]
I would personally support this. When I install a package, it would be strange for me to go somewhere else and say that I *really* want it to be loaded. If I don't want it, there are a lot of other places that I could modify to have it not be loaded.

**Comment by vermiculus** [comment]
I disagree. I can see a case for not wanting forge features in magit but wanting access to its codebase for other development. How would you avoid installing features if they're autoloaded?

**Comment by parhamdoustdar** [comment]
Good point. I know that `org` solves this by having a customizable list of
modules that it would load. Do you guys think it's useful to have something
like this in magit, where there is one place to register plugins that would
want to register their own prefix keys?
I mean, in the context of magit, it makes sense to have `magit-status`
autoloaded, because it's pretty much the gateway to magit functionality.
However, in terms of magit *plugins* (to coin a term), it doesn't make
sense to load all of them. Even when using `eval-after-load`, I often end
up not using forge so it ends up being loaded but not used at all.

**Comment by beeuhtricks** [comment]
@tarsius You closed my issue #115 but I’m pretty sure it’s different from this. I do use `:after magit` in my config, and I have the Forge suffixes in branch and fetch and so forth, they’re just missing in pull.

**Comment by purcell** [comment]
> Steve sometimes argues against packages imposing themselves just because they happen to be installed, but I feel this might be a different situation.

I think this is a standard situation, and the standard principles apply. It should be possible to have forge installed but not activated, just like any other Emacs library. It's normal to require some setup beyond installing a package.

If you want to provide an autoloaded something to make things easier, or generally just make it possible to enable `forge` integration using the Custom interface, then you might consider providing an autoloaded global minor mode.

**Comment by purcell** [comment]
> I mean, in the context of magit, it makes sense to have `magit-status` autoloaded, because it's pretty much the gateway to magit functionality. However, in terms of magit *plugins* (to coin a term), it doesn't make sense to load all of them. Even when using `eval-after-load`, I often end up not using forge so it ends up being loaded but not used at all.

There are some standard mechanisms for managing keybindings and optional behaviours, so I'm not sure magit plugins are a special case. I'd think that between keymaps, minor modes and prefix commands, there should be a way to configure all these that is consistent with other aspects of Emacs.

For example, if forge were an autoloaded minor mode with its own map, designed to be enabled in `magit-status-mode`, you could enable it either globally (by adding it to `magit-status-mode-hook`), in a `.dir-locals.el` or on-demand with `M-x forge-mode`.
