### ISSUE TITLE
Support draft pull requests on github

### ISSUE THREAD

**Issue by MordecaiMalignatus** [magit/forge#112]
A few weeks ago, GitHub [introduced](https://github.blog/2019-02-14-introducing-draft-pull-requests/) the notion of "Draft Pullrequests", that being, PRs that are not yet ready to be merged. 

Ideally this would be supported by forge (opening PRs on github in 'Draft' state) but it's understandable if that would be out of scope. It is also reasonably likely that other forges will include support for this, now that GH has it. 

Many thanks for the work on unifying this!

**Comment by danielcompton** [comment]
Here's the corresponding issue for hub: https://github.com/github/hub/issues/2038, and the resolving PR: https://github.com/github/hub/pull/2098.

**Comment by tarsius** [comment]
That feature is currently in preview, meaning that that a special ACCEPT header has to be used in this particular case. `ghub` does not yet support doing that and this feature doesn't seem important enough to implement that *just* for this feature.

**Comment by tarsius** [comment]
I have added basic support for draft pull-requests. To create a draft add `draft: true` to the yaml front matter. Currently there is only a yaml front matter if the user chose a template that comes with one. Eventually we might always use a yaml front matter. Until then, this is what a draft pull-request should look like:

```
---
title: a draft
draft: true
---

This is unfinished.
```

**Comment by MordecaiMalignatus** [comment]
@tarsius Thank you, and thank you for your work ❤️

**Comment by asymmetric** [comment]
@tarsius I've tried creating a draft PR the way you said above and it didn't work.

Additionally, [these comments](https://github.com/magit/forge/blob/269effb4954071f590954c0e5b4faba3f27d03d0/lisp/forge-topic.el#L689-L692) in the code say that front-matter is ignored for GitHub PRs.

Is it currently impossible to create them from within forge?

**Comment by claudio-dalicandro** [comment]
I can't find any info on the front-matter in the doc @tarsius, I tried to add a

```
-----
draft: true
-----
```

At the beginning of the PR creation buffer but didn't work at all (it just ended up in the description and title of the pr...)

Anyway I love forge, but I still have the feeling that I don't know it at all... Is there an exhaustive documentation that is escaping me or maybe I need to do a bit of reverse engineering?

**Comment by tarsius** [comment]
```
      ;; Unlike for issues, Github ignores the yaml front-matter for
      ;; pull-requests.  We just assume that nobody tries to use it
      ;; anyway.  If that turned out to be wrong, we would have to
      ;; deal with it by complicating matters around here.
```

Well turns out we do, but it's not a high priority.

**Comment by rolandtritsch** [comment]
Just checking on the status of this. At least I would love/like to make this configurable (`create-pr-as-draft: true/false`). Thoughts?

**Comment by pkryger** [comment]
I've been pondering on implementing something in `forge` to better support draft PRs (for github and gitlub). But this is not a small thing (at least to me) and I'll probably first create a write up of what I plan to do. That is to avoid a situation similar to review support.

In the mean time I'm using a small extension to forge that allows me to sent draft PRs to github and to change a draft into review ready. You can check [this PR](https://github.com/emacs-exordium/exordium/pull/167) to see how it works. Disclaimer: it uses `forge`'s internal functions, so may break any day without a warning.

**Comment by tarsius** [comment]
> But this is not a small thing (at least to me) and I'll probably first create a write up of what I plan to do.

That's a wise approach. :smiley:

**Comment by practicalli-john** [comment]
FYI.  I have noticed that creating pull requests from Magit forge is automatically creating a draft pull request. I noticed it towards the end of 2021.

**Comment by wraithm** [comment]
> FYI. I have noticed that creating pull requests from Magit forge is automatically creating a draft pull request. I noticed it towards the end of 2021.

Yeah, I've notice the same thing. Is there a way to change that?

**Comment by tarsius** [comment]
I don't see how this could happen.

Try this: Initiate a pull-request and then in the buffer where the message is written, evaluate `(forge--topic-parse-buffer)`. The returned alist should not have an element for `draft`. If it indeed does not, then Forge won't tell Github to create a draft (see `forge--submit-create-pullreq` in `forge-github.el`).

If Github creates a draft anyway, then I guess that it is possible to configure Github to create a draft by default, either as a user or repository setting. I couldn't find such a thing.

**Comment by wraithm** [comment]
The alist has `text`, `file`, `title`, and `body`. I don't see `draft` in there!

Github creates a draft anyways! I guess there's some setting to make PRs in draft mode by default!

I don't remember setting that anywhere. I've googled it furiously and am not able to pull anything up. I scoured our settings too. I can't find anything.

I'm totally baffled by this 😅

**Comment by gondalez** [comment]
I can report I experienced this for a time as well. I estimate about 3 months ago. 

I quite liked it as it suits my workflow.

However it reverted to creating non-drafts soon after.

**Comment by tarsius** [comment]
What does `(list json-false json-null (json-encode nil))` return for you. For me it returns `(:json-false nil "null")`, which isn't really correct but seems to work anyway, at least for me.

**Comment by tarsius** [comment]
Also check if `ghub-json-use-jansson` is nil.

**Comment by wraithm** [comment]
`(list json-false json-null (json-encode nil))` evaluates to `(:json-false nil "null")`.

`ghub-json-use-jansson` isn't defined. At least, when I search for the variable via help, I can't find it.

**Comment by wraithm** [comment]
Okay, I upgraded Doom Emacs and now it no longer makes draft PRs! I have no idea what I did other than upgrade...

**Comment by tarsius** [comment]
I just fixed some issue. Update `ghub` and `forge` and then no drafts should be created anymore unless you request it explicitly.

Intentionally creating a draft should also be possible now by manually adding this at the beginning of the buffer.

```
---
draft: true
---
```

I might still add a command to toggle this.

**Comment by tarsius** [comment]
There seems to be quite a bit of interest in this...
I'll try to get it done the next time I turn my attention to Forge.

**Comment by tarsius** [comment]
The draft status can now be toggled with `C-c C-e d` in the buffer used to write the pull-request description.

**Comment by tarsius** [comment]
Make sure to also update `yaml`.

**Comment by ryanprior** [comment]
I will use this regularly, thanks all!

**Comment by rolandtritsch** [comment]
Awesome. Thank you!!!

**Comment by tarsius** [comment]
:yum:

**Comment by wraithm** [comment]
@tarsius This is awesome! Is it possible to toggle the draft state on an existing pull request?

**Comment by tarsius** [comment]
Unfortunately that requires an update to the database schema and also to `ghub`, so it will likely again take a while until I am motivated to do it.

**Comment by tarsius** [comment]
Okay, I have implemented that too now. As always it may take a few hours until it becomes available on Melpa. If you use another installation method you'll also have to update magit and ghub.

This turned out more involved than expected, requiring changes to 15 files across three repositories. The github and gitlab rest apis do not support this. So for github I had to implement the first ever graphql mutation and for gitlab I had to use graphql for the first time ever.

**Comment by tarsius** [comment]
Note that all pull-requests that forge fetched before this change are marked as ready but you can turn them into drafts by "toggling" twice.

**Comment by goberlan** [comment]
I know this thread is somewhat dead, but how can i hide draft PR's in my list? I have tried just `N m f o` but it still lists `draft` PR's and i don't want them (my teams has a lot of them). I just want to filter them out and i can't figure out how...

**Comment by tarsius** [comment]
There's no support for that. Please open a new "idea" discussion, else this suggestion will get lost.
