### ISSUE TITLE
Lockup with diff dwim

### ISSUE THREAD

**Issue by jkdufair** [magit/forge#114]
Forge version 20190305.1102
Magit version 20190305.1106
Emacs 26.1
Mac OS 10.14.3

When I try to `d d` on a PR (Gitlab backend), Emacs locks up. Not sure how to troubleshoot, but any pointers and I'll try to dig in.

**Comment by tarsius** [comment]
I cannot reproduce. (Tried with a Gitlab repository.)

Maybe the pr is humongous and washing the diff takes forever. How does "Emacs lock up"? Does `C-g` help (but result in a partially corrupted diff)?

**Comment by jkdufair** [comment]
C-g does not seem to help. Screen actually goes black after a few seconds. Bell rings about 1x per second. Perhaps is something with my install. Will try to repro with -Q

**Comment by tarsius** [comment]
Let me know if you can reproduce with -Q.
