### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by xendk** [magit/forge#117]
I love forge but the UX seems a bit fiddly compared to magit. A few thoughts I had, for your consideration:

Why can't I just edit PR title and state by pressing return on them in the PR buffer?
Why doesn't `b b` on the PR line in the magit-status buffer suggest the branch per default?
Why all these new `C-c` commands. Haven't been using `C-c` with magit so far, it seems out of place.

It might just be me that doesn't quite grok forge yet, but that's my initial reaction.

**Comment by tarsius** [comment]
> Why can't I just edit PR title and state by pressing return on them in the PR buffer?

Across all of magit `RET` only ever visits something. New users quickly get an intuition that `RET` is always 100% safe, lets not break that intuition.

> Why doesn't `b b` on the PR line in the magit-status buffer suggest the branch per default?

That key is actually bound to

```emacs-lisp
(defun magit-checkout (revision)
  "Checkout REVISION, updating the index and the working tree.
If REVISION is a local branch, then that becomes the current
branch.  If it is something else, then `HEAD' becomes detached.
Checkout fails if the working tree or the staging area contain
changes.
\n(git checkout REVISION)."
  (interactive (list (magit-read-other-branch-or-commit "Checkout")))
  (when (string-match "\\`heads/\\(.+\\)" revision)
    (setq revision (match-string 1 revision)))
  (magit-run-git "checkout" revision))
```

> Why all these new `C-c` commands. Haven't been using `C-c` with magit so far, it seems out of place.

We are running out of letters.

**Comment by tarsius** [comment]
I agree there is room for improvement, but this is not a good time to discuss details because I am instead focused on fixing bugs and long standing issues (mostly in magit, not forge).

**Comment by xendk** [comment]
> Across all of magit RET only ever visits something. New users quickly get an intuition that RET is always 100% safe, lets not break that intuition.

Fair point, but couldn't `magit-edit-thing` be more straightforward ? Threading on user territory with `C-c` seems wrong, and with forge there seems to be a bigger need for editing.

> That key is actually bound to

Yes? It's labeled "dwim" and I've learned that it seems to switch branch. If I'm on a revision in the log, it suggests something like `branchname~3`, so on a PR I would expect it to suggest the PR branch.

> We are running out of letters.

Indeed. Problem is that you start messing with the muscle memory of users that's bound `C-c ...` to all kind of things. 

> I agree there is room for improvement, but this is not a good time to discuss details because I am instead focused on fixing bugs and long standing issues (mostly in magit, not forge).

I'll leave this around for when the time arises then.

**Comment by tarsius** [comment]
> Threading on user territory with `C-c` seems wrong,

Only `C-c <letter>` is reserved for users, `C-c C-<letter>` is not.

**Comment by tarsius** [comment]
> It's labeled "dwim" and I've learned that it seems to switch branch.

Maybe that's over selling it a bit. :stuck_out_tongue: 

> on a PR I would expect it to suggest the PR branch.

Yeah, it probably should. But doing that probably is a bit more work than one would hope.

**Comment by xendk** [comment]
> Only C-c <letter> is reserved for users, C-c C-<letter> is not.

Ah, okay, I thought it was them all. Maybe I should sacrifice `C-c e` to `magit-edit-thing` then. `C-c C-e` isn't particularly good on Dvorak, requiring me to swap control key in the middle.

> Maybe that's over selling it a bit. 

Granted, I do end up with a detached from time to time.

**Comment by tarsius** [comment]
I have renamed "dwim" to "branch/revision".

I think I won't try to add a real "dwim" variant because past experience has shown that "dwim" means very different things to different users when it comes to branch and checkout commands.
