### ISSUE TITLE
Problem while fetching a PR

### ISSUE THREAD

**Issue by rnehra01** [magit/forge#118]
As per documentation, `b y` should create a new branch for the PR but when I try to use for PR from `fork/master` to `origin/master`, magit asks me `Branch master already exists. Reset it?` and on confirming it create 2 new commits in my local master branch 
```
commit 6933611317006444685fdfd7144249e0acad0c66 (HEAD -> master, sannanansari/master, refs/pullreqs/185)
Date:   Thu Mar 7 11:49:20 2019 -0500
    Change in cloner.py

commit 105144dd22be945c22c8cda2d732ce3010ce8037
Date:   Thu Mar 7 11:40:11 2019 -0500
    Change in cloner.py

```

**Comment by tarsius** [comment]
I would recommend using feature branches instead of `master`, but if a user did use `master`, then we have to handle that gracefully.

**Comment by tarsius** [comment]
Well in a way we already did but I have changed the prompt to be very verbose now, which should be sufficient to prevent users from doing this. Also users are given the option to use a branch named `pr-<number>` now in most cases.
