### ISSUE TITLE
Interactively creating a token hangs

### ISSUE THREAD

**Issue by qinix** [magit/forge#119]
I'm creating a token interactively by invoking `forge-pull`. After submitting the password, the cursor hangs at the char 'P' like this.

<img width="245" alt="9DF87BD2-DBF2-48DC-9A0A-B9D65DD8BC56" src="https://user-images.githubusercontent.com/1946663/54090227-d9431980-43ac-11e9-9a15-971a43b470b0.png">

Then I hit `C-g` to quit the status, and try `forge-pull` again. The 'creating token' process starts again. \

**Comment by tarsius** [comment]
I don't think `ghub` is to blame here. The prompt comes from `url-basic-auth`, which uses `read-passwd`. Try if the same thing happens if you use `(read-passwd "Password: " nil "12345")` directly.
