### ISSUE TITLE
not possible to create Github PR against upstream?

### ISSUE THREAD

**Issue by titaniumbones** [magit/forge#120]
I'm not sure if I'm making some kind of an error, but I don't seem to be able to create a PR from my GH form of a project to an upstream repo.  

Steps to reproduce: 

- fork a GH repo
- add remotes for origin and upstream
- make changes locally in `my-changes` branch and push to origin
- invoke `forge-create-pullreq`, choosing `origin/my-changes` as head and `upstream/master` as base
- PR wil lbe created, but with `origin/master` as base (rather than upstream)

using 20180226 from MELPA, but didn't notice anything in changelog from last 2 weeks that would change this behaviour.

**Comment by tarsius** [comment]
I cannot find it right now but there is another issue about this.

That other issue can be summarized as "either (a) do not offer branches that we do not actually support opening a pr against and then open it against something else instead, or (b) support any remote branch from and remote".

**Comment by titaniumbones** [comment]
Is it #87? though that one is closed too.

**Comment by tarsius** [comment]
Ah, that's why I didn't find it. Meant to reopen that.
