### ISSUE TITLE
Interact with issues without cloning

### ISSUE THREAD

**Issue by matthew-piziak** [magit/forge#121]
This is sort of a funny question: is it possible to use forge to look at repositories without cloning into them with a full `magit-init`? More generally, do you foresee being able to use forge as an issue browsing and reporting tool? That's a more lightweight usecase than full collaborative development.

By the way, I've created this issue with `forge`, from my local forge repository managed by `straight`. So it definitely works pretty well once the repo is on your machine!

I'm thinking about larger repositories where you might want to quickly dip into repos to report bugs. Maybe one day some kind of autocompletion index for GitHub projects could remove any reason to visit GitHub at all, for example. I'm sure you have some thoughts about this.

**Comment by tarsius** [comment]
That's supported now, see #102.
