### ISSUE TITLE
"This is an old draft.  Discard and start over?" feels backwards

### ISSUE THREAD

**Issue by hpdeifel** [magit/forge#123]
The following is very subjective:

When forge finds an old draft for issues/prs, it asks me if I want to "Discard and start over". My intuitive reaction at this prompt is to type 'y' if I wan't to *retain* the draft and 'n' to discard it, which is exactly the opposite of what I should type.

I think my subconsciousness expects forge to ask if I want to *keep* the draft. The current behavior feels like someone walking up to you and asking "Hey, I've found something you might have lost! Should I throw it away?".

Sorry for this slightly incoherent issue :-)

**Comment by tarsius** [comment]
It's yet another "Do you want me to do the dangerous thing?" prompt. Replacing that with a "Do you want me to do the safe thing?" prompt would feel off to me.

**Comment by jperras** [comment]
I was just bitten by this today: my draft PR was mistakenly deleted because my instinct was to hit `y` from years of being conditioned that the destructive option is typically the `no` selection.

**Comment by tarsius** [comment]
"Yes or no" prompts are most suitable for "do it or don't do it" questions, but what we have here are two choices "do something" and "do something else". So we should probably use a multiple-choice question even though there are only two choices.

```
An old draft already exists
  [r]esume editing using draft
  [d]iscard draft and start over
```

**Comment by hpdeifel** [comment]
I guess the difference to other "Do you want me to do the dangerous thing?" prompts is that the user doesn't intentionally initiate the dangerous thing in this case. The action taken is not "throw away old post" but rather "create post".

The suggestion of switching "y/n" to "r/d" or something sounds good to me.

**Comment by tarsius** [comment]
I've done that now.

Also note that even if you accidentally discard, you can get the old draft back using `undo`.
