### ISSUE TITLE
format markdown lists in GitLab MR comments

### ISSUE THREAD

**Issue by dsvensson** [magit/forge#126]
GitLab lists pushes to the repo added after the MR as markdown lists via `<ul>`, `<li>` and so on. It would be nice if these were rendered as bullet points or something in the MR view.

**Comment by vermiculus** [comment]
In other words, you'd like commits added after a merge request was opened to be styled differently?

**Comment by dsvensson** [comment]
Well... it seems like it's partially markdown-rendered, in that for example links are rendered correctly. For example "Compare with previous version" is rendered as a http link, and ```-blocks are rendered code blocks . It's just that lists are not markdown-rendered. 

Here for example:
https://gitlab.gnome.org/GNOME/glib/merge_requests/708

The top-most comment that starts with "Jordan Petridis @alatiera added 26 commits 2 weeks ago " would in forge have its list printed out in magit forge pull request view as something like `<ul><li>d8dc9d34...35db2ffe - 17 commits from branch GNOME:master</li><li>...</li></ul>`, rather as a bullet point list.

**Comment by dsvensson** [comment]
Ah, I think this is caused by forge using gfm-mode here:

https://github.com/magit/forge/blob/42ec0e005a589d9f47bd324a730b79ed58ec3a5d/lisp/forge-topic.el#L408

And GitLab uses plain Markdown in its data?

**Comment by vermiculus** [comment]
Can you provide a screenshot of what you do see? If it's showing lists as
```
- item one
- item two
```
I think that's just how markdown-mode works. There might be an option to 'prettify' it, but 'prettify' is certainly a matter of opinion here.

**Comment by dsvensson** [comment]
![image](https://user-images.githubusercontent.com/302027/54763175-c96dd580-4bf5-11e9-8e1f-090c58527535.png)

The wrapping of:

"Compare with previous
version"

...should probably be one line as well?

Copying the whole message results in:

```
added 7 commits

<ul><li>ddeva9321 - xxxxxxxxxxx
xxxxxx</li><li>50cfcdd5 - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxx</li><li>d0018f36 - xxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxx</li><li>859bf9e5 - xxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</li><li>6cbc75ee -
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</li><li>dbfe0e01 - xxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</li><li>8d07b545 -
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</li></ul>

[Compare with previous
version](https://..../merge_requests/6/diffs?diff_id=..&start_sha=.....)
```

**Comment by tarsius** [comment]
> The top-most comment

That's not a comment (made by a human) but some other "event". I plan to support displaying all information that is displayed in the "event stream" in the web interface. Eventually.

It doesn't provide any details, but I consider #58 to be the issue about this.
