### ISSUE TITLE
Error with "F y" from a magit status buffer

### ISSUE THREAD

**Issue by NicolasPetton** [magit/forge#13]
On a GitHub project, during the initial pull, I get the following errors in process filters after the message 
      "Storing org/project...done"

```
error in process filter: mapconcat: Wrong type argument: listp, []
error in process filter: Wrong type argument: listp, []
```

**Comment by wedens** [comment]
Isn't it the same as https://github.com/magit/forge/issues/5?

**Comment by NicolasPetton** [comment]
@wedens it looks like it, thanks. Closing this one.
