### ISSUE TITLE
502 error fetching pull requests

### ISSUE THREAD

**Issue by adrinjalali** [magit/forge#130]
This happens when I try to fetch pull requests of https://github.com/scikit-learn/scikit-learn

```
error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null")
(errors ((message . "Something went wrong while executing your query.
This may be the result of a timeout, or it could be a GitHub bug. Please include
`BAD6:0851:12B577C:263B29A:5CA1CE03` when reporting this issue.")))) ```

**Comment by adrinjalali** [comment]
Related to https://github.com/magit/forge/issues/69, if not a duplicate.

**Comment by adrinjalali** [comment]
Also related: https://github.com/magit/forge/issues/20

**Comment by tarsius** [comment]
Also https://github.com/magit/ghub/issues/83#issuecomment-456098300.

**Comment by adrinjalali** [comment]
FWIW, fetching notifications works for me, it's the `forge-pull` which fails.
