### ISSUE TITLE
forge-pull fails with HTTP error when getting project

### ISSUE THREAD

**Issue by dcaixinha** [magit/forge#131]
Hey! First of all, thanks for this awesome package :raised_hands: 

I have a private GitLab instance and I've followed the instructions on #9 to set-up the authentication. When I do a `forge-pull` I get:
```
HTTP Error: 404, "Not found", "/api/v4/projects/some-thing%2Fmyproject", ((message . "404 Project Not Found"))
```
The remote is configured as:
```
Remote origin (git@gitlab.mydomain.com:some-thing/myproject.git)
```

I'm guessing the issue is related to the `/` in the remote being translated to `%2F`. Is this a bug or am I misusing somethig? Thanks :raised_hands:

**Comment by tarsius** [comment]
> I'm guessing the issue is related to the `/` in the remote being translated to `%2F`. Is this a bug

That's not a bug. While it is inconvenient and ugly, Gitlab really expects the `%2F`.

> I've followed the instructions on #9 to set-up the authentication.

That issue is about https being required and http not being supported. Are you using https or http? If it's the latter then that's why it is not working.

**Comment by dcaixinha** [comment]
I'm using `https`. From the error itself (`404 Not found`) I thought the issue wasn't authentication but using the GitLab API itself. This is what I added to my dotfile to support my private instance:
```
  (with-eval-after-load 'forge
    (add-to-list 'forge-alist '("gitlab.mydomain.com" "gitlab.mydomain.com/api/v4" "gitlab.mydomain.com" forge-gitlab-repository)))
```
Does this look OK?

**Comment by dcaixinha** [comment]
Sorry the red herring @tarsius, closing this issue now. It was a misconfiguration for GitLab in my company's instance. Thanks :bowing_man:
