### ISSUE TITLE
Forge sections missing

### ISSUE THREAD

**Issue by little-dude** [magit/forge#132]
Hello,

I'm getting started with emacs, so this issue is probably entirely my fault, but I can't find what I did wrong. I installed `magit` and `forge` via MELPA, and reduced my `init.el` to the following (there are other package _installed_, does that matter?):

```elisp
;; enable MELPA. See: https://melpa.org/#/getting-started
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(require 'use-package)

(use-package magit
  :bind (("C-x g" . magit-status)))

(use-package forge
  :after magit)

;; we keep our secrets in an encrypted file
(setq auth-sources '((:source "~/.config/authinfo.gpg")))
```

My problem is that after doing a `forge-pull`, I don't see the "Pull Requests" and "Issues" sections as they are described in the [guide](https://magit.vc/manual/forge/Usage.html#Usage):

> Once information has been fetched from a repository’s forge, Forge adds two additional sections named "Pull requests" and "Issues" to Magit’s status buffer.

You can see the `forge-pull` successfully running in the `*Messages*` buffer:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Making completion list... [4 times]
Turning on magit-auto-revert-mode...done
Making completion list... [2 times]
Pulling little-dude/generals-rs...
Decrypting /home/corentin/.config/authinfo.gpg...done
Pulling little-dude/generals-rs...done
Storing little-dude/generals-rs...done
Running git fetch origin
Git finished
Quit
Mark set
Mark activated
next-line: End of buffer [6 times]
```

Here is what I see: [image](https://imgur.com/a/7JBD7N5)

More infos:

- emacs 26.1, GUI version
- `M-x magit-version`: `Magit 20190402.2114, Git 2.21.0, Emacs 26.1, gnu/linux`
- forge version: `20190323.1422` (note that `M-x pkg-info-package-version RET forge` doesn't work: `epl-package-from-lisp-file: Invalid EPL package file: "/home/corentin/.emacs.d/elpa/forge-20190323.1422/forge.el", "Package lacks a \"Version\" or \"Package-Version\" header"`)

Thank you for your packages and for your time.

**Comment by npostavs** [comment]
> Pulling little-dude/generals-rs...done

I think the problem is that forge doesn't insert the sections when there are 0 issues/pull requests, as is the case for that repo.

**Comment by little-dude** [comment]
Geez, that's right, sorry about this, it all works fine on another repo with both issues and PR.
