### ISSUE TITLE
Forge is `require`d and loaded, `forge-dispatch` is bound but `forge-pull` is not

### ISSUE THREAD

**Issue by matthew-piziak** [magit/forge#138]
I configure forge with:
``` emacs-lisp
(use-package forge
	:straight t
	:after magit)
```

With this configuration, `forge` has an Info node, and I can run `M-x forge-pull`. I can also press `'` in a Magit buffer to get the Forge dispatcher. But I do not see Forge in my pull menu. Specifically, `F y` does not run `forge-pull`.

![screenshot](https://user-images.githubusercontent.com/6801001/56218960-e69a9600-6033-11e9-8e9c-64fc95905459.png)

**Comment by tarsius** [comment]
Things to try:

1. Are both `forge` and `magit` up-to-date?
2. Are there any `... is not a transient command` errors in `*Message*`.
3. The bindings are defined at the end of`forge.el`. Try evaluating the respective forms using `eval-last-sexp`.
3. Remove `:straight t`, which results in what forks for me.

**Comment by matthew-piziak** [comment]
1. Yes.
2. No.
3. Surprisingly, _no_, that doesn't work for me, even though it looks like it should.

I evaluated these forms: 
```
(transient-append-suffix 'magit-pull "m"
  '("y" "forge topics" forge-pull))
(transient-append-suffix 'magit-pull "y"
  '("Y" "forge notifications" forge-pull-notifications))
```

4. Removing `:straight t` did not work for me.

**Comment by tarsius** [comment]
Is it only missing from `F` or `f` also? If only from `F`, then that is expected because the group the binding is added to is not visible unless `magit-pull-or-fetch` is non-nil.

**Comment by matthew-piziak** [comment]
It is in fact missing from `f` as well...I've also tried setting `magit-pull-or-fetch` to `t` and it's still not part of `F`.

**Comment by tarsius** [comment]
Do you understand emacs lisp? If so try adding debug statements to the relevant functions to see where things start going wrong.

**Comment by matthew-piziak** [comment]
I do, yeah. I'll take a crack at it.

**Comment by matthew-piziak** [comment]
I deleted and reloaded the package and now they're back in the `f` menu.

**Comment by matthew-piziak** [comment]
And with this they're back to the `F` menu as well.
```
(use-package forge
  :straight t
  :after magit
  :config
  (setq magit-pull-or-fetch t))
```

Sorry, not sure what happened there! Closing this out, thank you!

**Comment by tarsius** [comment]
Probably some outdated `*.elc` file was loaded. You can prevent that using my `auto-compile` package.

**Comment by tarsius** [comment]
It won't work for `init.el` and all built-in files loaded before that though due to a chicken and egg problem. (And it is possible that `init.elc` was the outdated file in this case.)

**Comment by matthew-piziak** [comment]
Brilliant! Thank you.
