### ISSUE TITLE
Ability to filter topics

### ISSUE THREAD

**Issue by yisraeldov** [magit/forge#140]
It would be very useful to be able to filter topic. 

Specifically showing only issues for a specific milestone. 

Also in the list mode it would be very helpful to see tags there and be able to limit to only open issues. 

Thanks

**Comment by yisraeldov** [comment]
This can be done by adding more filelds to the list 

```
(setq forge-topic-list-columns
  '(("#" 5
     (lambda (a b)
       (> (car a) (car b)))
     (:right-align t) number nil)
    ("Title" 35 t nil title  nil)
    ("Milestone" 4 t nil milestone nil)
    ("State" 4 t nil state nil)
    ("Updated" 10 t nill updated nil)
    ))
```

and then using `tablist-edit-filter`

**Comment by Boruch-Baum** [comment]
I confirm that @yisraeldov 's suggestion works, but suggest the following tweaks to column lengths so that the data appears nicely:
```
(setq forge-topic-list-columns
  '(("#" 4
     (lambda (a b)
       (> (car a) (car b)))
     (:right-align t) number nil)
    ("Title" 35 t nil title  nil)
    ("Milestone" 9 t nil milestone nil)
    ("State" 6 t nil state nil)
    ("Updated" 10 t nill updated nil)
    ))
```

**Comment by Boruch-Baum** [comment]
This issue prompted me to make a feature request against the emacs function `tabulated-list-sort`. See [here](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=35796) and feel free to comment there.

**Comment by yisraeldov** [comment]
Also it would be nice to have the nicely formatted topics in the list view like they are in the main view.

**Comment by Silex** [comment]
Just wanted to mention https://github.com/politza/tablist

It's based on tabulated list but can filter columns by regex, resize columns, etc

**Comment by yisraeldov** [comment]
You can already filter, but the default view doesn't show enough columns to
make it usefull.

I showed an example on youtube.

**Comment by atanasj** [comment]
This sounds like it would be a great feature to implement, however I cannot seem to get this working. I have added @Boruch-Baum [config](https://github.com/magit/forge/issues/140#issuecomment-493726841), but it doesn't seem to work. See below for exact config:

```emacs-lisp
  ;; forge config
  (with-eval-after-load 'forge
    (add-to-list 'forge-alist '("api.github.com/graphql" forge-github-repository))
    (setq forge-topic-list-columns
          '(("#" 4
             (lambda (a b)
               (> (car a) (car b)))
             (:right-align t) number nil)
            ("Title" 35 t nil title  nil)
            ("Milestone" 9 t nil milestone nil)
            ("State" 6 t nil state nil)
            ("Updated" 10 t nill updated nil)
            )
          )
```

When I run `forge-list-topics` the info is presented without any labels or the ability to filter. 
How can I get this working?

**Comment by Matsa59** [comment]
I would like to do this but with tags (know as labels). However, using the code from above I got `unbound`. 
In the quick view on status buffer page, we can see number, title and labels so I hope it's possible.

**Comment by tarsius** [comment]
> It would be very useful to be able to filter topic.

Some filtering is possible. Currently this is limited to one filter at a time, but I plan to make it possible to use multiple filters at once.

> Specifically showing only issues for a specific milestone.

There isn't a milestone filter yet. I'll delay that until I add support for multiple filters at once, at which point it will be much easier to do this.

> Also in the list mode it would be very helpful to see tags there

I've added support for that.

> and be able to limit to only open issues.

That existed for a while now.

**Comment by tarsius** [comment]
Filtering has been much improved. There are more filters and one can use multiple filters at once.

In topic list buffers use `C-c C-c` to open the filtering menu. That menu is also available in the status buffer via `N m f`.

The approach suggested above, to fake filtering by sorting, does not work anymore. The topic lists no longer use `tabulated-list-mode` and, at least for the time being, it is not possible to add more columns.
