### ISSUE TITLE
How does one clear closed (gray) topics from forge?

### ISSUE THREAD

**Issue by matthew-piziak** [magit/forge#141]
For GitHub, when does Forge decide to mark a topic as closed (`forge-topic-closed`), and when does it decide to omit it from the "Pull requests" section entirely? Can I ask forge to clean all closed topics from the section?

The Forge manual says:
> All open issues and some recently edited and closed topics are listed.

Can this behavior be changed?

**Comment by waymondo** [comment]
See the variable [`forge-topic-list-limit`](https://github.com/magit/forge/blob/master/lisp/forge-topic.el#L43). You can filter out closed topics by use `0` as the 2nd number in this variable.

**Comment by matthew-piziak** [comment]
@waymondo Works perfectly, thank you!
