### ISSUE TITLE
Local or user-specific notes for topics

### ISSUE THREAD

**Issue by matthew-piziak** [magit/forge#142]
Usecase: I'd love to be able to locally mark a forge topic as "reviewed-by-me" even if the upstream semantics don't support that (i.e. I don't want to make a comment or tag on GitHub).

I know that pretty much nobody uses git notes, but I'd definitely use something analogous for topics.

**Comment by vermiculus** [comment]
Would this be similar to the 'personal notes' feature of magithub?

Although your particular use-case seems better suited to some sort of discrete data structure.

**Comment by symbiont-matthew-piziak** [comment]
Looking at the definition for `magithub-issue-personal-note` it does look similar. I agree that this specific usecase would be better served by some kind of read/unread semantics, but of course I don't know if it's popular enough to warrant it.

**Comment by matthew-piziak** [comment]
Wow! Thank you @tarsius!

**Comment by tarsius** [comment]
I've added support topic "marks".  Marks are like labels except that they are private (and local to one machine).  A topics marks can be changed the same way as its labels.

Unlike labels, marks are not local to a particular repository.  To create a new mark us `forge-create-mark`.  There's also `forge-edit-mark`.

Beside `forge-edit-topic-marks` (`C-c C-e` on the the "Marks:" header), there also exists a function to toggle a single mark, which can be used to define dedicated commands.  I think you were after something like that.  Use it like this:

``` emacs-lisp
(defun forge-toggle-NEXT-mark ()
  (interactive)
  (forge-toggle-mark "NEXT"))

(setf (alist-get 'forge-toggle-NEXT-mark magit-dwim-selection)
      (list nil t)))
```

**Comment by matthew-piziak** [comment]
Just tried this out and it works perfectly. Love the user experience of how I can interactive set a name and a face and it immediately becomes available. Thanks again!
