### ISSUE TITLE
does forge support quote reply?

### ISSUE THREAD

**Issue by shuxiao9058** [magit/forge#143]
and how to quote reply?

**Comment by tarsius** [comment]
> and how to quote reply?

Either mark the text that you want to quote before typing `C-c C-r` or, if you want to quote a complete post, then use `C-u C-c C-r`.

I have just implemented this feature.  It might take a while to hit Melpa.

**Comment by shuxiao9058** [comment]
thanks so much.

**Comment by shuxiao9058** [comment]
> if you want to quote a complete post, then use `C-u C-c C-r`.

not work.

**Comment by shuxiao9058** [comment]
it is because `C-u` bind to `evil-scroll-up`

```
It is bound to C-u, <visual-state> C-u, <normal-state> C-u.

(evil-scroll-up COUNT)

Scrolls the window and the cursor COUNT lines upwards.
If COUNT is not specified the function scrolls down
‘evil-scroll-count’, which is the last used count.
If the scroll count is zero the command scrolls half the screen.

```

**Comment by tarsius** [comment]
Yes, `C-u` usually is `universal-argument`. Use whatever key is bound to that command in your case.
