### ISSUE TITLE
Avoid long key-binding sequences

### ISSUE THREAD

**Issue by jwiegley** [magit/forge#144]
I was a bit surprised to see that `' p` was changed to `' c p`. As someone who creates many pull requests each day, and owing to the fact that `' p` can be typed with one hand (on either Qwerty or Dvorak), but `' c p` requires two hands, I'd like to request that where possible, long key-binding sequences be avoided unless there is some obvious benefit. I locally remapped `' p` to restore a much appreciated convenience.

Or, have a customization variable to enable these "shorthands for advanced users". I still use and appreciate my `F F` and `P P` bindings perhaps hundreds of times a week, for how quickly they can be executed given how often they are used.

**Comment by jwiegley** [comment]
Love the new transient stuff @tarsius.

**Comment by tarsius** [comment]
Glad you like it!
