### ISSUE TITLE
Create issue on gitlab fails if using any but first template

### ISSUE THREAD

**Issue by chaoflow** [magit/forge#147]
Upon forge-create-issue in a GitLab project with issue templates I'm prompted for a template and existing templates are tab-completed. If I use any but the alphabetically first template the prompt is cleared and I'm prompted again for the template.

This can be tested in https://gitlab.com/chaoflow-test-projects/magit-forge

https://gitlab.com/chaoflow-test-projects/magit-forge/tree/master/.gitlab/issue_templates

foo works, story and xyz don't.

Feel free to add issues in there.

**Comment by chaoflow** [comment]
Discovering magit-forge after years of using Magit and GitLab reminds me of having discovered Magit after years of Git without it.

THANK YOU!

**Comment by tarsius** [comment]
Sorry for the delay.

It was a rather silly bug.

> Discovering magit-forge after years of using Magit and GitLab reminds
> me of having discovered Magit after years of Git without it.

:-D

**Comment by chaoflow** [comment]
@tarsius Thanks a lot for finding and fixing the bug!
