### ISSUE TITLE
Custom hostnames for ssh identities

### ISSUE THREAD

**Issue by jtrakk** [magit/forge#148]
I use a few Github accounts for different projects. Normally I do

```
git remote add origin git@github.com-someaccount:org/repo.git
```

and I have in `~/.ssh/config`:

```
Host github.com-someaccount
     Hostname github.com
     IdentityFile ~/.ssh/id_rsa_someaccount
     User git
     identitiesOnly yes
```

This means I can use a separate ssh key for each account. 

Then I can just `git push` to these accounts from a shell. But `forge` doesn't recognize the custom hostname `github.com-someaccount`, so I can't create a pull request `git@github.com-someaccount:org/repo.git isn't a forge url`. Can I modify the regex to always recognize `github.com-*` as github, or otherwise have `forge` figure out what I mean? Thanks.

**Comment by tarsius** [comment]
Re #44.

See https://github.com/magit/forge/wiki/Tips-and-Tricks. It explains how to teach Forge about such ssh identities.
