### ISSUE TITLE
buffers are not clearly labeled

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/forge#150]
When opening a topic, `forge` creates a buffer of mode `View Topic` with the buffer name being the repository/topic name, with leading and trailing asterisks. This is undesirable for people who configure the ibuffer to group buffers by buffer type. Currently, even if a user has configured ibuffer to collect all "magit..." buffers in a single ibuffer category, these new `forge` buffers appear in the "emacs internal" category.

My suggestion would be to either set the mode to `Magit` (or magit-something), or the buffer name to `magit: ...` or `forge: ...`.

**Comment by vermiculus** [comment]
I recommend you use `forge-post-mode` and `forge-topic-mode`.

**Comment by Boruch-Baum** [comment]
How could I have a choice in that? From a magit-status buffer, I press
"' l n" to view notifications, and then select on the notification
whose details I wish to view, and the buffer is created, labeled as I
described. How otherwise are you suggesting I proceed?

BTW, I'm posting this comment using 'forge'!

**Comment by Boruch-Baum** [comment]
There is an additional aspect to the buffer naming: I just now had a `magit-status` buffer open for project "A" (`emacs-w3m`), and in that context successfully made a comment to this issue on project "B" (magit/forge"), but when I went to then create a new issue for project "B" the issue was added to project "A" instead.

A separate issue would be how to handle multiple repositories simultaneously, but for the purposes of this issue, what should be added is some form of clear labeling as to what repository/project a specific `forge` buffer is attached. 

One specific example is buffer `*Issues*`. Besides not having any indication from the buffer name that it is part of package `forge` and relates to some project "foo", the heading text of the buffer lacks any such context. A suggestion would be a heading line "magit/forge issues: foo

**Comment by tarsius** [comment]
The name of the topic buffers now begin with "*forge: ". I looked into using the same mechanism as for Magit but I feel that's not really appropriate in its current form. Eventually I will have to get back to this but for your need this should be good enough.

> There is an additional aspect to the buffer naming: [...]

I don't fully understand what you are saying here but I fixed a bug that could potentially cause a post going to the wrong repository. So this is probably fixed. If not, then please open a new issue and describe more precisely what you are doing.

> One specific example is buffer `*Issues*`.

Oh... still have to do something about those.

**Comment by tarsius** [comment]
These buffers are now named `*forge-issue-list: OWNER/NAME*` and `*forge-pullreq-list: OWNER/NAME*`

**Comment by Boruch-Baum** [comment]
I just updated from melpa and restarted emacs, but melpa itself is
still on yesterday's version....
