### ISSUE TITLE
Checkout pull request without creating a local branch

### ISSUE THREAD

**Issue by mgalgs** [magit/forge#155]
When reviewing PRs, I frequently check out the code that I'm reviewing to take the code for a test drive in an ad-hoc, ephemeral manner.  I don't push any changes to the branch, I just want to pull it in locally for a closer look.

It would be great to have a new subcommand to check out a PR in a detached HEAD state without creating and configuring a branch.

I can code it up if this is something you'd be okay with adding.

**Comment by tarsius** [comment]
Expand the pull-request, move to the first commit and type `b b RET`.

**Comment by tarsius** [comment]
I might change it so you can also just move to the pull-request and type `b b RET`.

**Comment by mgalgs** [comment]
> Expand the pull-request, move to the first commit and type `b b RET`.

aah that works great!

> I might change it so you can also just move to the pull-request and type `b b RET`. On the other hand maybe `b b` in that location should just behave like `b y RET` in that location. I'll have to think about it.

Since `b b` is currently only used to **checkout** existing branches (or revisions) it would seem asymmetric to me to have it **create** a branch when invoked from a pull-request.  But I'm also a bit biased on this one ;)

Either way, I think we can probably close this issue.

**Comment by tarsius** [comment]
> Since `b b` is currently only used to **checkout** existing branches (or revisions) it would seem asymmetric to me to have it **create** a branch when invoked from a pull-request. 

Errrr, that was a thinko on my part.

**Comment by tarsius** [comment]
What I meant was to teach that command to suggest to *checking out* the appropriate branch (if that already exists) or `refs/pullreqs/N` (if that has already been fetched). I have implemented that now by making `magit-branch-or-commit-at-point` aware of pullreq sections.
