### ISSUE TITLE
Prefill pull request with commit details

### ISSUE THREAD

**Issue by danielcompton** [magit/forge#157]
[hub](https://hub.github.com) is a wrapper for Git which also provides GitHub specific commands. One of them is `hub pull-request`. It has a nice feature which I couldn't find in forge, where it prefills a pull-request draft from the commit messages on the branch.

https://github.com/github/hub/blob/v2.11.2/commands/pull_request.go#L261-L270

It has two modes:

1. If there is a single commit on the branch, it sets the title of the PR to the title of the commit message, and the remaining lines of the PR to the body of the commit message.
2. If there are multiple commits on a branch, it adds the entries as comments below the main body of the message. This lets you review all of the commits going into the PR and copy any relevant text directly.

Would something like this be useful for forge too?

**Comment by vermiculus** [comment]
At least related to, if not a duplicate of #70.

**Comment by danielcompton** [comment]
Yep, this is a dupe, sorry about that!
