### ISSUE TITLE
Add customization to not enabling bug-reference modes everywhere.

### ISSUE THREAD

**Issue by thomasf** [magit/forge#158]
I do want it in the forge-topic modes when reading issue comments but it's a bit too distracting for me and overrides other fortification modes.   Maybe a defcustom to for limiting where it inserts itself would be nice?

I quickly solved it for myself with an advice, not really sure which modes I want this in.. 

```el
(defun my-forge-bug-reference-setup-condition (orig-fun &rest args)
  (when (or (eq major-mode 'forge-topic-mode)
           (eq major-mode 'magit-staus-mode)
           (eq major-mode 'forge-issue-list-mode)
           (eq major-mode 'magit-log-mode))
    (apply orig-fun args)))
(advice-add 'forge-bug-reference-setup :around #'my-forge-bug-reference-setup-condition)
```

**Comment by tarsius** [comment]
You can use the new option `forge-bug-reference-hooks` for this now.
