### ISSUE TITLE
progn: Wrong type argument: arrayp, forge-gitlab-repository

### ISSUE THREAD

**Issue by robbyoconnor** [magit/forge#159]
When doing `M-x forge-pull`, 

I get the following: 

`progn: Wrong type argument: arrayp, forge-gitlab-repository`

Not sure if there was a recent change or if I'm doing something wrong..

**Comment by dsdshcym** [comment]
Got an similar error when trying to run `forge-pull` for a new repo:

```
closql--oset: Wrong type argument: arrayp, forge-github-repository
```

**Comment by jaor** [comment]
Same error with github repos, only there it's forge-pullreq:

```
error in process filter: closql--oset: Wrong type argument: arrayp, forge-pullreq
error in process filter: Wrong type argument: arrayp, forge-pullreq
```

**Comment by scymtym** [comment]
I started seeing this error since building Emacs from source resulting in `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-06-03`.

Apparently, the `eieio--object-class` function was changed to return a symbol instead of class object. Whole story is here: https://github.com/emacs-mirror/emacs/commit/5f01af6c8e0f7355f7a99a80ff32369071f65eda

**Comment by jaor** [comment]
Thanks for the pointer, Jan.  In my case, setting
`eieio-backward-compatibility` seems to have cured the problem, although
i haven't been using forge with that a lot yet.

**Comment by npostavs** [comment]
>  In my case, setting `eieio-backward-compatibility` seems to have cured the problem,

Do you mean setting to `nil` or `t`?

**Comment by aaronjensen** [comment]
It fails for me with `eieio-backward-compatibility` as `nil` or `t`, though with different errors.

The error from the OP is what I get when it's `t`. When it's `nil`, I get:

```
slot-boundp: Wrong type argument: eieio-object-p, #s(forge-database #<process emacsql-sqlite> #<buffer  *emacsql-log*> #<finalizer> "/Users/user/.emacs.d/.cache/forge-database.sqlite")
```

**Comment by jaor** [comment]
On Fri, Jun 14 2019, Noam Postavsky wrote:

>     In my case, setting eieio-backward-compatibility seems to have cured the problem,
>    
> Do you mean setting to nil or t?

I mean nil. Which yes, seems weird.

Things work for me with that setting except that eieio then
decides to be very noisy and show messages every time some deprecated
function is called.  It's particularly annoying in the eioeio's method
`make-instance`: every time other packages create an instance in a way
it doesn't like, i get the unconditional noise, and that method is
called all the time.  So i've had to modify its definition eliding the
message (ideally, eieio would provide a flag to turn off warnings).

**Comment by npostavs** [comment]
> The error from the OP is what I get when it's `t`. When it's `nil`, I get:

Are you setting on the fly? Does it help if you set to `nil` at the top of your init.el, before any packages are loaded?

**Comment by npostavs** [comment]
Oh, it just occurred to me that my Emacs change referenced above (emacs-mirror/emacs@5f01af6), changes some `defsubst`s, so this might be a case of stale elc. Does deleting .elc files of forge and closql help?

**Comment by aaronjensen** [comment]
Unfortunately, no, not for me.

**Comment by npostavs** [comment]
> my Emacs change referenced above ([emacs-mirror/emacs@5f01af6](https://github.com/emacs-mirror/emacs/commit/5f01af6)),

Okay, I've taken a closer look, and it seems the problem is due to `closql` digging into eieio internals which my Emacs change fiddled with. The fix seems simple enough: emacscollective/closql#1

**Comment by aaronjensen** [comment]
This worked for me, thank you @npostavs and @tarsius .
