### ISSUE TITLE
Add support for GitLab merge_when_pipeline_succeeds

### ISSUE THREAD

**Issue by danlamanna** [magit/forge#162]
This may be a feature request for Magit proper, but since it's tied to GitLab I thought it might belong in forge.

GitLab 11.10 added support for adding options to `git push` which automatically create an MR, and merge it if the pipeline succeeds.

The documentation for the options is [here](https://docs.gitlab.com/ee/user/project/merge_requests/#git-push-options).

**Comment by tarsius** [comment]
What happens if you create a merge request like this? A new merge request whose title is something like "no title has been set for this merge request"?!

The target branch most likely can also be set using the REST API instead of by pushing, which seems like a more appropriate interface.

`merge_request.merge_when_pipeline_succeeds` sounds useful, though isn't something I myself am likely to use.

**Comment by danlamanna** [comment]
> What happens if you create a merge request like this? A new merge request whose title is something like "no title has been set for this merge request"?!

It would be the same as the default in the GUI when you create an MR, for GitLab this is the title of the most recent commit on the branch. I'm not sure what GitHub does in this case, but I imagine something similar.

**Comment by tarsius** [comment]
You can add such arguments like this:

``` emacs-lisp
(transient-append-suffix 'magit-push '(0 -1)
  '("+c" "Create merge-request"
    "--push-option=merge_request.create"))

(transient-append-suffix 'magit-push '(0 -1)
  '("+b" "Target branch"
    "--push-option=merge_request.target="
    :history-key magit-revision-history
    :reader (lambda (prompt initial-input history)
              ;; You could get fancier here.
              (magit-completing-read prompt nil nil nil
                                     (or initial-input "master")))))

(transient-append-suffix 'magit-push '(0 -1)
  '("+m" "Merge on success"
    "--push-option=merge_request.merge_when_pipeline_succeeds"))
```
