### ISSUE TITLE
error in process filter after losing access to repository

### ISSUE THREAD

**Issue by aaronjensen** [magit/forge#164]
I don't know where these urls are coming from, perhaps my notifications? I see these errors every time I forge pull (`org/repo` anonymized) :

```
error in process filter: ghub-repository-id: Repository "org/repo" does not exist on "api.github.com".
Maybe it was renamed and you have to update "remote.<remote>.url"?
error in process filter: Repository "org/repo" does not exist on "api.github.com".
Maybe it was renamed and you have to update "remote.<remote>.url"?
```

Resetting cache does not help.

**Comment by aaronjensen** [comment]
> I think we'll need a backtrace here.

Emailed

**Comment by tarsius** [comment]
Because of line-wrapping I had a hard time making sense of that. I did however spot `forge--ghub-massage-notification` in there, so that does answer one of the questions I had.

Please answer this other question:

> Seems I didn't take "losing access to repository" literal enough. You are talking about a repository that you had access to and now the permissions that would allow you to continue to interact with that repository have been revoked, right?

**Comment by tarsius** [comment]
Try if this helps:

```diff
diff --git a/lisp/forge-github.el b/lisp/forge-github.el
index 57adaed..920162f 100644
--- a/lisp/forge-github.el
+++ b/lisp/forge-github.el
@@ -299,10 +299,17 @@ (cl-defmethod forge--pull-notifications
     (forge--msg nil t nil "Pulling notifications")
     (pcase-let*
         ((`(,_ ,apihost ,forge ,_) spec)
-         (notifs (--keep (forge--ghub-massage-notification it forge githost)
-                         (forge--ghub-get nil "/notifications"
-                                          '((all . "true"))
-                                          :host apihost :unpaginate t)))
+         (notifs (-keep (lambda (data)
+                          ;; Github may return notifications for repos
+                          ;; the user no longer has access to.  Trying
+                          ;; to retrieve information for such a repo
+                          ;; leads to an error, which we suppress.
+                          (with-demoted-errors "forge--pull-notifications: %S"
+                            (forge--ghub-massage-notification
+                             data forge githost)))
+                        (forge--ghub-get nil "/notifications"
+                                         '((all . "true"))
+                                         :host apihost :unpaginate t)))
          (groups (-partition-all 100 notifs))
          (pages  (length groups))
          (page   0)
```

**Comment by tarsius** [comment]
> The repository does not appear in `forge-remove-repository`. 

I believe that can only mean that there isn't actually an entry for that repo in the database.

**Comment by aaronjensen** [comment]
> Seems I didn't take "losing access to repository" literal enough. You are talking about a repository that you had access to and now the permissions that would allow you to continue to interact with that repository have been revoked, right?

That's correct.



> Try if this helps:

I still see the first half of the error:

```
error in process filter: ghub-repository-id: Repository "org/repo" does not exist on "api.github.com".
Maybe it was renamed and you have to update "remote.<remote>.url"?
```

But then it continues on to pull the rest of the notifications, which is different, if I remember correctly. For some reason, my Pull requests section in my repo I was testing in is not updating properly. It's showing hundreds of PRs as open that are actually closed. I don't know if this is related or not...

**Comment by aaronjensen** [comment]
```
  ghub-repository-id("my-org" "my-proj-static-api" :host "api.github.com" :auth forge :forge ghub)
  #f(compiled-function (class host owner name &optional stub) "Return (OUR-ID . THEIR-ID) of the specified repository.\nIf optional STUB is non-nil, then the IDs are not guaranteed to\nbe unique.  Otherwise this method has to make an API request to\nretrieve THEIR-ID, the repository's ID on the forge.  In that\ncase OUR-ID derives from THEIR-ID and is unique across all\nforges and hosts.  " #<bytecode 0x1ff6c7e845a9>)(forge-github-repository "github.com" "my-org" "my-proj-static-api" nil)
  apply(#f(compiled-function (class host owner name &optional stub) "Return (OUR-ID . THEIR-ID) of the specified repository.\nIf optional STUB is non-nil, then the IDs are not guaranteed to\nbe unique.  Otherwise this method has to make an API request to\nretrieve THEIR-ID, the repository's ID on the forge.  In that\ncase OUR-ID derives from THEIR-ID and is unique across all\nforges and hosts.  " #<bytecode 0x1ff6c7e845a9>) forge-github-repository ("github.com" "my-org" "my-proj-static-api" nil))
  forge--repository-ids(forge-github-repository "github.com" "my-org" "my-proj-static-api" nil)
  #f(compiled-function (&rest rest) "Return the repository identified by HOST, OWNER and NAME." #<bytecode 0x1ff6c7e850ed>)(("github.com" "my-org" "my-proj-static-api") nil create)
  apply(#f(compiled-function (&rest rest) "Return the repository identified by HOST, OWNER and NAME." #<bytecode 0x1ff6c7e850ed>) ("github.com" "my-org" "my-proj-static-api") (nil create))
  forge-get-repository(("github.com" "my-org" "my-proj-static-api") nil create)
  forge--ghub-massage-notification(...)
  -keep((closure (... ... ... ... ... ... ... ... ... ... ... ... t) (data) (condition-case err ... ...)) ((... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ...) ...))
  (let* ((notifs (-keep #'(lambda (data) (condition-case err (forge--ghub-massage-notification data forge githost) (... ... nil))) (forge--ghub-get nil "/notifications" '((all . "true")) :host apihost :unpaginate t))) (groups (-partition-all 100 notifs)) (pages (length groups)) (page 0) (result nil)) (let (--cl-cb--) (setq --cl-cb-- #'(lambda (&optional data _headers _status _req) (progn (if data (progn ...)) (if groups (progn ... ... ...) (forge--msg nil t t "Pulling notifications") (forge--msg nil t nil "Storing notifications") (let ... ... emacsql--result) (forge--msg nil t t "Storing notifications") (if callback ...))))) (funcall --cl-cb--)))
  (let ((forge x523) (apihost x521)) (let* ((notifs (-keep #'(lambda (data) (condition-case err ... ...)) (forge--ghub-get nil "/notifications" '(...) :host apihost :unpaginate t))) (groups (-partition-all 100 notifs)) (pages (length groups)) (page 0) (result nil)) (let (--cl-cb--) (setq --cl-cb-- #'(lambda (&optional data _headers _status _req) (progn (if data ...) (if groups ... ... ... ... ... ...)))) (funcall --cl-cb--))))
  (let* ((x520 (cdr spec)) (x521 (car x520)) (x522 (cdr x520)) (x523 (car x522)) (x524 (cdr x522)) (x526 (cdr x524))) (let ((forge x523) (apihost x521)) (let* ((notifs (-keep #'(lambda ... ...) (forge--ghub-get nil "/notifications" '... :host apihost :unpaginate t))) (groups (-partition-all 100 notifs)) (pages (length groups)) (page 0) (result nil)) (let (--cl-cb--) (setq --cl-cb-- #'(lambda (&optional data _headers _status _req) (progn ... ...))) (funcall --cl-cb--)))))
  (let ((spec (assoc githost forge-alist))) (if spec nil (error "No entry for %S in forge-alist" githost)) (forge--msg nil t nil "Pulling notifications") (let* ((x520 (cdr spec)) (x521 (car x520)) (x522 (cdr x520)) (x523 (car x522)) (x524 (cdr x522)) (x526 (cdr x524))) (let ((forge x523) (apihost x521)) (let* ((notifs (-keep #'... (forge--ghub-get nil "/notifications" ... :host apihost :unpaginate t))) (groups (-partition-all 100 notifs)) (pages (length groups)) (page 0) (result nil)) (let (--cl-cb--) (setq --cl-cb-- #'(lambda ... ...)) (funcall --cl-cb--))))))
  (progn (let ((spec (assoc githost forge-alist))) (if spec nil (error "No entry for %S in forge-alist" githost)) (forge--msg nil t nil "Pulling notifications") (let* ((x520 (cdr spec)) (x521 (car x520)) (x522 (cdr x520)) (x523 (car x522)) (x524 (cdr x522)) (x526 (cdr x524))) (let ((forge x523) (apihost x521)) (let* ((notifs (-keep ... ...)) (groups (-partition-all 100 notifs)) (pages (length groups)) (page 0) (result nil)) (let (--cl-cb--) (setq --cl-cb-- #'...) (funcall --cl-cb--)))))))
  (closure (t) (_class githost &optional callback) (progn (let ((spec (assoc githost forge-alist))) (if spec nil (error "No entry for %S in forge-alist" githost)) (forge--msg nil t nil "Pulling notifications") (let* ((x520 (cdr spec)) (x521 (car x520)) (x522 (cdr x520)) (x523 (car x522)) (x524 (cdr x522)) (x526 (cdr x524))) (let ((forge x523) (apihost x521)) (let* (... ... ... ... ...) (let ... ... ...)))))))(forge-github-repository "github.com" #f(compiled-function () #<bytecode 0x1ff6cd84b555>))
  apply((closure (t) (_class githost &optional callback) (progn (let ((spec (assoc githost forge-alist))) (if spec nil (error "No entry for %S in forge-alist" githost)) (forge--msg nil t nil "Pulling notifications") (let* ((x520 (cdr spec)) (x521 (car x520)) (x522 (cdr x520)) (x523 (car x522)) (x524 (cdr x522)) (x526 (cdr x524))) (let ((forge x523) (apihost x521)) (let* (... ... ... ... ...) (let ... ... ...))))))) forge-github-repository ("github.com" #f(compiled-function () #<bytecode 0x1ff6cd84b555>)))
  forge--pull-notifications(forge-github-repository "github.com" #f(compiled-function () #<bytecode 0x1ff6cd84b555>))
```

**Comment by tarsius** [comment]
For me the notification about your reply on the issue from the deleted repository was deleted even on the second try and this time I made sure the notification was still unread before deleting the repository. But your case is a bit different--the repository isn't deleted, you just don't have access to it anymore.

**Comment by aaronjensen** [comment]
Want me to create a repo, invite you and then create a notification and then remove you?

**Comment by tarsius** [comment]
So this backtrace very much looks like the error occurs inside the code I wrapped with the `with-demoted-errors` and yet the error appears not to be demoted for you. Are you sure you applied the above patch and made sure that that is loaded not the outdated `*.elc` file. You might want to add some debugging statements to this function to make sure the error really occurs where I think it occurs and that the modified version is called.

> Want me to create a repo, invite you and then create a notification and then remove you?

It's worth a try :stuck_out_tongue:

**Comment by aaronjensen** [comment]
Hmm, looks like it's there:

```
TESTING <-- my test message
Pulling notifications...
forge--pull-notifications: (error "Repository \"org/proj-static-api\" does not exist on \"api.github.com\".
Maybe it was renamed and you have to update \"remote.<remote>.url\"?")
```

`with-demoted-errors` demotes them to a message apparently, so it makes sense that i'm seeing them as a message. AFAICT, that patch is being effective. I'm getting further with notifications and they're actually being stored now. 

I think my pull request issue may actually just be me misreading the formatting. Only the top PR is actually open. I think the others have unread notifications, so maybe the formatting just makes them look open? I really only want to see the open PRs here (there are only 2 on this repo, not 300+. 

<img width="766" alt="CleanShot 2019-06-18 at 09 33 56@2x" src="https://user-images.githubusercontent.com/8588/59702288-36b8e480-91ac-11e9-8a2d-a24b23d01101.png">

I just marked all my notifications as read and forge pull'd again and i'm now down to 7 PRs.

**Comment by aaronjensen** [comment]
Btw, i sent you an invite to a repo.

**Comment by tarsius** [comment]
> `with-demoted-errors` demotes them to a message apparently, so it makes sense that i'm seeing them as a message. AFAICT, that patch is being effective.

Right, I misinterpreted what you said earlier.  Seems everything is good now.  We still do not know *why* there are bogus notifications for you (and I think we should continue to at least show the error *message*) but at least updating of the remaining messages works now.

> I think my pull request issue may actually just be me misreading the formatting. Only the top PR is actually open. I think the others have unread notifications, so maybe the formatting just makes them look open?

- Open topics are supposed to use `default's color.
- Closed topics are supposed to be grayed out
- Topics with unread replies are supposed to be bold.

It seems your theme doesn't get that quite right.

> I really only want to see the open PRs here (there are only 2 on this repo, not 300+.

All unread topics are always shown (and that cannot be disabled), so...

> I just marked all my notifications as read and forge pull'd again and i'm now down to 7 PRs.

...that's what you have to do.

In addition to all unread and all open issues, five closed issues are also shown by default, but that can be changed by setting the `cdr` of `forge-topic-list-limit` to `0`.

**Comment by tarsius** [comment]
Off-topic:

Your screenshot is not shown in forge. The markup is:

```
<img width="766" alt="CleanShot 2019-06-18 at 09 33 56@2x" src="https://user-images.githubusercontent.com/8588/59702288-36b8e480-91ac-11e9-8a2d-a24b23d01101.png">
```

In some related issue the screenshot is shown given this markup:

```
![2019-06-18-072545_1918x1078_scrot](https://user-images.githubusercontent.com/229679/59692687-58a96b80-919a-11e9-8d67-981f4c1e5fe2.png)
```

How did you insert the image?

@fosskers And how did *you* insert the image at https://github.com/magit/magit/issues/3903?

**Comment by fosskers** [comment]
I used Github's interface. The word "selecting" can be clicked, bringing up a file prompt. The image then gets uploaded to GH somehow, and displayed. 

Meta post!

![2019-06-18-103849_1918x1078_scrot](https://user-images.githubusercontent.com/229679/59706437-56083f80-91b5-11e9-9ec8-f3abc5719236.png)

The markdown itself looks like this:
```
![2019-06-18-103849_1918x1078_scrot](https://user-images.githubusercontent.com/229679/59706437-56083f80-91b5-11e9-9ec8-f3abc5719236.png)
```

**Comment by tarsius** [comment]
> The markdown itself looks like this:

But in forge that gets displayed as an image even though it is inside a code block.  And down the rabbit hole we go...

**Comment by tarsius** [comment]
But in my post that did not happen. I am guessing that's because you didn't put an empty line before the three opening backticks. Let's try editing that...

**Comment by tarsius** [comment]
... yup, that was it.

**Comment by aaronjensen** [comment]
> Your screenshot is not shown in forge. The markup is:

That markup is fine afaict. It's just not markdown. Both are valid on github. I drag and dropped an image in to create it.



> It seems your theme doesn't get that quite right.

Ah, it's my theme so I'll look into it.



> All unread topics are always shown (and that cannot be disabled), so...

That's too bad... I tend to ignore notifications (because i get the mails), so this just adds another step to keep things clean.



> In addition to all unread and all open issues, five closed issues are also shown by default, but that can be changed by setting the `cdr` of `forge-topic-list-limit` to `0`.

thanks.

**Comment by tarsius** [comment]
> That markup is fine afaict. It's just not markdown. Both are valid on github. I drag and dropped an image in to create it.

I  wasn't suggesting otherwise. It appears `markdown-mode` doesn't support it though, so I have to implement support myself it seems. I just wanted to know in what case Github uses this syntax, which we currently don't support because if you actually written this manually or had done something really obscure to cause Github to cause this syntax, then it would be less important to implement support for it soon.

> That's too bad... I tend to ignore notifications (because i get the mails), so this just adds another step to keep things clean.

The whole un-/read thing is really messy right now and Github is not being helpful in this regard. Some major changes will be required, but I don't know what to do yet, so I'll leave things as-is until I have a better idea and the time to implement it.

**Comment by tarsius** [comment]
So the original issue has been address, I think.

**Comment by aaronjensen** [comment]
Yes, thank you!
