### ISSUE TITLE
Issues buffer not inheriting magit/forge keymaps

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/forge#165]
From a buffer "*Issues*" (forge-version melpa 2019-06-19), typing a
single quote or `C-c C-c` does nothing. I was expecting the buffer to
inherit magit, or at least forge, keybindings.

Note that buffer "*forge-notifications*" does bind those keys.

**Comment by tarsius** [comment]
I have bound `'` now.

> `C-c C-c` does nothing

Those are the keys that are usually bound to the "perform **the** action" command. I cannot think of such a primary action in this case.

> I was expecting the buffer to inherit magit,

`magit-mode-map` has many bindings that seem inappropriate to me.

> or at least forge, keybindings.

There aren't actually that many forge commands that aren't context sensitive variants of existing commands and either already bound in forges list buffers or not suitable here. `forge-dispatch` was missing, but I have added the `'` binding for that now, as suggested.

If you have concrete suggestions for commands that should but are not available in these buffers, then please mention them explicitly. I don't think inheriting from `magit-mode-map` would be the correct thing to do.

**Comment by Boruch-Baum** [comment]
On 2019-06-21 03:57, Jonas Bernoulli wrote:
>    I have bound ' now.

Thanks.

>    If you have concrete suggestions for commands that should but are not
>    available in these buffers, then please mention them explicitly.

  ? For the magit pop-up of the issue buffer's project
  b for branching within the issue buffer's project
  l for logs of the issue buffer's project

Maybe also:

  f/F for fetch/Pull of the issue buffer's project
  y   for refs of the issue buffer's project

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tarsius** [comment]
If added `magit-dispatch`. Together with the `forge-dispatch` binding that makes the non-contextual command from Magit buffers in these buffers too, though with one additional key press.

I am not adding the other suggested bindings. Maybe I will change my mind about this one day, maybe not.

If you want to go all in, then you can do so using:

```emacs-lisp
(set-keymap-parent forge-topic-list-mode-map
                   (make-composed-keymap tabulated-list-mode-map
                                         magit-mode-map))
```
