### ISSUE TITLE
https? url with username/password are not recognised

### ISSUE THREAD

**Issue by ramblehead** [magit/forge#169]
```forge--split-url()``` fails to recognise https urls with username e.g.:
```(forge--split-url "https://username@github.com/organization/project.git")```
returns ```nil```

```forge--split-url()``` uses regexp returned by ```forge--url-regexp()``` to recognise url strings. ```forge--url-regexp()``` version which I have from melpa is the following:

```elisp
(defun forge--url-regexp ()
  (concat "\\`\\(?:git://\\|[^/@]+@\\|ssh://\\(?:[^/@]+@\\)?\\|https?://\\)"
          (regexp-opt (mapcar #'car forge-alist) t)
          "[:/]\\(.+?\\)"
          "\\(?:\\.git\\|/\\)?\\'"))
```

Not sure, if it was intentional to not allow username in https urls?

Possible fix:
```elisp
(defun forge--url-regexp ()
  (concat "\\`\\(?:git://\\|[^/@]+@\\|ssh://\\(?:[^/@]+@\\)?"
          "\\|https?://\\(?:[^/@]+@\\)?\\)"
          (regexp-opt (mapcar #'car forge-alist) t)
          "[:/]\\(.+?\\)"
          "\\(?:\\.git\\|/\\)?\\'"))
```

Thank you for magit and forge! Both are magical :)

**Comment by tarsius** [comment]
> Not sure, if it was intentional to not allow username in https urls?

I wasn't aware Github allowed that.

Do you know where that is documented in the Github documentation?
Are you sure the password can also be given like this?

**Comment by ramblehead** [comment]
I just followed common URL standard, which allows username and password:
"3.1. Common Internet Scheme Syntax" @ https://www.ietf.org/rfc/rfc1738.txt

When running:
```git clone https://username:password@github.com/organization/project.git```
git would remember username and password in ```project/.git/config``` and use them for all further operations without asking (careful though, ```project/.git/config``` is unencrypted).

When running:
```git clone https://username@github.com/organization/project.git```
git would remember username and only ask for password. I often use this approach as my username is widely known ;) and there is no need to keep re-entering it.

> Do you know where that is documented in the Github documentation?

No, I have not seen it in Github documentation. Possibly, it is not documented to discourage users storing their passwords in ```project/.git/config```...

> Are you sure the password can also be given like this?

Yes
