### ISSUE TITLE
`forge--split-url-path` fails to parse URLs of gitlab projects in subgroups

### ISSUE THREAD

**Issue by tomjorquera** [magit/forge#17]
Gitlab allows to put repositories inside [subgroups](https://docs.gitlab.com/ee/user/group/subgroups/). This will create a repo with path `gitlab.com/foo/bar/baz.git`.

An example from gitlab: https://gitlab.com/gitlab-org/release/tasks

When trying to `forge-pull` on such repo will return an error "Cannot determine forge repository.  git@gitlab.com:gitlab-org/release/tasks.git isn’t a forge url"

I believe it is caused by `forge--split-url-path` that only supports paths with 2 components (while `(forge-split-url-path "foo/bar")` works as expected `(forge-split-url-path "foo/bar/baz")` fails.

I guess some other forges offering a similar functionality could be affected too.

(note: sorry I accidentally created the issue before finishing writing it, so I closed it and  re-opened it after finishing it up)

**Comment by tarsius** [comment]
That should work now.  You'll have to update `forge` *and* `ghub`.

**Comment by tarsius** [comment]
Should be fixed now.
