### ISSUE TITLE
error in process sentinel: forge--color-brightness: Color doesn’t have #NNNNNN format

### ISSUE THREAD

**Issue by davep** [magit/forge#170]
This seems to have started coinciding with forge updating to `forge-20190708.2203` for me. If I `forge-pull` I get the following error message showing:

```
forge--color-brightness: Color doesn’t have #NNNNNN format
```

I modified `forge--color-brightness` to report the colour it wasn't happy with when throwing the `error` and, in this case, it's a colour value of "#666".

I'm running against a locally-hosted GitLab and there is such a label colour:

![image](https://user-images.githubusercontent.com/28237/61038156-69798580-a3c4-11e9-807b-f69fbf0a26a3.png)

**Comment by tarsius** [comment]
What is the six digit representation of `#666`? `#606060`?

**Comment by davep** [comment]
I believe so, yes. It's one of the valid formats listed here: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#RGB_colors

**Comment by tarsius** [comment]
According to that page it is the same as `#666666`.

**Comment by davep** [comment]
Yes, sorry, misread the above. The latter is correct.

**Comment by tarsius** [comment]
That should do it.

**Comment by davep** [comment]
Thanks, I'll give it a test very soon.

```elisp
(error "Color does not have #RRGGBB or #RGB format")
```

It might be worth noting, from the above link, that something like `#6666` is also valid (as is `#66666666`). For example:

![image](https://user-images.githubusercontent.com/28237/61041718-b82a1e00-a3ca-11e9-95af-a63ae17fd091.png)
![image](https://user-images.githubusercontent.com/28237/61041759-cd9f4800-a3ca-11e9-9deb-548d59be6bab.png)
![image](https://user-images.githubusercontent.com/28237/61041794-dc85fa80-a3ca-11e9-859d-d20119ca775d.png)

Etc...

**Comment by tarsius** [comment]
Emacs has some code to determine whether to use the dark or light face definition and given that this is getting more complicated than I originally thought it would probably be better to locate and reuse that than to re-implement it. Maybe you could help me locate it?

**Comment by davep** [comment]
I don't know of the feature you mention, but if I get some time I'd be happy to have a dig around (which will likely mean trying to better understand what forge is doing here too). Might be a few days I'm afraid as I've got quite a lot on at the moment.

**Comment by davep** [comment]
Would it be helpful for me to open this as a new issue (that way it should serve as a reminder to me that I need to take a look)?

**Comment by tarsius** [comment]
> I don't know of the feature you mention

Depending on `(set-face-foreground 'default THIS)` Emacs uses the light or the dark theme. The code that makes that decision based on THIS, might be suitable for our need too, provided it can be called from lisp.

> Would it be helpful for me to open this as a new issue

No, but I'll reopen this one if that helps you.

**Comment by davep** [comment]
Okay, I see. Yes, please reopen and when I get some time I'll dive into
this.

**Comment by davep** [comment]
I've had a brief look and, sadly, it's confirmed that I'm far too ignorant of how faces and fonts and the like work in Emacs to be any help here. Sorry.

**Comment by tarsius** [comment]
I had a look too yesterday and it looks like Emacs doesn't provide any rgba support. I am inclined to simply discard that information and assume full opacity.

**Comment by davep** [comment]
Seems like a fair approach to me; as long as it doesn't throw an `error` over the other two forms that could be used and just uses the RGB/RRGGBB information I'd imagine that'd work well in most/all cases.

**Comment by tarsius** [comment]
The alpha channel is now simply discarded and if the color is completely unrecognized, then black is used instead of raising an error.
