### ISSUE TITLE
Base and head repos/refs are not displayed for pull requests

### ISSUE THREAD

**Issue by darth10** [magit/forge#171]
This is something fairly basic shown in GitHub.
Since it's available on the API, it should be easy to surface.

![image](https://user-images.githubusercontent.com/1171466/61182576-ae820e00-a689-11e9-80ed-eccf8f783a4f.png)

I've done some work on this in #168.

**Comment by tarsius** [comment]
I have seen your ping but was busy the last two days. There is no need for this duplicate.
