### ISSUE TITLE
Cookies must be enabled to use GitHub

### ISSUE THREAD

**Issue by pedz** [magit/forge#174]
I'm restarting my emacs after each attempt to get a fresh start.  In my init.el I have

    (with-eval-after-load 'magit
      (require 'forge))

    (with-eval-after-load 'forge
      (add-to-list 'forge-alist
		   '("github.blah.blah.blah.com"
		     "github.blah.blah.blah.com/api"
		     "github.blah.blah.blah.com"
		     forge-github-repository)))

My github is an Enterprise Github that seems to be old because the "api" link takes me to the 2.14 documentation and the errors point me to the 2.14 documentation as well.

I'm using el-get and the commit id for forge is c1a5db6955788fc0245f684c9746b93728324ae4 with a date of Jul 20, 2019.

Path 1... I start with nothing in my .authinfo (and the above setup), I get into a git repository and do "f y" and go through the wizard and end up with this message:

    ghub--confirm-create-token: HTTP Error: 403, "Forbidden", "/api/authorizations", ((message . "Cookies must be enabled to use GitHub.") (documentation_url . "https://github.com/magit/ghub/wiki/Github-Errors"))

Path 2... I change the above from .../api to .../api/v3 (again, starting from a fresh emacs) and go through the wizard.  This time it asks me to save the .authinfo.  I say "y" and then it gives me:

    ghub--signal-error: HTTP Error: 404, "Not found", "/api/v3/graphql", ((message . "Not Found") (documentation_url . "https://developer.github.com/enterprise/2.14/v3"))

but I think the path should be api/graphql according to [this page](https://developer.github.com/enterprise/2.14/v4/guides/forming-calls/#the-graphql-endpoint)

which is why I removed the /v3 part of the URL.  I've noticed one example has /v4 so I tried that and I end up with the first message about cookies (before asking to save .authinfo)

Emacs version is 26.1 on a Mac built by homebrew.

**Comment by tarsius** [comment]
It could have been so easy

    REST:    https://github.com/api/
    GRAPHQL: https://github.com/api/graphql/

could have generalized as

    REST:    https://[hostname]/api/
    GRAPHQL: https://[hostname]/api/graphql/

but not so fast.

Based on circumstantial evidence we must conclude that the following four Github Enterprise API URL scheme genotypes exist:

    TYPE I
    REST:    https://[hostname]/api/
    GRAPHQL: https://[hostname]/api/graphql/

    TYPE II
    REST:    https://[hostname]/
    GRAPHQL: https://[hostname]/graphql/

    TYPE III
    REST:    https://[hostname]/api/v3/
    GRAPHQL: https://[hostname]/api/graphql/

    TYPE IV
    REST:    https://[hostname]/v3/
    GRAPHQL: https://[hostname]/graphql/

Because `ghub.el` has to support both I/III and II/IV what it calls HOST can take either the form `[hostname]` or `[hostname]/[path]`, so we might call e.g. `example.com/api` a "host", which isn't technically correct I guess.  Moving on...

The bigger problem, however, is the different needs of I/II vs. III/IV.  We can be near certain that `.../v3/graphql/` is never correct because the GraphQl API is also referred to as "the v4 API". But we have settled on using either `[hostname]` or `[hostname]/[path]` as the key and if `[path]` contains `v3`, then that is a problem.

We address it using a hack.  Hurray.

Please try the `non-v3` branch of `ghub`.

**Comment by pedz** [comment]
I was playing around today and tried more or less the same change and it got past that point but then eventually ended up in ghub--graphql-vacuum but now host doesn't match what is in .authinfo so it stops and wants to create a new token.

I had to go and couldn't continue but... would it work to duplicate the .authinfo line with /api/graphql (instead of /apt/v3)?  (i.e. have two entries, slightly different with the same token.

As I said, I had to go home and didn't have a chance to try it.

I will try your change as well but I'm guessing it will have the same effect.

**Comment by pedz** [comment]
I pulled down the non-v3 branch.  Over the weekend while reading the ghub manual I discovered steps I had not done.  I cleaned up my ~/.gitconfig and removed the extra `[github xxx]` entries that had been created in all my testing (for /api /api/v4 and /api/graphql).  I also did the `git config github.host xxx` command per repository and tested and it didn't work.  But then I added this diff

    diff --git a/ghub-graphql.el b/ghub-graphql.el
    index e920cdd..8cb45d6 100644
    --- a/ghub-graphql.el
    +++ b/ghub-graphql.el
    @@ -237,7 +237,11 @@ See Info node `(ghub)GraphQL Support'."
	 (setq username (ghub--username host forge)))
       (ghub--graphql-retrieve
	(ghub--make-graphql-req
    -    :url       (url-generic-parse-url (concat "https://" host "/graphql"))
    +    :url       (url-generic-parse-url (concat "https://"
    +                                              (if (string-suffix-p "/v3" host)
    +                                                  (substring host 0 -3)
    +                                                host)
    +                                              "/graphql"))
	 :method    "POST"
	 :headers   (ghub--headers nil host auth username forge)
	 :handler   'ghub--graphql-handle-response

which is roughly the same change but in `ghub--graphql-vacuum` and it appears to be working but I haven't really played with it yet.  If we can, lets keep this open a few more days and I'll update you with issues if I hit any.

Thank you for your time

**Comment by tarsius** [comment]
Obviously this change has to be made in both places. I did not consider that `ghub--graphql-vacuum` does not use `ghub-request` when I only edited the latter. I have pushed an update.

**Comment by pedz** [comment]
You have a typo in the last change:

    git diff
    diff --git a/ghub-graphql.el b/ghub-graphql.el
    index c17647a..b39f1bc 100644
    --- a/ghub-graphql.el
    +++ b/ghub-graphql.el
    @@ -239,9 +239,9 @@ See Info node `(ghub)GraphQL Support'."
	(ghub--make-graphql-req
	 :url       (url-generic-parse-url
		     (format "https://%s/graphql"
    -                        (if (string-suffix-p "/v3" host))
    +                        (if (string-suffix-p "/v3" host)
				 (substring host 0 -3)
    -                          host))
    +                          host)))
	 :method    "POST"
	 :headers   (ghub--headers nil host auth username forge)
	 :handler   'ghub--graphql-handle-response

**Comment by pedz** [comment]
I've been using forge today quite a bit.  Its really awesome.

**Comment by tarsius** [comment]
Thanks!

I have pushed the (fixed) kludge now.

**Comment by MageJohn** [comment]
Hey @tarsius! Should this kludge be put in the documentation? I was able to set up forge with my companies GHE installation thanks to finding the discussion here, but I had to spend a while looking.

**Comment by tarsius** [comment]
I've added a note to the doc-string. (Couldn't find a good place to do it in the manual.)

**Comment by MageJohn** [comment]
Wow, that was fast! Thanks so much!
