### ISSUE TITLE
Forge not pulling updated version of a PR

### ISSUE THREAD

**Issue by gautammohan** [magit/forge#180]
Hi there,

I just started using `forge` and it's great! I am running into an issue where an open PR on Github is not reflecting the latest version in `forge`. On Github, the PR has a few comments and a review request, but the version shown in `magit` on my local machine only has the diffs + first comment. The "review-requests" field is empty, and it only has one comment, despite there being 2 more displayed on github.

I have tried `forge-reset-database` several times before running `forge-pull`, but that did not help.

Do you have any suggestions of steps I can take to debug/diagnose this issue? Unfortunately the repository I am referencing is private, but I could perhaps try and repro this behavior on a fresh public repo if you think that would help.

**Comment by gautammohan** [comment]
I should also note that the comments in question are "review comments", I think? They refer to specific diffs of the PR, and are not left on the main thread of the PR, if that makes sense. Sorry for not being totally clear, I am unfamiliar with the exact github terms to describe these things...

**Comment by tarsius** [comment]
> I should also note that the comments in question are "review comments", I think?

Indeed. Forge doesn't support those yet. The feature request for that is #75.
