### ISSUE TITLE
GitLab Topic State: merge/merged

### ISSUE THREAD

**Issue by jkdufair** [magit/forge#181]
Would it be possible to support GitLab's functionality where the PR's branch is merged and the PR is closed in one operation? I just tried out manually merging the branch with magit and then closing the PR with forge and GitLab indicates that it was closed without merging. And it shows up in the "closed" tab vs. the "merged" tab when browsing a project's PRs. Example:

![image](https://user-images.githubusercontent.com/623494/62798839-3e5e8080-baad-11e9-83b1-6bc0687640c2.png)  

Thank you!

**Comment by tarsius** [comment]
Did you actually merge the merge-request as it lives on Gitlab's server or just some earlier version? Github automatically detects merges and I would be very surprised if Gitlab didn't do the same.

Maybe the following happened? You checked out the merge-request branch, fixed a small typo, merged the feature branch into master and finally pushed master. Then you closed the mr manually.

If after fixing the typo you had *force* pushed the local representation of the merge-request branch to  its remote location, then Gitlab would have noticed that causing it to automatically close the merge-request *as merged*.

Maybe you were unable to push to the merge-request branch? Not sure when that is impossible on Gitlab, but on Github the maintainer can push to the contributor's branch on the contributor's fork, unless the contributor has explicitly disallowed that.

**Comment by jkdufair** [comment]
Not sure what I did, exactly, but I'll do some investigation and see if forge is working as intended. Thank you for the quick reply.

**Comment by jkdufair** [comment]
Thanks @tarsius. I must have been overthinking it. In a test repo, when I pushed the merged master branch, Gitlab did indeed detect the merge and closed the MR as merged. I did not need to force push the feature branch at all.
