### ISSUE TITLE
Access PR URL after creation

### ISSUE THREAD

**Issue by glasser** [magit/forge#182]
One thing I liked about magit-gh-pulls was that after I created a PR, it copied (killed) the URL to the PR. This was helpful since I often wanted to go to the URL in a browser or send it to a colleague immediately. Is there a hook somewhere on forge-create-pullreq that would let me implement this?

**Comment by tarsius** [comment]
Are you aware that you can visit a topic in a browser using `C-c C-w` while point is on the topic? Of course you have to wait for the topic to be shown in the status buffer before you can do that.

There is no suitable hook but you could use an advice. Another problem is that you cannot know the URL of the topic with absolute certainty until the API response that tells you what number was assigned. Other topics may have been created since you last fetched topics.

**Comment by glasser** [comment]
Agreed that the URL is needed from the response.

I have been using Forge only for creating PRs, not for browsing them. My work project is pretty active and I stay up to date on issues/PRs via a variety of mechanisms (some of which are on my phone where Forge isn't an option), including just "seeing that there's a long thread about a PR I don't care about in my email inbox and moving on to the next thread". So trying to keep up to date with comment read status isn't going to happen and I removed the pull request and issues lists from my magit buffer.

Would it be reasonable to add some sort of post-create-pullreq hook that receives the newly created pullreq's URL?

**Comment by tarsius** [comment]
I've added such a hook, called `forge-post-submit-callback-hook`. It's called whenever a new pull-request/issue/post is created or an existing one is edited. It's called with the same arguments as all ghub callbacks, see `ghub-request`'s doc-string. You can use it like so:

```emacs-lisp
(defun my-forge-post-submit-callback-kill-url (value _headers _status req)
  (when t ; TODO something kinda like (sic-p (url-recreate-url (ghub--req-url req)))
    (when-let ((url (alist-get 'url value)))
      (kill-new url))))

(remove-hook 'forge-post-submit-callback-hook
             'my-forge-post-submit-callback-kill-url)
```

You might want to improve that by detecting what kind of request we just made and then behaving differently depending on that. The request url would be useful for that but currently it is always "/" by the time we get here. I know why that is so and it probably should be considered a bug. But I'll have to think about it a bit more--don't want to break anything by fixing it.

**Comment by rolandtritsch** [comment]
`(alist-get 'url value)` will give you `https://api.github.com/repos/<org>/<repo>/pulls/<id>`.

Probably not what you want.

Using `'html_url` makes this work as intented.

```
(defun my-forge-post-submit-callback-kill-url (value _headers _status _req)
  (when t
    (when-let ((url (alist-get 'html_url value)))
      (kill-new url))))

(add-hook 'forge-post-submit-callback-hook 'my-forge-post-submit-callback-kill-url)
```
