### ISSUE TITLE
Topic template selection seems unavoidable

### ISSUE THREAD

**Issue by kimjetwav** [magit/forge#184]
It seems to be the case (since I cannot find it documented, as well as from a cursory glance at the forge-topic.el) that if topic templates exist, the user is prompted to select one, however the user _cannot_ choose to select no template in order to access the default blank topic creation buffer.

Specifically, selecting no template from the list escapes topic creation altogether, apparently forcing the use of templates if any exist for topic creation.

Is this intended, or am I misunderstanding how to escape template usage without escaping topic creation?

**Comment by tarsius** [comment]
> Is this intended, or am I misunderstanding how to escape template usage without escaping topic creation?

Yes. I think it is nice if the user reads the most appropriate instructions even if none fits the topic they are about to create perfectly. If the instructions are completely unsuitable, then the user can easily discard them using `erase-buffer`.

Maybe I will change my mind about this eventually, but for now I think it is a good thing to not make it even easier to ignore the maintainers instructions.

**Comment by kimjetwav** [comment]
Fair enough! Thanks for the reply!
