### ISSUE TITLE
Avoid inserting dashes in pull requests when no template exists

### ISSUE THREAD

**Issue by r-darwish** [magit/forge#185]
When I make a pull request for a repository which has no pull request template the post buffer shows:

```markdown
# Add binding for k8s


----

# 


```

I could not find any documentation regarding the dashes, so I looked at the code and found out that the second section should be a pull request template, if exists. I usually just delete the dashes and the second section. I think it's best not to insert this section if performing a pull request and no template exists.

**Comment by tarsius** [comment]
The code that is responsible for this is a mess. That's why I did not get around to fixing this yet; I don't know what I was thinking when I wrote that.

**Comment by aspiers** [comment]
IIUC this is the code in question:

https://github.com/magit/forge/blob/e14a49d8f2ede96d0da4f0a327449d0826a72e7a/lisp/forge-post.el#L149-L158

I don't understand the logic behind the `(if source ...` conditional, but I do note that removing the `(insert .text)` and the `(insert "\n----\n\n")` fixes it for me.

**Comment by aspiers** [comment]
Having said that, I didn't yet test that with a repo which has pull request templates.

**Comment by tarsius** [comment]
Finally fixed it.
