### ISSUE TITLE
UNIQUE constraint failed: repository.id

### ISSUE THREAD

**Issue by tarsius** [magit/forge#188]
The most likely cause for this is that a repository was renamed.

The id used in the local database is based on the id used by the forge on which the repository is located.  Among other things it was done that way to make it easier to deal with renamed repositories.  Unfortunately not everything that is required to make that a reality has been implemented yet and meanwhile it has the *opposite* effect.

(I know what the issue is, but could not yet decide how and especially where to fix it.)

Here's a work-around:

If you are aware which repository has been renamed recently, then

1. Remove it from the database using `M-x forge-remove-repository`.
2. Update the url `remote.REMOTE.url` in your local clone of the repository.
3. Fetch the forge data for the repository anew.

This has been brought up before in #10.

**Comment by reverland** [comment]
Yeah, I've just renamed a private gitlab repo, and the error occurred.

The workaround works well

**Comment by raxod502** [comment]
In my case, I was able to identify the repository which needed to be deleted just by looking at the `*Backtrace*` buffer, since it appeared as an argument to one of the functions called there.
