### ISSUE TITLE
gitlab wrong api url when `-` in the group name

### ISSUE THREAD

**Issue by yisraeldov** [magit/forge#190]
When there is a dash `-` in the group name of a gitlab repo, the API url does not get made correctly.

for some reason the `/` is getting escaped. 

I don't have this problem on other repos.

Thanks!

```
ghub--signal-error: HTTP Error: 404, "Not found", "/api/v4/projects/group-a%2Fproject", ((message . "404 Project Not Found"))

```

Is there possible a way to manually set the API url manually as a work around..

**Comment by tarsius** [comment]
It would be helpful to know when that happens. What do you do to trigger it? Could I get a backtrace with this?

`glab-repository-id` quotes `/`, so doing the same for `-` might do the trick, but only if this is actually where the error happens.

**Comment by tarsius** [comment]
I have located the documentation that explains that `/` quoted: https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding.

It does not mention that the same is the case for `-`, which I expect it would if it were.

**Comment by yisraeldov** [comment]
Thanks,  but the problem is that the slash is quoted when it shouldn't be.
The dash is OK,  it should not be quoted.

It happens when I first try to pull from the repo issues.  It works great
with other projects.  G-d willing I'll send you the back trace when I get
back to the office.

**Comment by tarsius** [comment]
Why do you thing the `-` is relevant at all? My guess is that something completely unrelated is wrong with that repository.

> problem is that the slash is quoted when it shouldn't be.

Why do you think that? That's not what the documentation says.

I tried to reproduce using https://gitlab.com/test-xyz/aproject, which I created just for this purpose, but everything worked as it should.

**Comment by yisraeldov** [comment]
I thought those things because I am a moron! It was nothing to do with that at all.
The problem is that they are private repos, my public doesn't give the same error, but has a different issue, seems to be related to authentication. I'm going to try and track down exactly what happened and I'll check back in.
