### ISSUE TITLE
pulling notifications very slow again, even in small repos

### ISSUE THREAD

**Issue by titaniumbones** [magit/forge#191]
when I run `M-x forge-pull`  from a magit-status buffer in a repo with a Github remote, or file an issue in such a repo,  pulling notifications takes a very long time (generally more than a minute, though I've only timed it a couple of times). During this time, emacs is unresponsive.  

What strategy should I take to try to figure out what's taking so long?  At present the only messages are as follows:
```
Pulling notifications...
Pulling notifications (page 1/4)...
Pulling notifications (page 2/4)...
Pulling notifications (page 3/4)...
Pulling notifications (page 4/4)...
````

**Comment by tarsius** [comment]
Fetching notifications is complicated by the fact that Github doesn't expose notifications using GraphQL, even though this would be an area where that would make more sense than in many other areas and GraphQL is used for all other areas (which I have tried using so far). :roll_eyes: 

As a result the code on the client-side has a "let's not spend to much time on it, I am sure they are going to see the light soon" kinda quality.

The relevant functions are `forge--pull-notifications` and `forge--ghub-massage-notification` in `forge-github.el`. It's callback hell.

**Comment by titaniumbones** [comment]
> The relevant functions are `forge--pull-notifications` and `forge--ghub-massage-notification` in `forge-github.el`. It's callback hell.

Scrambling around these couple of days but hoping to look into this when I can! Thanks @tarsius .

**Comment by titaniumbones** [comment]
I think when called interactively with `M-x forge-pull`, forge-pull is fetching notifications for all the repositories in my database.  I don'treally understand the common lisp forms, but with edebug running on `forge--pull-notifications` and a breakpoint on line. 316 in this part of the function:

```lisp
(notifs (-keep (lambda (data)
                          ;; Github may return notifications for repos
                          ;; the user no longer has access to.  Trying
                          ;; to retrieve information for such a repo
                          ;; leads to an error, which we suppress.  See #164.
                          (with-demoted-errors "forge--pull-notifications: %S"
                            (forge--ghub-massage-notification
                             data forge githost)))
                        (forge--ghub-get nil "/notifications"
                                         '((all . "true"))
                                         :host apihost :unpaginate t)))
```

, looking at `data` , it appears to loop through every repo I have.  Shouldn't it only pull the notifications specific to the repo?  In that case notifications I guess has to be replaced with `(format "/repos/%s/%s/notfications" owner reponame), though I don't know how to extract the owner and repo name from the repo object returned from closql.  

cf api docs here: https://developer.github.com/v3/activity/notifications/#list-your-notifications-in-a-repository

**Comment by titaniumbones** [comment]
I tried something hackish in titaniumbones/forge@8764690db09eb8f7fb8a41c2f6fb99e8d524fd64 

Will submit a PR if it looks like a good solution, but I suspect it's not up to par.

**Comment by tarsius** [comment]
I am aware that this fetches notifications for all repositories (or rather all notifications for any repository on the same Github instance the current repository comes from), and consider that a good thing. That way you are informed about repositories that need your attention without having to manually fetch each repository individually (including the ones you haven't even cloned locally yet).

I would rather find another way to make this faster than to make it less useful.

Until then I recommend you set the option `forge-pull-notifications` to `nil` and instead once in a while explicitly use the command by the same name.

**Comment by titaniumbones** [comment]
ah, ok. Hmm, I guess that's what I want to do.  I hadn't actually realized that notifications were being managed distinctly from issues and PRs, and only just now discovered `forge-list-notifications`... which is kind of amazing.  Thanks for clearing this up. Closing now, because `(setq forge-pull-notifications nil)` solves the problem
