### ISSUE TITLE
set milestone in issue

### ISSUE THREAD

**Issue by titaniumbones** [magit/forge#206]
I'm not sure, but I don't think it's currently possible to set a milestone from the issue view.  This seems like a useful feature, so just adding this issue here.

**Comment by tarsius** [comment]
I've added support for that last week.

**Comment by base698** [comment]
@tarsius C-c C-e doesn't autocomplete available milestones.  Using Gitlab 13.7.  Is there a way to pull them?  Tickets with Milestones show as `^A`.  Can create a bug if need be.

![Screenshot from 2021-02-08 11-31-59](https://user-images.githubusercontent.com/207514/107271610-56e08b80-6a01-11eb-90b3-16a7fcbd427a.png)

**Comment by tarsius** [comment]
Yes please open a new issue and also check whether you have the same issue on Github.
