### ISSUE TITLE
`forge-browse-commit` freezes for seconds with many branches

### ISSUE THREAD

**Issue by lionel-** [magit/forge#207]
Hello,

I'm working with a Github repository (https://github.com/wch/r-source) that has 264 branches.

```lisp
(length (magit-list-remote-branch-names "upstream"))
> 264
```

`forge-browse-commit` is stuck for several seconds in this loop: https://github.com/magit/forge/blob/247dbb85ceae77625d04a71ea36622aa583f7873/lisp/forge-commands.el#L183

**Comment by tarsius** [comment]
Check whether `git branch --contains THE-COMMIT` is sufficiently faster.

**Comment by lionel-** [comment]
Is this a note to yourself or would you like me to check?

**Comment by tarsius** [comment]
I would like you to check. :stuck_out_tongue_winking_eye:

**Comment by lionel-** [comment]
A single `git merge-base --is-ancestor` takes 0.13s on my system, so it sounds like replacing the `-any-p` loop with `git branch --contains` would solve the problem:

```sh
time git merge-base --is-ancestor 62a4c351ef upstream/2-9-branch                                                                                                                                      
#> git merge-base --is-ancestor 62a4c351ef upstream/2-9-branch  0.13s user 0.01s system 97% cpu 0.150 total
```

```sh
time git branch --contains 62a4c351ef
#> * trunk
#> git branch --contains 62a4c351ef  0.02s user 0.02s system 98% cpu 0.041 total
```

**Comment by tarsius** [comment]
You'll need to also update magit.

**Comment by lionel-** [comment]
Thanks!
