### ISSUE TITLE
forge-create-pullreq writes to .git/magit/posts/new-pullreq but no Pull request created

### ISSUE THREAD

**Issue by rezmuh** [magit/forge#208]
Hi, I am trying to setup magit forge so that I can create a pull request from emacs. I have setup authinfo manually and can see list of pull requests and issues from magit window. However, I can't seem to get pull requests working.

When I run M-x forge-create-pullreq, I am asked with the source branch and the target branch. Once I am done with the mesage, the status says that it has saved it to . .git/magit/posts/new-pullreq file.

This is the content of the file:

```
# update information
Test pull request

----

#
```

However, I don't see this pull request is created on GitHub though. It doesn't even look like it's trying to connect to GitHub to create the PR. It feels like I was missing one step.

What did I miss?

Thanks.

**Comment by tarsius** [comment]
> What did I miss?

Did you press <kbd>C-c C-c</kbd>? (Like when being done writing a commit message.)

**Comment by rezmuh** [comment]
Ahh, that works. I am actually using doom-emacs (with evil-magit). I thought just by save and quitting the pull request editor (:wq) would create the pull-request but it didn't. So i had to press `C-c C-c`. Is there a way I could map it to just save and quitting the pull request editor with evil-mode?

**Comment by tarsius** [comment]
Does it work like that when writing a commit message? If so, then it should be possible to do the same when writing a pull-request message and the `evil-magit` package would probably be a good place to do it.

**Comment by justbur** [comment]
@tarsius `:wq` is triggering the commit in evil-mode due to [these lines in with-editor](https://github.com/magit/with-editor/blob/d5c777298cd8f62fef701fb45684c626d384bf76/with-editor.el#L411). Do you think this should be done in evil-magit, or in forge like it's being done in with-editor?

**Comment by tarsius** [comment]
``` emacs-lisp
(defvar forge-post-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-c")                      'forge-post-submit)
    (define-key map [remap evil-save-and-close]          'forge-post-submit)
    (define-key map [remap evil-save-modified-and-close] 'forge-post-submit)
    (define-key map (kbd "C-c C-k")                      'forge-post-cancel)
    (define-key map [remap kill-buffer]                  'forge-post-cancel)
    (define-key map [remap ido-kill-buffer]              'forge-post-cancel)
    (define-key map [remap iswitchb-kill-buffer]         'forge-post-cancel)
    (define-key map [remap evil-quit]                    'forge-post-cancel)
    map))

```

Like this?  That is fine by me.  Did you test it?

**Comment by justbur** [comment]
@tarsius That appears to work for me. Thanks
