### ISSUE TITLE
ability to fork remote

### ISSUE THREAD

**Issue by Silex** [magit/forge#215]
Hello,

It'd be nice if after `github-clone` I could make a fork of the repo to my github user which would automagically add the username remote and set pushdefault there, like https://github.com/dgtized/github-clone.el/blob/master/github-clone.el#L138 does (unfortunately I don't want to use that anymore since forge works much better for everything else).

If you think it's not too complicated I can maybe help with a PR.

**Comment by tarsius** [comment]
> If you think it's not too complicated I can maybe help with a PR.

It's probably not too complicated and could always be improved. Yet I was planning to do it for a long time and never got around to it, so it would help if you could implement it.

**Comment by Silex** [comment]
Alright, I'll see what I can do.

**Comment by Silex** [comment]
Hum, you can maybe clarify if `gh` is something I can use or if I'm only supposed to use `ghub`. I'm a bit lost in all these libraries :-)

From a quick look it looks like `gh` is kinda dead, and `ghub` should be enhanced to support creating forks which then can be used in forge.

**Comment by tarsius** [comment]
I created `ghub` because I considered `gh` a dead-end.

**Comment by Silex** [comment]
Alright, thanks for the info.

**Comment by tarsius** [comment]
You should know that the probability that I won't merge your implementation is much larger for this feature than it would be for other features. I minimal viable version shouldn't be hard (and more likely be merged) but one reason I have not implemented this myself yet is that I haven't decided *how* to do that. I don't want to commit to anything just because someone else got around to implement something.

**Comment by Silex** [comment]
Can you elaborate a little on what *beyond* means here? I mean, my use case is "oh I'd like to make a change to this repo" and being able to clone-fork in one go reduces friction.

**Comment by tarsius** [comment]
That's the thing, I don't know yet. But `magit-clone` is defined in its own 270 line library. I expect `forge-fork` will get more complex than that eventually. Also--how should it be integrated with `magit-clone`? Many things to think about.

**Comment by tarsius** [comment]
I'll need to do a lot of forking soon, so I'll work on a minimal viable version myself today.

**Comment by Silex** [comment]
> I'll need to do a lot of forking soon, so I'll work on a minimal viable version myself today.

Unfortunately I can't help before next week (going on small holidays tomorrow) :disappointed:

Will ping you when I'm back to see what I can do.

**Comment by tarsius** [comment]
No problem at all. I was actually a bit worried we would duplicate work.

**Comment by tarsius** [comment]
Okay I have added a very basic `forge-fork`. Only supports github.com for now.

**Comment by jdtsmith** [comment]
I can't figure how `forge-fork` works.  I need to set `forge-owned-accounts`, which I think I've accomplished.  But `forge-fork` always results in:

```
 HTTP Error: 422, "Unprocessable Entity (Added by DAV)", "/repos/blah/blah/forks", 
((message . "'jdtsmith' is the login for a user account. You must pass the login for an organization account.") 
(errors ((resource . "Fork") (code . "invalid") (field . "organization"))) 
(documentation_url . "https://developer.github.com/v3/repos/forks/#create-a-fork"))
```

**Comment by asymmetric** [comment]
I'm seeing the same as @jdtsmith.

Workflow:

- call `forge-fork`
- Fork to: "https://github.com/asymmetric/foo"
- Remote name: "myfork"

And then I get the error above.

**Comment by tarsius** [comment]
> I'm seeing the same as @jdtsmith.
> ...
> In the end though, forge said Github was taking too long to create the repo, and it failed.

This seems like a contradiction. Did you or did you not get the same error message as him?

----

> 'jdtsmith' is the login for a user account. You must pass the login for an organization account.

This is how the request that resulted in that error was made:

```
(cl-defmethod forge--fork-repository ((repo forge-github-repository) fork)
  (with-slots (owner name) repo
    (forge--ghub-post repo
                      (format "/repos/%s/%s/forks" owner name)
                      (and (not (equal fork (ghub--username (ghub--host nil))))
                           `((organization . ,fork))))
    (ghub-wait (format "/repos/%s/%s" fork name) nil :auth 'forge)))
```

The error is most likely due to `(ghub--username (ghub--host nil))` not returning `"jdtsmith"`. Can you make any other requests using `ghub`/ `forge`? I am guessing this would fail anyway but for most other requests you would get a more helpful error message.

**Comment by jdtsmith** [comment]
> (ghub--username (ghub--host nil))

This returned my full email address, which is apparently a valid login option and worked to e.g. fetch topics.  But for forking this doesn't work.  I altered `github.user` in my git config to make it my short username, let forge make a new `~/.authinfo` and now fork works perfectly.  Thanks!

**Comment by ibizaman** [comment]
It worked for me by answering like this, while magit state was open on a remote repository:
Fork to: `ibizaman` (my "organization")
Remote name: `elfeed`
That created this: https://github.com/ibizaman/elfeed
