### ISSUE TITLE
Remote 'git@github.com:/user/project' not recognized

### ISSUE THREAD

**Issue by lukego** [magit/forge#216]
Forge does not seem to recognize the "scp-like" git remote syntax `git@github.com:/user/project`. Git treats this syntax as equivalent to `ssh://git@github.com/user/project`.

Tested with forge 20191017 from nixpkgs.

**Comment by tarsius** [comment]
I doubt that because that's what I personally use.

**Comment by tarsius** [comment]
Ah, but you may have to end that with `.git`.

**Comment by tarsius** [comment]
Actually it's this typo that is causing issues:

```diff
-git@github.com:/user/project.git
+git@github.com:user/project.git
```

The `.git` is optional in Forge too, see `forge--url-regexp`.

**Comment by lukego** [comment]
Intersting!

That's not a typo though: that's straight out of a working repository. Git accepts that syntax.

**Comment by lukego** [comment]
Concrete example for clarity:

```shell
ubuntu@ip-172-31-47-207:~/git$ git clone git@github.com:/magit/forge
Cloning into 'forge'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 1759 (delta 66), reused 77 (delta 42), pack-reused 1654
Receiving objects: 100% (1759/1759), 434.60 KiB | 257.00 KiB/s, done.
Resolving deltas: 100% (1314/1314), done.

ubuntu@ip-172-31-47-207:~/git$ cd forge

ubuntu@ip-172-31-47-207:~/git/forge$ git remote -v
origin  git@github.com:/magit/forge (fetch)
origin  git@github.com:/magit/forge (push)
ubuntu@ip-172-31-47-207:~/git/forge$ git --version
git version 2.17.1
```

**Comment by tarsius** [comment]
Well I guess then I have to support it too. Going for a swim first.

**Comment by lukego** [comment]
I can send you a patch for this tomorrow if you like too.
