### ISSUE TITLE
Usage Question: List of files touched by PR

### ISSUE THREAD

**Issue by webframp** [magit/forge#217]
Hi 👋 

This might also just be a magit usage question so pardon my ignorance if so. With forge I frequently create new branches based of PRs, using `b y` and I'd like a `git log --stat` style view of just which files are touched by the commits from the PR.

Is there a good way to do this right now with forge?

**Comment by tarsius** [comment]
You could place the cursor on the pullreq (i.e. on a subsection of "Pull requests").
Then type `l - s o RET`. If you have already checked out the branch you can also use `l - s c`.

**Comment by webframp** [comment]
Thanks, that will work nicely for now. You can close this issue probably.

Some forges like Gitlab have a tree view of changed files like this:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/774378/68151322-7855ec00-ff0f-11e9-8f1b-961256bbbbb1.png">

which is sometimes convenient to use for navigation. Github has a "Jump to ..." feature:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/774378/68151593-0336e680-ff10-11e9-822e-30d3aa8cc8ac.png">

While these are convenient on the web views, I think it's just a matter of me figuring out how to navigate properly within magit to jump to files with affected changes.

**Comment by tarsius** [comment]
Try `j` with the cursor on the diffstat line.
