### ISSUE TITLE
Troubleshoot failed pull request branches?

### ISSUE THREAD

**Issue by lukego** [magit/forge#218]
I've started using Forge today and I love it :)

I'm getting mixed results when I press `b Y` to create a local branch for a pull request though.

On some branches it works fine. On others it fails with `Git error: "branch 'abc' does not exist (in /user/dir)"`.

I'm not sure what the difference is. I am seeing both success and failure with branches having the same target and remote.

The `*magit-process*` log shows messages like
```
  0 git … remote set-branches --add eugeneia avf
  0 git … fetch eugeneia
From github.com:eugeneia/snabb
 * [new branch]          avf        -> eugeneia/avf

128 git … branch avf --set-upstream-to\=master
fatal: branch 'avf' does not exist

  0 git … remote set-branches --add eugeneia avf
  0 git … fetch eugeneia
128 git … branch avf --set-upstream-to\=master
fatal: branch 'avf' does not exist

Any troubleshooting tips?

**Comment by tarsius** [comment]
> Any troubleshooting tips?

Add debug statements to `forge--branch-pullreq`.
