### ISSUE TITLE
Not yet installable using only Melpa Stable 

### ISSUE THREAD

**Issue by fommil** [magit/forge#22]
```~ ag "magit-insert-section-body" .emacs.d
.emacs.d/elpa/forge-0.1.0/forge-issue.el
155:      (magit-insert-section-body

.emacs.d/elpa/forge-0.1.0/forge-pullreq.el
216:      (magit-insert-section-body
240:        (magit-insert-section-body
```

but `magit-insert-section-body` is not defined in `magit-2.90.1`

**Comment by fommil** [comment]
Looks like this commit needs to be in a stable release for it to work https://github.com/magit/magit/commit/39f8d03026e193ef7cef0d7e305bbc93d810d385

Workaround is to pin magit to melpa (not melpa-stable) for a little while :slightly_smiling_face:

**Comment by tarsius** [comment]
`forge` also depends on the wrong `ghub` right now.

> Workaround is to pin magit to melpa (not melpa-stable) for a little while

Yep, unfortunately that's necessary right now.  I was gonna create a new `forge` release today in order to depend on `ghub-3.1.0`, but since a new `magit` release would also be required I'll probably have to delay that after Christmas.

**Comment by enaeher** [comment]
I am using the melpa (not stable) version of magit (20181226.908) and I also see this problem. (Specifically, I get: `error in process sentinel: Invalid function: magit-insert-section-body`).

**Comment by jellelicht** [comment]
Are there any blockers for this to happen? It would be nice to be able to package a stable version of forge-and-friends

**Comment by tarsius** [comment]
The release of Transient was. And dealing with the fallout from that release still is.

**Comment by tarsius** [comment]
But I was planning to spend some time on the changelog today, which you can take as an indicator that I would rather do this sooner than later.

There's also an issue that is more relevant to Forge itself that I would like to address first: https://github.com/magit/ghub/issues/81. And maybe even https://github.com/magit/ghub/issues/83. So maybe this will still take a while. But at least now that Transient is out I have more time to tackle other things again.

**Comment by jellelicht** [comment]
What would prevent a semi-recent snapshot of master from being released as `0.2.0`?

**Comment by tarsius** [comment]
It would depend on a semi-recent `magit` shapshot, which hasn't been released yet and which in turn would depend on a semi-recent `transient` shapshot, which hasn't been released yet.

**Comment by hh** [comment]
Wondering how the transient->magit->forge release flow is going.

Is there a working config I could take a look at that ties the current dependencies together?

**Comment by unhammer** [comment]
https://stable.melpa.org/#/forge should this issue be closed now?

**Comment by tarsius** [comment]
Yep :grinning:
