### ISSUE TITLE
editing reviewers on pull request page asks for pull request

### ISSUE THREAD

**Issue by MartinNowak** [magit/forge#221]
Editing the reviewer list (<kbd>C-c C-e</kbd> forge-edit-topic-review-requests) on a pull request page interactively prompts `Request review for:`.
This is slightly confusing as editing is started from the PR's page.
It also behaves different from editing the topic's assignee, which correctly picks up the current PR as topic.

The different functionality between [`forge-read-topic`](https://github.com/magit/forge/blob/ebe499ec47f87c0d2ed24ff4082c2b2a483e5fcd/lisp/forge-commands.el#L483) and [`forge-read-pullreq`](https://github.com/magit/forge/blob/ebe499ec47f87c0d2ed24ff4082c2b2a483e5fcd/lisp/forge-commands.el#L509) comes from the former using [forge-current-topic](https://github.com/magit/forge/blob/8acb25026bc4edf8e54be062a59fb22753382420/lisp/forge-post.el#L83) and the latter just using [forge-pullreq-at-point](https://github.com/magit/forge/blob/8a25693774b80c3917e44be09929c04f61fe2b6e/lisp/forge-pullreq.el#L205) as defaults.
Implementing a forge-current-pullreq seems like the cleanest approach to fix the difference.
Any suggestions where and how to implement this properly?

**Comment by tarsius** [comment]
> Any suggestions where and how to implement this properly?

Place each (`issue` and `pullreq`) `current` function right below the respective `at-point` function. Adjust the respective `read` functions to use the `current` function as you suggested, but that also involves looking at all existing callers of the `read` functions to determine whether doing so is appropriate in all cases.

**Comment by tarsius** [comment]
I have done that now.
