### ISSUE TITLE
Label editing doesn't have an effect

### ISSUE THREAD

**Issue by acwatkins** [magit/forge#222]
When editing a label for gitlab there are no existing labels in the minibuffer. After adding a label, the labels aren't updated in the issue either in the detailed view or the main issue view. They are also not updated on gitlab itself. The edited label is in the minibuffer if you edit again, however.

**Comment by tarsius** [comment]
I cannot reproduce any of these issues.

**Comment by acwatkins** [comment]
Hmm, I'm running emacs 26.3

I tried to get you a log or something and while looking at it, I happened to have a merge request with the same number as an Issue I was editing. It applied the label to the merge request, not the issue (when editing the issue's labels) Another error now makes sense as when I try to mark an issue closed it gives an error that merged pull requests cannot be opened...

**Comment by tarsius** [comment]
That was an important little detail.

Thanks!
