### ISSUE TITLE
Tell markdown-mode how to handle relative paths to images

### ISSUE THREAD

**Issue by jmalmari** [magit/forge#223]
I'm visiting a gitlab issue that has messages. I can move through them with `magit-section-forward` and `magit-section-backward`. However, if I move past the last message section by using some other command (such as `magit-next-line` or `end-of-buffer`), the cursor gets stuck.

Trying to go forward, I see in Messages buffer:
> user-error: No next section

which is reasonable. Trying to go backward, I get
> funcall-interactively: Wrong type argument: number-or-marker-p, nil

or 

> magit-previous-line: Wrong type argument: number-or-marker-p, nil

from which I can only recover by using non-magit movement commands.

forge 0.1.0 (v0.1.0-251-gae724649+1)
magit 2.90.1 (v2.90.1-810-g8c4e8ed74+1)
emacs 27.0.50

**Comment by jmalmari** [comment]
Oh, and there's also `forge-topic-refresh-buffer: Wrong type argument: char-or-string-p, nil` when opening the issue (`forge-visit-issue`).

**Comment by jmalmari** [comment]
I tested another repository (this one) and I don't see the issue. The other one is unencrypted gitlab. 

I understand the unencrypted part of that is not supported, as discussed in https://github.com/magit/forge/issues/9

Here's how I set up the unencrypted gitlab:

```
(defclass forge-gitlab-http-repository (forge-gitlab-repository)
	((issues-url-format         :initform "http://%h/%o/%n/issues")
	 (issue-url-format          :initform "http://%h/%o/%n/issues/%i")
	 (issue-post-url-format     :initform "http://%h/%o/%n/issues/%i#note_%I")
	 (pullreqs-url-format       :initform "http://%h/%o/%n/merge_requests")
	 (pullreq-url-format        :initform "http://%h/%o/%n/merge_requests/%i")
	 (pullreq-post-url-format   :initform "http://%h/%o/%n/merge_requests/%i#note_%I")
	 (commit-url-format         :initform "http://%h/%o/%n/commit/%r")
	 (branch-url-format         :initform "http://%h/%o/%n/commits/%r")
	 (remote-url-format         :initform "http://%h/%o/%n")
	 (create-issue-url-format   :initform "http://%h/%o/%n/issues/new")
	 (create-pullreq-url-format :initform "http://%h/%o/%n/merge_requests/new")
	 (pullreq-refspec :initform "+refs/merge-requests/*/head:refs/pullreqs/*")))
(add-to-list 'ghub-insecure-hosts "private.com/api/v4")
(add-to-list 'forge-alist '("private.com" "private.com/api/v4" "private.com" forge-gitlab-http-repository))
```

**Comment by jmalmari** [comment]
It seems that for some issues, in the unencrypted gitlab, there is no problem.

**Comment by tarsius** [comment]
Such errors being raised during navigation are normally due to the buffer contents being corrupted and that is the case because some other error occurred earlier while the buffer contents were being created. So turn on debugging earlier and report what error occurs while the buffer is being created.

**Comment by jmalmari** [comment]
The error comes from `markdown-display-inline-images`, in my case eventually trying to evaluate
```
(downcase (url-type (url-generic-parse-url "/images/image.png")))
```
It expects all image hyperlinks to be complete URLs. In GitLab, at least, they don't have to be. They can be relative to the web site URL: [GitLab markdown](https://about.gitlab.com/handbook/product/technical-writing/markdown-guide/#images)

**Comment by jmalmari** [comment]
I wonder how this should be solved. Markdown probably doesn't get context where the image originated and hence can't know how to resolve the relative path.

**Comment by jmalmari** [comment]
https://github.com/jrblevin/markdown-mode/issues/422

**Comment by tarsius** [comment]
Please point me to a repository and issue that I can use to observe this.

> The path can either be relative to the website, or a full URL for an external image. 

What's "the website"? `https://gitlab.com`?

Adding a new argument to `markdown-display-inline-images` to allow passing "the website" seems like a sensible approach.

**Comment by jmalmari** [comment]
> Please point me to a repository and issue that I can use to observe this.

You can use this: https://gitlab.com/jarno.malmari/md-test-project/issues/1

To some extent, you can also test this in github using this comment itself. Browser will find this image, but forge won't:
![emoji](/images/icons/emoji/unicode/1f334.png)

> > The path can either be relative to the website, or a full URL for an external image.
> 
> What's "the website"? `https://gitlab.com`?
> 

This may be tricky. For gitlab, the generic format seems to be something along the lines of http[s]://GITHOST/USER_OR_GROUP[/SUBGROUP1/SUBGROUP2/...20]/PROJECT

Markdown will handle the http when it's appended `markdown-remote-image-protocols`.

> Adding a new argument to `markdown-display-inline-images` to allow passing "the website" seems like a sensible approach.

Either that or using the `markdown-translate-filename-function`, depending on how https://github.com/jrblevin/markdown-mode/issues/422 proceeds.

**Comment by jmalmari** [comment]
It is now possible to use `markdown-translate-filename-function` for inline images as well.

For this to be enabled in Forge, I guess a sufficiently generic format for the URL needs to be figured out. For my purposes, where I don't have any subprojects and the server is https, I use:
```
(defun my-gitlab-file (file)
	(let ((reponame (magit-toplevel)))
	  (if reponame
		  (concat "https://gitlab.domain.org/mygroup/"
				  (file-name-base (directory-file-name reponame))
				  file)
		file)))
;; As a `markdown-translate-filename-function', it gets called like: 
(my-gitlab-file "/uploads/pic.png")
```
