### ISSUE TITLE
git+ssh URL?

### ISSUE THREAD

**Issue by antoine-levitt** [magit/forge#224]
I connect to my repo with git+ssh://git@github.com/username/project, but forge says it's not a forge URL. Am I doing something wrong?

**Comment by tarsius** [comment]
I've just added support for this (see the mentioned commit), but I recommend you spell this `ssh://git@github.com/username/project` or even `git@github.com:username/project`--that's all equivalent. But shorter.

**Comment by antoine-levitt** [comment]
Thanks! Yeah I had this spelling from the last time I was confused and google came up with that.
