### ISSUE TITLE
Gitlab: Support for setting "Delete source branch" when creating MR

### ISSUE THREAD

**Issue by webframp** [magit/forge#225]
Hi There, 

If it's already possible to do this then I missed it, just point me at the docs. I love the dispatch to create MRs from forge using `@ c p` but this is the only common setting I'm missing that makes me go to the Web UI during this workflow.

This value can be set on new MR when creating or an MR can be edited to set this value so the feature branch is automatically deleted after merging. In the gitlab api, this is means setting the   `force_remove_source_branch` bool to `true`.

Here is what a Gitlab MR api response looks like with it is enabled. 

```json
{
  "id": 59771,
  "iid": 119,
  "project_id": 2345,
  "title": ":bug: Fix missing secret values",
  "description": "A short bug fix to populate missing secret value from the appropriate backend secret store.",
  "state": "opened",
  "created_at": "2019-11-29T19:08:45.951Z",
  "updated_at": "2019-11-29T19:13:35.662Z",
  "merged_by": null,
  "merged_at": null,
  "closed_by": null,
  "closed_at": null,
  "target_branch": "master",
  "source_branch": "secret-datasource-fix",
  "user_notes_count": 1,
  "upvotes": 0,
  "downvotes": 0,
  "author": {
    "id": 13,
    "name": "Escriva, Sean",
    "username": "webframp",
    "state": "active",
    "avatar_url": "https://gitlab.selfhosted.url/uploads/-/system/user/avatar/13/avatar.png",
    "web_url": "https://gitlab.selfhost.url/webframp"
  },
  "assignee": {
    "id": 13,
    "name": "Escriva, Sean",
    "username": "webframp",
    "state": "active",
    "avatar_url": "https://gitlab.seflhosted.url/uploads/-/system/user/avatar/13/avatar.png",
    "web_url": "https://gitlab.selfhosted.url/webframp"
  },
  "source_project_id": 2345,
  "target_project_id": 2345,
  "labels": [],
  "work_in_progress": false,
  "milestone": null,
  "merge_when_pipeline_succeeds": false,
  "merge_status": "can_be_merged",
  "sha": "a93f07cacfdab7dc988230c951529f8ce3e34ae4",
  "merge_commit_sha": null,
  "discussion_locked": null,
  "should_remove_source_branch": null,
  "force_remove_source_branch": true,
  "reference": "!367",
  "web_url": "https://gitlab.selfhosted.url/Group/app-repo/merge_requests/367",
  "time_stats": {
    "time_estimate": 0,
    "total_time_spent": 0,
    "human_time_estimate": null,
    "human_total_time_spent": null
  },
  "squash": false
}
```

Ability to set `squash: true` might be a nice to have and is in the same area on the MR edit Web View but I use that less often.

**Comment by webframp** [comment]
A little further info, I believe it's also possible to set these flags as push options, for example with a command like:

```
git push -u origin `git symbolic-ref --short HEAD` -o merge_request.create -o merge_request.merge_when_pipeline_succeeds -o merge_request.remove_source_branch
```

The option names map directly to the request fields in the json api response example.

**Comment by tarsius** [comment]
And you can also enable this by default: Check `Enable "Delete source branch" option by default` under `Merge requests` in the settings.

I think that's the proper place to configure this. It makes more sense to me than to repeat this information for every new merge-request.

**Comment by AmandaCameron** [comment]
It's worth noting that at the moment, GitLab does not have a sensible default for this when not provided by the API call. I have [filed an issue against GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/231245) for this, so others may want to follow it for updates on this.
