### ISSUE TITLE
deleted branches are still appearing in forge?

### ISSUE THREAD

**Issue by adhamhf** [magit/forge#228]
I'm starting to use forge for creating PRs.  I have rebuilt my forge database and done a `M-x forge-pull`.  However, when I create a new PR using `' c p` I see branches I have deleted.

Is there a way to get rid of these deleted branches?  I'm using GitHub enterprise but I don't think that matters.

Thanks.

**Comment by Silex** [comment]
In magit, fetch & prune branches that are gone: `f -p u` (`u` might be `p` depending on your config). This should delete the remote branches. For the local branches that are still there, you have no choice but to delete them locally: `b x` etc.

**Comment by tarsius** [comment]
Additionally, if you enable `--prune` permanently in the fetch popup, then forge's fetch commands also respect that. See [Saving Values](https://magit.vc/manual/transient/Saving-Values.html#Saving-Values) for how to do that.
