### ISSUE TITLE
`tabulated-list--column-number: No column named #` when trying to list issues or pull requests

### ISSUE THREAD

**Issue by seandavi** [magit/forge#229]
I imagine that the error I noted in the title is a local problem, but I have been unsuccessful in tracking down where my problem is. The error occurs when I try to list issues or pull requests from magit. Listing repositories, on the other hand, works as expected.

**Comment by xorb0ss** [comment]
I'm also having the same issue

**Comment by tarsius** [comment]
Have you updated recently. I vaguely remember having such an issue a while ago and am not able to reproduce this now.

What command exactly are you using, which triggers this? Could I have a backtrace with this?

**Comment by xorb0ss** [comment]
I did a fresh reinstall of my emacs today. The commands affected are `forge-list-issues` and `forge-list-pullreqs`

Backtrace:
```
Debugger entered--Lisp error: (error "No column named #")
  signal(error ("No column named #"))
  error("No column named %s" "#")
  tabulated-list--column-number("#")
  tabulated-list--get-sorter()
  tabulated-list-print(t)
  tabulated-list-revert()
  run-hooks(display-line-numbers-mode-hook display-line-numbers-mode-on-hook)
  display-line-numbers-mode()
  display-line-numbers--turn-on()
  global-display-line-numbers-mode-enable-in-buffers()
  run-hooks(after-change-major-mode-hook)
  run-mode-hooks(forge-pullreq-list-mode-hook)
  forge-pullreq-list-mode()
  forge--list-topics("BASE64==" forge-pullreq-list-mode nil (("BASE64=" 97 "PR NAME") ... MORE HERE )
  forge-list-pullreqs("BASE64==")
  funcall-interactively(forge-list-pullreqs "BASE64==")
  call-interactively(forge-list-pullreqs record nil)
  command-execute(forge-list-pullreqs record)
  execute-extended-command(nil "forge-list-pullreqs" nil)
  funcall-interactively(execute-extended-command nil "forge-list-pullreqs" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by seandavi** [comment]
Thanks to you both for the followup. @xorb0ss, thanks for doing my homework.

**Comment by tarsius** [comment]
Check the value of `forge-topic-list-columns`. Is it a different value from what is set at the beginning of `forge-list.el`?

**Comment by xorb0ss** [comment]
While inside emacs, `describe-variable forge-topic-list-columns`:
```
forge-topic-list-columns is a variable defined in ‘forge-list.el’.
Its value is
(("#" 5 forge-topic-list-sort-by-number
  (:right-align t)
  number nil)
 ("Title" 35 t nil title nil))
```

My local `forge-list.el:34-37`:
```
(defvar forge-topic-list-columns
  '(("#" 5 forge-topic-list-sort-by-number (:right-align t) number nil)
    ("Title" 35 t nil title  nil)
    ))
```

**Comment by tarsius** [comment]
The backtrace is weird. Why would one of the hooks `display-line-numbers-mode-hook` or `display-line-numbers-mode-on-hook`? That doesn't make any sense. 

.... okay figured it out. See the commit message.
