### ISSUE TITLE
error in process filter:  forge--sanitize-string: Wrong type argument: arrayp, nil

### ISSUE THREAD

**Issue by oceyral** [magit/forge#23]
Hi,

When pulling (first F y) from a private Gitlab instance, I have the following error:
```
Pulling GROUP/PROJECT...
Pulling GROUP/PROJECT issues...done
Pulling GROUP/PROJECT pullreqs...done
Pulling GROUP/PROJECT...done
Storing GROUP/PROJECT...
error in process filter: forge--sanitize-string: Wrong type argument: arrayp, nil
error in process filter: Wrong type argument: arrayp, nil
```

Emacs version: 26.1
Magit version : 20181218.2039
forge version : 20181219.2130
ghub version : 20181211.1827

There is at least one (small with very low volume of PR/issues/etc) repository where it doesn't happen, but it happens on bigger ones.

**Comment by oceyral** [comment]
Not sure it's related to the issues.

One of the projects I'm having this error with doesn't have any issue (we use an external bug tracker). The other had issues at some point, but they are now deactivated.

Yet another project without issues works fine, however.

**Comment by ipa-mtb** [comment]
In my case i think the description of a MR was nil and therefore it crashed.
Redefining forge--sanitize-string to
```
(defun forge--sanitize-string (string)
  (when string
    (replace-regexp-in-string "\r\n" "\n" string t t)))
```
fixed it for me

**Comment by oceyral** [comment]
It does fix the issue for me too. :+1:
