### ISSUE TITLE
forge-pull-topic doesn't work for pull requests

### ISSUE THREAD

**Issue by lplewa** [magit/forge#237]
I'm not sure if it is a bug, But forge-pull pulls all topics (PR and issues) but forge-pull-topic works only for issues and doesn't accept PRs.

**Comment by tarsius** [comment]
I cannot reproduce that. Are you using the latest forge snapshot?

**Comment by lplewa** [comment]
I have 20191211.1610 from melpa 

let me try update

**Comment by tarsius** [comment]
Github or Gitlab?

**Comment by lplewa** [comment]
in repository https://github.com/pmem/pmdk/pulls

if i will fetch #4480 i got following error:
`error in process filter: peculiar error: ((type . "NOT_FOUND") (path "repository" "issue") (locations ((line . 7) (column . 5))) (message . "Could not resolve to an Issue with the number of 4480."))`

If I will fetch #4478 everything works correctly 

updated to 20200102.2204 still doesn't work 

also, I have set forge.repositiory to different origin name.
