### ISSUE TITLE
Infinite loop fetching gitlab issues when no issues exist

### ISSUE THREAD

**Issue by mgulick** [magit/forge#238]
Hi,
Trying magit forge on a local gitlab instance, the initial fetch gets stuck in a loop constantly querying the gitlab API for issues.  The project has no issues.  Creating a fake issue in the gitlab web UI fixed the problem.

I captured the traffic with Wireshark, and the request is `/api/v4/projects/GROUP/PROJECT/issues?per_page=100&order_by=updated_at&updated_after=`.  The response from the server is `HTTP/1.1 200 OK`, and the response content is simply an empty JSON array: `[]`.

Thanks,
Mike

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by mgulick** [comment]
Thanks for the fix!
