### ISSUE TITLE
ghub--signal-error: peculiar error: ((message . "Unexpected end of document"))

### ISSUE THREAD

**Issue by asos-stephanemaniaci** [magit/forge#24]
I can `' P` and list all pull-requests, but trying to fetch notifications (`' f`) yields this error. Can you advise how to provide more information?

**Comment by asos-stephanemaniaci** [comment]
if I open my `*Messages*` buffer I get 

```
Pulling asosteam/asos-web-product-listing-page...done
Storing asosteam/asos-web-product-listing-page...done
Pulling notifications...
ghub--signal-error: peculiar error: ((message . "Unexpected end of document"))
```

**Comment by ginabythebay** [comment]
I'm seeing something similar.  Emacs 26.1, on windows 7.  I see in #5, this can be tied to the version of ghub.  I'm using version 3.1.0.

The backtrace I am seeing is:

Debugger entered--Lisp error: (ghub-graphql-error ((message . "Unexpected end of document")))
  signal(ghub-graphql-error (((message . "Unexpected end of document"))))
  ghub--signal-error((ghub-graphql-error ((message . "Unexpected end of document"))))
  ghub--graphql-handle-response((:peer (:certificate (:version 3 :serial-number "04:30:d9:79:1f:fc:b5:20:ac:33:9f:a4:a7:3a:7b:76" :issuer "C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 High Assurance Server CA" :valid-from "2018-06-19" :valid-to "2019-07-10" :subject "C=US,ST=California,L=San Francisco,O=GitHub\\, Inc.,CN=*.github.com" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:4e:0a:00:36:1e:9d:51:52:3b:c2:f2:92:89:4f:6e:8b:56:22:15:e6" :certificate-id "sha1:5f:f1:60:31:09:04:3e:f2:90:d2:b0:8a:50:38:04:e8:37:9f:bc:76") :key-exchange "ECDHE-RSA" :protocol "TLS1.2" :cipher "AES-128-GCM" :mac "AEAD")) #s(ghub--graphql-req :url #s(url :type "https" :user nil :password nil :host "api.github.com" :portspec nil :filename "/graphql" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous t) :forge nil :silent nil :method "POST" :headers #f(compiled-function () #<bytecode 0x27fbce5>) :handler ghub--graphql-handle-response :unpaginate nil :noerror nil :reader nil :callback #f(compiled-function (data) #<bytecode 0x25ae4d1>) :errorback nil :value nil :extra nil :query (query) :variables nil :until nil :buffer #<killed buffer> :pages 1))
  apply(ghub--graphql-handle-response ((:peer (:certificate (:version 3 :serial-number "04:30:d9:79:1f:fc:b5:20:ac:33:9f:a4:a7:3a:7b:76" :issuer "C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 High Assurance Server CA" :valid-from "2018-06-19" :valid-to "2019-07-10" :subject "C=US,ST=California,L=San Francisco,O=GitHub\\, Inc.,CN=*.github.com" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:4e:0a:00:36:1e:9d:51:52:3b:c2:f2:92:89:4f:6e:8b:56:22:15:e6" :certificate-id "sha1:5f:f1:60:31:09:04:3e:f2:90:d2:b0:8a:50:38:04:e8:37:9f:bc:76") :key-exchange "ECDHE-RSA" :protocol "TLS1.2" :cipher "AES-128-GCM" :mac "AEAD")) #s(ghub--graphql-req :url #s(url :type "https" :user nil :password nil :host "api.github.com" :portspec nil :filename "/graphql" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous t) :forge nil :silent nil :method "POST" :headers #f(compiled-function () #<bytecode 0x27fbce5>) :handler ghub--graphql-handle-response :unpaginate nil :noerror nil :reader nil :callback #f(compiled-function (data) #<bytecode 0x25ae4d1>) :errorback nil :value nil :extra nil :query (query) :variables nil :until nil :buffer #<killed buffer> :pages 1)))
  url-http-activate-callback()
  url-http-chunked-encoding-after-change-function(1015 1112 97)
  url-http-wait-for-headers-change-function(1 1137 1136)
  url-http-generic-filter(#<process api.github.com> "HTTP/1.1 200 OK\015\nDate: Thu, 20 Dec 2018 18:11:59 GMT\015\nContent-Type: application/json; charset=utf-8\015\nTransfer-Encoding: chunked\015\nServer: GitHub.com\015\nStatus: 200 OK\015\nCache-Control: no-cache\015\nX-OAuth-Scopes: notifications, read:user, repo\015\nX-Accepted-OAuth-Scopes: repo\015\nX-GitHub-Media-Type: github.v4; format=json\015\nX-RateLimit-Limit: 5000\015\nX-RateLimit-Remaining: 4981\015\nX-RateLimit-Reset: 1545332228\015\nAccess-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type\015\nAccess-Control-Allow-Origin: *\015\nStrict-Transport-Security: max-age=31536000; includeSubdomains; preload\015\nX-Frame-Options: deny\015\nX-Content-Type-Options: nosniff\015\nX-XSS-Protection: 1; mode=block\015\nReferrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin\015\nContent-Security-Policy: default-src 'none'\015\nContent-Encoding: gzip\015\nVary: Accept-Encoding\015\nX-GitHub-Request-Id: C1A8:30A1:2869727:32D9E5C:5C1BDB6F\015\n\015\n55\015\n\037\213\010\0\0\0\0\0\0\003\253VJI,IT\262\312+\315\311\321QJ-*\312/*V\262\212\256V\312M-.NLOU\262R\n\315K\255(HM.IMQH\315KQ\310OSH\311O.\315M\315+Q\252\215\255\005\0\346$\217\206A\0\0\0\015\n0\015\n\015\n")

**Comment by tarsius** [comment]
Please check whether 6586fcca074d4d0da57b22fca4bb9e97938462ac fixes this issue.

**Comment by tarsius** [comment]
Until I hear otherwise, I am going to assume that it does.
