### ISSUE TITLE
Can't do a pull

### ISSUE THREAD

**Issue by qrilka** [magit/forge#240]
After setting up a token I just can't do a `forge-pull` described in https://magit.vc/manual/forge/Initial-Pull.html#Initial-Pull
`forge` just keeps me asking
```
Git variable `github.user' is unset.  Set to:
```
I give my username `qrilka` but after eating some CPU it asks me about that again.
Is it something expected or maybe there is some way to debug this?

**Comment by qrilka** [comment]
`forge` and `magit` are installed from melpa

**Comment by tarsius** [comment]
I'm afraid I don't know what is wrong. But just in case; if you have two-factor authentication enabled, then try doing the configuration manually.

**Comment by qrilka** [comment]
@tarsius any hint how to do that manually?

**Comment by tarsius** [comment]
A good place to get started is [Manually Creating and Storing a Token](https://magit.vc/manual/ghub/Manually-Creating-and-Storing-a-Token.html) from the `ghub` manual.

**Comment by qrilka** [comment]
Thank you

**Comment by qrilka** [comment]
@tarsius it appeared that the problem was in my `~/.config/git/config` as it was configured with home-manager it wasn't readable

**Comment by qrilka** [comment]
Thanks for your help
