### ISSUE TITLE
Gitlab forge-pull doesnt work

### ISSUE THREAD

**Issue by venkateshks** [magit/forge#242]
forge-pull on a gitlab repo bails with the following error
error in process filter: EmacSQL had an unhandled condition: "table issue has 22 columns but 23 values were supplied

**Comment by tarsius** [comment]
The quick and dirty fix would be to discard the database and to start over. Usually forge automatically updates the database schemata but it appears that failed here.

**Comment by gburnett1** [comment]
I've encountered a similar problem when I run `forge-pull` for the first time.

```
error in process filter: EmacSQL had an unhandled condition: "table pullreq has 33 columns but 34 values were supplied" [2 times]
```

Should I also discard the database?

**Comment by tarsius** [comment]
Well since there isn't anything in the database yet, it's definitely worth a try.

**Comment by gburnett1** [comment]
I'm afraid that I get the same result each time that I discard the database and try `forge-pull`.

**Comment by tarsius** [comment]
My guess is that you updated `forge` without restarting. Remove the database once more and restart Emacs. If it still does not work, then uninstall `forge`, restart Emacs, and then reinstall.

**Comment by venkateshks** [comment]
I have a fix. I will try to post the fix once I am in front of a desktop.

**Comment by iterati** [comment]
I've

- Uninstalled forge while inside of emacs
- Deleted the forge .database file in another terminal window
- Exited emacs
- Restarted emacs (use-package then installed forge)
- Opened magit
- `M-x forge-pull`

After all that I still am getting this error message.

**Comment by iterati** [comment]
I had this issue with forge 0.1.0 from MELPA Stable, but changing the source to MELPA worked.

**Comment by gburnett** [comment]
> I had this issue with forge 0.1.0 from MELPA Stable, but changing the source to MELPA worked.

Why would that make a difference?

Looks like there has only been one release so far.

**Comment by tarsius** [comment]
Unfortunately once cannot unpublish from Melpa.
Forge 0.1.0 is broken, please don't use it.

**Comment by etehtsea** [comment]
@tarsius what do you think about releasing current version from melpa as `0.2.0`. It could help newbie like me, because I considered melpa-stable as more rock-solid alternative to melpa.

Thanks!

**Comment by tarsius** [comment]
> what do you think about releasing current version from melpa as `0.2.0`.

That's not possible before making a new magit release as well and that is not ready yet.

> I considered melpa-stable as more rock-solid alternative to melpa.

You are being mislead by the name of the archive, it is in no way more stable than regular melpa. All of the melpa maintainers use regular melpa and strongly suggest that users do the same. Search melpa's issue tracker and/or r/emacs for more information.
