### ISSUE TITLE
forge-fork is not working with custom github instance

### ISSUE THREAD

**Issue by pkryger** [magit/forge#246]
## The Issue
I use a setup with a custom enterprise github instace. The instance is available from the internal network at `https://entgithub.enterprise.com`. Note the host name: `entgithub` matches regex: `github`. I set up `forge` to point to this instance with:

``` emacs-lisp
(add-to-list 'forge-alist
             '("entgithub.enterprise.com"
               "entgithub.enterprise.com/api/v3"
               "entgithub.enterprise.com" forge-github-repository))
(setq forge-owned-accounts '(("mylogin" . (remote-name "mylogin"))))
```

This setup works for my most of my everyday needs: I can clone, submit a PRs or an issue.  However, as soon as I try to fork some repository to `mylogin` with `forge-fork`:
- a new fork appears in `entgithub.enterprise.com/mylogin`,
- adding a remote for it times out.

## Workaround I Use Now
I have poked around a bit and found that `forge-fork` calls `magit-clone--name-to-url` with just a name of a fork and a repository name. The latter function uses `magit-clone-name-alist` to guess the host and it matches `github.com`, as it is an optional for a match. Using that knowledge I:

``` emacs-lisp
(setq magit-clone-name-alist '(("\\`\\(?:entgitthub:\\|entgh:\\)?\\([^:]+\\)\\'" "entgitthub.enterprise.com" "github.entgitthub.enterprise.com.user")
                               ("\\`\\(?:github:\\|gh:\\)\\([^:]+\\)\\'" "github.com" "github.user")
                               ("\\`\\(?:gitlab:\\|gl:\\)\\([^:]+\\)\\'" "gitlab.com" "gitlab.user")))
```

So now, my `entgithub` is a default to match when adding a remote after creating a fork.

This solution, however, has a disadvantage that now all my forks try to add remote from `entgithub`.

### Alternative Workaround
I've also toyed with an idea to temporarily advise `magit-clone--name-to-url` so it gets the name of a actual forge to add remote for:

``` emacs-lisp
(setq magit-clone-name-alist
      '(("\\`\\(?:entgithub\\(?:.enterprise.com\\)?:\\|entgh:\\)?\\([^:]+\\)\\'" "entgithub.enterprise.com" "github.entgithub.enterprise.com.user")
        ("\\`\\(?:github\\(?:.com\\):\\|gh:\\)\\([^:]+\\)\\'" "github.com" "github.user")
        ("\\`\\(?:gitlab\\(?:.com\\):\\|gl:\\)\\([^:]+\\)\\'" "gitlab.com" "gitlab.user")))
(define-advice forge-fork (:around (fn &rest args) pk/forge-fork--magit-clone--name-to-url--with-repo)
  "Define temporary advice for `magit-clone--name-to-url' call."
  (interactive)
  (let ((repo (forge-get-repository 'stub))
        ret)
    (cl-flet ((pk/magit-clone--name-to-url--with-repo (args)
                                         (list (concat
                                                (oref repo githost) ":" (car args)))))
      (advice-add 'magit-clone--name-to-url :filter-args #'pk/magit-clone--name-to-url--with-repo)
      (setq ret (apply fn args))
      (advice-remove 'magit-clone--name-to-url #'pk/magit-clone--name-to-url--with-repo))
    ret))
```

This also seem to has the job done, yet it seems even more fragile, as it goes directly into implementation of `forge-fork` that may change one day.

## Proposed Solution
Given my experiences above, and limited knowledge of the `forge` and `magit` internals (I've only explored it for a few hours so far), I think one solution that could be considered is:
- concat the `githost` to the concatenation of the fork and repo name in `magit-clone--name-to-url` call,
- adjust default values of `magit-clone-name-alist` to include optional domain names.

I.e., the `forge-fork` could become (note the argument for `magit-clone--name-to-url` call):

``` emacs-lisp
(defun forge-fork (fork remote)
  "Fork the current repository to FORK and add it as a REMOTE.
If the fork already exists, then that isn't an error; the remote
is added anyway.  Currently this only support Github.com."
  (interactive
   (let ((fork (magit-completing-read "Fork to"
                                      (mapcar #'car forge-owned-accounts))))
     (list fork
           (read-string "Remote name: "
                        (or (plist-get (cdr (assoc fork forge-owned-accounts))
                                       'remote-name)
                            fork)))))
  (let ((repo (forge-get-repository 'stub)))
    (forge--fork-repository repo fork)
    (magit-remote-add remote
                      (magit-clone--name-to-url
                       (concat (oref repo githost) ":" fork "/" (oref repo name)))
                      (list "--fetch"))))

```

@tarsius, please let me know what you think. If you're happy with the above I can submit PRs for both `forge` and `magit`. I can also try to tinker with another direction if you have one in mind and can share it.

**Comment by pkryger** [comment]
I think the #248 sufficiently addresses the need to differentiate the `githost` when adding a remote after fork. However, the `(substring (oref repo githost) nil -4)` makes the regexp `magit-clone-name-alist` used to match the `githost` a bit awkward (i.e., no `.com` or any last four letters for that matter):

``` lisp
"\\`\\(?:entgithub\\(?:.enterprise\\)?:\\|entgh:\\)?\\([^:]+\\)\\'"
```

Leaving this open for now, to see if there's any other approach.

**Comment by tarsius** [comment]
It was a mistake to involve `magit-clone-name-alist` in this at all.
