### ISSUE TITLE
Support for GitHub pull request templates

### ISSUE THREAD

**Issue by aaronjensen** [magit/forge#25]
Hi there, thanks for releasing forge. It's exciting to see your take on "forge" management. One of the things I've used magithub for a lot is creating pull requests. It looks like forge supports that, but does not yet respect pull request templates:

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

It'd be great if it did as well. Thanks!

**Comment by tarsius** [comment]
Piuuuu!  Recovered.

**Comment by aaronjensen** [comment]
Awesome, thanks. Anything else in your reflog I may like? 😉

**Comment by claudio-dalicandro** [comment]
I don't understand, the issue has been closed, is there a PR in place? 🤔

**Comment by tarsius** [comment]
> is there a PR in place?

I don't remember whether I used a PR (probably not), but b122b584d8c85fae5cd1159efffa6b7d6d201d52 made it onto `master` a long time ago. This does not work if the template is defined user/organization wide int the `<name>/.github` repository, but I believe that extended feature was added to Github after I implemented support for the basic feature.
