### ISSUE TITLE
Q: How do I refresh the forge client so that deleted issues are removed locally

### ISSUE THREAD

**Issue by rileyrg** [magit/forge#252]
I deleted an issue on the github server but it wont go away on my client. I did a forge fetch all but the issue remains.

**Comment by tarsius** [comment]
The api does not answer the question "what topics have been deleted" so we would have to ask "this is a list of all issues, which one of those do not exist anymore". The latter would be very cumbersome and costly so we don't do it.

Duplicate of #163.

**Comment by rileyrg** [comment]
fair enough. Wonderful module. I just did a database reset - learning by
doing.

**Comment by tarsius** [comment]
There's also `forge-remove-topic-locally`.

**Comment by rileyrg** [comment]
Oh wonderful. I missed that.  Thank you.
