### ISSUE TITLE
Cannot use when github using authenticator app

### ISSUE THREAD

**Issue by togakangaroo** [magit/forge#255]
I try to use forge on my github projects. My account has 2fa set up using Authy.

I get asked for my username ✔️ 
I get asked for my password ✔️ 
I get asked for my authenticator code ✔️ 

Unfortunately then I get the following error

```
ghub--confirm-create-token: HTTP Error: 401, "Unauthorized", "/authorizations", ((message . "Must specify two-factor authentication OTP code.") (documentation_url . "https://developer.github.com/v3/auth#working-with-two-factor-authentication"))
```

Not sure what else would be useful to report. Happy to jump on a screenshare with someone at some point - would love to see how people debug emacs in real time.

**Comment by tarsius** [comment]
This is known not to work at the moment, see https://github.com/magit/ghub/issues/104.
