### ISSUE TITLE
forge-pull-topic unable to fetch single not-yet-fetched pull request

### ISSUE THREAD

**Issue by stepnem** [magit/forge#256]
The GitHub (and currently only) implementation of forge--pull-topic
distinguishes between issues and PRs using forge-get-pullreq, which
only works for PRs already in the database. It is thus impossible to
pull a single new PR.

Is it even necessary/practical to distinguish PRs and issues this way
(a priori)? They can't have the same #number anyway, can they?

**Comment by tarsius** [comment]
> which only works for PRs already in the database

What's the other side of the distinction here? PRs that are in the database? What about issues?; does it work for them?; even if not in the database yet?

> It is thus impossible to pull a single new PR.

Thus what? Please be more specific about what prevents that action.

> Is it even necessary/practical to distinguish PRs and issues this way (a priori)? They can't have the same #number anyway, can they?

Yes it is necessary because Git*lab* makes that distinction. There issues and prs do not share a numbering namespace. As a result Forge uses separate tables for issues and prs and that propagates up to here.

**Comment by stepnem** [comment]
>> which only works for PRs already in the database
>
> What's the other side of the distinction here? PRs that are in the
> database? What about issues?; does it work for them?; even if not in
> the database yet?

Yes, it works as expected for issues; the only problem apparently is
that for a PR, as I wrote, the request isn't even made due to the check.

>> It is thus impossible to pull a single new PR.
>
> Thus what? Please be more specific about what prevents that action.

I thought I did explain quite specifically? Just look at the
forge--pull-topic implementation: the pullreqp argument will never be
true for PRs not yet in the database, because of the forge-get-pullreq
check, so the number is just passed to ghub-fetch-issue in that case.
Which works for issues, but not PRs.

>> Is it even necessary/practical to distinguish PRs and issues this way
>> (a priori)? They can't have the same #number anyway, can they?

> Yes it is necessary because Git*lab* makes that distinction. 

Well, we are talking about the GitHub implementation here, though.
forge--pull-topic apparently hasn't been implemented for GitLab yet, and
even if it were, it could work differently.

> There issues and prs do not share a numbering namespace. As a result
> Forge uses separate tables for issues and prs and that propagates up
> to here.

Right. Well, my questions here were not rhetorical, I mean, if I thought
I knew how best to fix this, I would have sent a PR. :-D

Apparently what is needed is to somehow distinguish between
not-yet-pulled PRs and issues, i.e., instead of forge-get-pullreq, which
only works for local (fetched already) PRs, use something else which
will also work for remote (not fetched yet) PRs. And I don't know what
the best/most effective way to do that is. Or make a more generic
request which (for GitHub, at least) would work for both issues and PRs,
to avoid querying the API repeatedly? I don't know enough about the API
or ghub/forge to be making any concrete suggestions here.

**Comment by tarsius** [comment]
> the pullreqp argument will never be true for PRs not yet in the database, because of the forge-get-pullreq check,

That's the part that didn't just pop into my head. :wink: 

> Right. Well, my questions here were not rhetorical, I mean, if I thought
> I knew how best to fix this, I would have sent a PR. :-D

Nor were main. Anyway, the fix was quite simple but required changing `ghub` too.

**Comment by stepnem** [comment]
Great, thanks!
