### ISSUE TITLE
Can't find how to call level 7 functions

### ISSUE THREAD

**Issue by achempion** [magit/forge#260]
Right now we have many useful commands such as
```lisp
    (7 "l a" "awaiting review"     forge-list-requested-reviews)
    (7 "o i" "owned issues"        forge-list-owned-issues)
    (7 "o p" "owned pull-requests" forge-list-owned-pullreqs)
    (7 "o r" "owned repositories"  forge-list-owned-repositories)]
```

They described in manual (except `forge-list-requested-reviews`) bun unfortunately without any hint how to call them. It'll be great to have them visible by default to make more users aware of such functionality.

I can call them by `M-x <command>` but can't figure out what `7` means to enable bindings (`7` key doesn't work for me).

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>
