### ISSUE TITLE
Browse repo from transient menu

### ISSUE THREAD

**Issue by diasjorge** [magit/forge#265]
Hi, I use magithub and I usually like to open the github project from emacs.

This can currently be done by pressing `H H`.

Is there a way to extend the current transient command so I can add new commands when I press `'`?

I'd like to add a new section or command so I could go to the github repo by pressing `' b` or something like that.

I could leverage the `forge-browse-remote` function, but I don't know how to extend the menu.

Is it possible without patching forge itself? If not is this a feature you could accept and I can try to submit a PR?

**Comment by tarsius** [comment]
> Is there a way to extend the current transient command so I can add new commands when I press `'`?

This is documented in the Transient manual.

**Comment by diasjorge** [comment]
I struggled a bit with the manual, since there were no examples, but I found a couple results with the Github search for the functions and came up with this solution:

```
(transient-append-suffix 'forge-dispatch '(0 2) ["Browse" ("b" "repository" forge-browse-remote)])
```

Thanks
