### ISSUE TITLE
access api with project id

### ISSUE THREAD

**Issue by maggo007** [magit/forge#270]
I try to access my university gitlab with forge and it seems that it is configured to not work when trying the path `/api/v4/projects/username/projectname` as it returns 404 error. I can access the API when I use `/api/v4/projects/1234`where 1234 is the projectId. Is there a way to specify to use the id instead of username/projectname?

**Comment by tarsius** [comment]
With Gitlab `username/projectname` has to be written as `username%2Fprojectname`, which Forge already does. Maybe in some place it fails to do so--please provide more information about what request exactly fails.

**Comment by maggo007** [comment]
Forgot to mention it but I already tried both version. Only the one with %2F is working on offical gitlab.com and forge is pulling issues and everything correctly. When using my university gitlab forge returns the following.

```
ghub--signal-error: HTTP Error: 404, "Not found", "/api/v4/projects/username%2Fproject", ((message . "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/v4/projects/csat2062/dotconfig was not found on this server.</p>
</body></html>") (documentation_url . "https://github.com/magit/ghub/wiki/Github-Errors"))
```

In the browser I get the message
```
Not Found
The requested URL /api/v4/projects/username/project was not found on this server.
```
Even tho i entered the url with %2F. When entering the url without it %2F i get a reply in json format

`{"error":"404 Not Found"}`

All non forge magit related things work fine.

**Comment by tarsius** [comment]
I still don't know what you do, which then triggers that error. What command do you execute? Can you get a backtrace by `M-x toggle-debug-on-error` first?

**Comment by maggo007** [comment]
The error triggers when I add the repository with `M-x forge-add-repository` I am also pretty sure that my university didn't set up everything correctly so changing from `username/project` to `projectid` for the api call could solve my problems.

Also can i sent the backtrace to you directly if still needed? There is some personal information in there I am not to keen on sharing and removing or rewriting everything could mess up the log information you probably need.

**Comment by tarsius** [comment]
> Only the one with %2F is working on offical gitlab.com and forge is pulling issues and everything correctly. When using my university gitlab forge returns the following.

Based on that I am unsure if you are actually reporting two issues. Let us first look at the issue with gitlab.com as I would be able to reproduce that. Please provide the instructions on how to reproduce it.

> Also can i sent the backtrace to you directly if still needed? There is some personal information in there I am not to keen on sharing and removing or rewriting everything could mess up the log information you probably need.

Might be useful. Yes you can mail it to me personally.

**Comment by maggo007** [comment]
>Based on that I am unsure if you are actually reporting two issues. Let us first look at the issue with gitlab.com as I would be able to reproduce that. Please provide the instructions on how to reproduce it.

I don't have any problems when using gitlab.com only with my university set up version of gitlab. I'll send you an email with the backtrace and the project I try to access which should be visible to all.

**Comment by tarsius** [comment]
> I don't have any problems when using gitlab.com

I found this confusing:

> Only the one with %2F is working on offical gitlab.com

I thought you might mean:

> Only the one with `%2F` is working on offical gitlab.com, the one with `/` is not working, not even on official gitlab.com.

**Comment by maggo007** [comment]
Yes I worded that a bit wrong. I don't have any problems on official gitlab.com because forge already uses `%2F` which is not working for my university.

**Comment by tarsius** [comment]
Okay :grinning:

**Comment by doblak** [comment]
One possible reason for the university Gitlab issue is a reverse proxy in front of Gitlab rejecting %2F in the URL (it looks like the default Apache 404 response to me).

**Comment by tarsius** [comment]
That sounds plausible but obviously I have no way of verifying. So it seems like this is not an issue with `forge`/`ghub` or something I could do something about. Let me know if it turns out that I can actually do something about it.
