### ISSUE TITLE
[GitHub] Transferred issues are not removed from forge database

### ISSUE THREAD

**Issue by christopher-dG** [magit/forge#271]
On GitHub, if you create an issue, pull it with forge, transfer the issue to another repository, then pull again with forge, the issue remains visible. `magit-browse-thing` actually works because GH handles the redirect, but attempting to comment on the issue via forge results in a 404.

**Comment by tarsius** [comment]
Duplicate of #252 and #163.

**Comment by christopher-dG** [comment]
Thanks for pointing me to `forge-remove-topic-locally`, sorry for the noise.

**Comment by tarsius** [comment]
I've just added https://github.com/magit/forge/wiki/FAQ :stuck_out_tongue:
