### ISSUE TITLE
Create Pull Request fails "Failed to submit post"

### ISSUE THREAD

**Issue by julienchastang** [magit/forge#273]
Thanks for magit and forge.

I can't get `forge-create-pullreq` to work:

```
error in process filter: Failed to submit post: (error http 404 ((message . "Not Found") (documentation_url . "https://developer.github.com/v3/pulls/#create-a-pull-request"))) [2 times]
```

```
Magit 20200503.1905, Git 2.24.1, Emacs 26.3, darwin
```

`forge-pull` appears to work fine.

[Searching this project's issue history](https://github.com/magit/forge/issues?q=is%3Aissue+%22Failed+to+submit+post%22), I can see similar errors have appeared before, but I believe this error is unrelated to those previous issues.

 I am willing to try to get to the bottom of this, but my efforts with `edebug` did not yield any insights nor my attempts to obtain more verbose diagnostics. For starters, I would really like to see what POST request is actually being issued.

**Comment by tarsius** [comment]
> For starters, I would really like to see what POST request is actually being issued.

`(setq url-debug t)` should help with that.

**Comment by julienchastang** [comment]
I figured out the problem. I had not set the proper scope when defining the token:

![image](https://user-images.githubusercontent.com/229955/81088578-5d613600-8eb8-11ea-8813-1ae97b9886e7.png)

Could this be [more clearly documented somewhere](https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started)? I don't think there is any mention of scopes in the docs. I was also confused about the parent "repo" option that talks about private repos.

Also, the format of storing the token in `~/authinfo.gpg` [might be better explained in the docs](https://magit.vc/manual/ghub.html#How-Ghub-uses-Auth_002dSource), in particular that the password should really be the token and not the password.

```
machine api.github.com login username^forge password <token>
```

Thanks for these great projects. Just think about the amount of time you have saved developers around the world by streamlining people's workflows via emacs. :-)

**Comment by tarsius** [comment]
> Could this be more clearly documented somewhere?

Yeah, I am currently working on the documentation, and these are some useful hints.
