### ISSUE TITLE
gitlab.com pull-request fetching often gets stuck

### ISSUE THREAD

**Issue by kevin8t8** [magit/forge#275]
First, I have to preface this with an apology: I'm not well versed in Emacs Lisp or debugging it.  However, I've been using forge (and magit) happily for some time.

The past month or so, fetch / forge topics ('f' 'y') has started getting stuck on pull requests to my gitlab.com project extremely often.  It fetches issues first, and those never have a problem, but when it starts on the first pull request, it gets stuck.  I'll see error messages like:
```
error in process filter: apply: Wrong type argument: listp, 4
error in process filter: Wrong type argument: listp, 4
(the number 4 varies.  right now in my log I also see 18 and 47)

or:
error in process filter: Unrecognized keyword: "f" [2 times]
```

Sometimes, going into the emacs buffer list, and marking/killing all magit buffers will fix the issue for the next fetch.  But the next time I try after that, it gets stuck on pull requests again.

I have in my init.el:
``` elisp
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")

(use-package forge
  :ensure t
  :config
  ;; -5 turns off showing "closed" issues/prs by default
  ;; forge-toggle-closed-visibility will flip the sign and show up to 5 of them
  (setq forge-topic-list-limit '(60 . -5))

  ;; The heading format in tickets/pr.  Switching to %c to show absolute dates
  (setq forge-post-heading-format "%a %c\n")

  ;; 2020-04-16 I've started getting errors. :-(
  ;; https://github.com/magit/ghub/issues/81 suggests adding this
  (setq ghub-use-workaround-for-emacs-bug 'force))
```

I usually use Debian stable Emacs 26.1.  However I also have the problem in Arch Linux  Emacs 26.3.

I'll be happy try to produce any debugging output that might help, but may need explicit directions.

Thank you.

**Comment by kevin8t8** [comment]
I've been trying to investigate a bit, by adding debug `message` calls, and then setting `url-debug` to t.

Forge happily makes `url-retrieve` calls until it tries to retrieve the notes for the first pull request, but on that one it sits waiting for the callback.

Setting `url-debug`, it looks like url-retrieve never sees the "end of stream chunk".  Eventually it times out, but I'm not sure what gets sent to the callback then.

I tried setting `(setq url-http-attempt-keepalives nil)` and that seems to have "fixed" the issue.  At least now I see
```
http -> Saw end of stream chunk!
```
in the URL-DEBUG buffer for that request and everything finishes up right away.

Is there another workaround I could try?  Thank you.

**Comment by kevin8t8** [comment]
Since no one else has reported the problem, I think it would be okay to close this bug.

Either there is something with my setup, or perhaps an obscure Gitlab http bug.  In either case, I don't think this is Forge's problem.

For now I'm leaving `(setq url-http-attempt-keepalives nil)` but if I have more time in the future I'll try to investigate why the end-of-stream chunk doesn't appear sometimes.

**Comment by tarsius** [comment]
> I think it would be okay to close this bug.

Thanks :grinning:

> Either there is something with my setup, or perhaps an obscure Gitlab http bug. In either case, I don't think this is Forge's problem.

Most likely not. If it is in my code then probably in `ghub`, but IMO it is more likely a Gitlab issue or else a `url` issue. That beast isn't well groomed either. Ah well. Ehem, good luck!
