### ISSUE TITLE
Title: forge-fork fails

### ISSUE THREAD

**Issue by tvraman** [magit/forge#276]
Description:
Attempting to fork a repo using forge-fork gies this error:
HTTP Error: 422, "Unprocessable Entity (Added by DAV)",
"/repos/zorkow/speech-rule-engine/forks", ((message . "Validation
Failed") (errors ((resource . "Fork") (code . "invalid") (field
. "organization"))) (documentation_url
. "https://developer.github.com/v3/repos/forks/#create-a-fork"))
Description: It works!

Jonas, thanks for the helpful email, and apologies for the additional
spam where I asked about the secondary prompt with magit-fork.

I should have just followed your tip to hit enter twice :-)
I understand how things work now, I just forked another repo
successfully.

Final question, once a Pull-Request has been created in my fork,, how
do I send it to the upstream project from magit/fork --- everything on
the Web talks about clicking on the github  site, and searching in the
magit and forge info pages didn't find me the answer.

**Comment by tarsius** [comment]
For me it doesn't. Care to provide some more information?

Here are some issues that might be relevant: https://github.com/magit/forge/issues?q=is%3Aissue+Added+by+DAV. Please read through that information first.

**Comment by tvraman** [comment]
Jonas Bernoulli <notifications@github.com> writes:

Hi Jonas,

Will read through that info, heads-up, I find Github pages
hard/difficult to read using spoken output
(https://github.com/tvraman/emacspeak is what I use --- this is also why
I'm trying so hard to do everything from magit/forge vs clicking buttons
on the github website.

1. I have magit and forge installed from melpa, I tend to update things
every couple of days, and did an update this morning.

2. I was trying to fork https://github.com/zorkow/speech-rule-engine
3. I invoked M-x forge-fork
specified https://github.com/tvraman/speech-rule-engine and
https://github.com/zorkow/speech-rule-engine at the minibuffer (fork did
not exist previously)

I got the error I sent in the issue (copied it from the *Messages*
buffer.

I did manage to create the fork eventually using python command-line
tool gitman.

Hope this helps,

--raman 
> For me it doesn't. Care to provide some more information?
>
> Here are some issues that might be relevant:
> https://github.com/magit/forge/issues?q=is%3Aissue+Added+by+DAV.
> Please read through that information first.
>
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

--

**Comment by tarsius** [comment]
> 3. I invoked M-x forge-fork
> specified https://github.com/tvraman/speech-rule-engine

Ah, that's where things went wrong. You are not supposed to enter a url here but a key used in the variable forge-owned-account. I probably need to document that better and warn users about invalid input.

In your case you probably should just add this to your init file:
(setq forge-owned-accounts '(("tvraman")))

After that you can select "tvraman" at the prompt "Fork to". The second prompt is "Remote name" and the value chosen at the first prompt is used as initial input. Just confirm that.

All this is a bit overkill if you always fork to the same account and use the name of the account as the name of the git remote, but when often forking to different organizations, then this can be useful.

If you only ever clone to your user account, then just pressing RET on both prompts gets the job done, provided of course you have added
(setq forge-owned-accounts '(("tvraman")))
to the init file as I mentioned before.

**Comment by tvraman** [comment]
Jonas Bernoulli <notifications@github.com> writes:

Thanks for the tip! That explains it. I even looked through the source
code and saw the variable where you can specify one's account, but
dismissed it as irrelevant:-)>     3 I invoked M-x forge-fork
>       specified https://github.com/tvraman/speech-rule-engine
>
> Ah, that's where things went wrong. You are not supposed to enter a
> url here but a key used in the variable forge-owned-account. I
> probably need to document that better and warn users about invalid
> input.
>
> In your case you probably should just add this to your init file:
> (setq forge-owned-accounts '(("tvraman")))
>
> After that you can select "tvraman" at the prompt "Fork to". The
> second prompt is "Remote name" and the value chosen at the first
> prompt is used as initial input. Just confirm that.
>
> All this is a bit overkill if you always fork to the same account and
> use the name of the account as the name of the git remote, but when
> often forking to different organizations, then this can be useful.
>
> If you only ever clone to your user account, then just pressing RET on
> both prompts gets the job done, provided of course you have added
> (setq forge-owned-accounts '(("tvraman")))
> to the init file as I mentioned before.
>
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

--

**Comment by tvraman** [comment]
Jonas Bernoulli <notifications@github.com> writes:

P.S. Second prompt: would I under the full URL of the remote I'm
forking, or just "zorkow/speech-rule-engine" in my example?>     3 I invoked M-x forge-fork
>       specified https://github.com/tvraman/speech-rule-engine
>
> Ah, that's where things went wrong. You are not supposed to enter a
> url here but a key used in the variable forge-owned-account. I
> probably need to document that better and warn users about invalid
> input.
>
> In your case you probably should just add this to your init file:
> (setq forge-owned-accounts '(("tvraman")))
>
> After that you can select "tvraman" at the prompt "Fork to". The
> second prompt is "Remote name" and the value chosen at the first
> prompt is used as initial input. Just confirm that.
>
> All this is a bit overkill if you always fork to the same account and
> use the name of the account as the name of the git remote, but when
> often forking to different organizations, then this can be useful.
>
> If you only ever clone to your user account, then just pressing RET on
> both prompts gets the job done, provided of course you have added
> (setq forge-owned-accounts '(("tvraman")))
> to the init file as I mentioned before.
>
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

--

**Comment by tarsius** [comment]
Input at both prompts is just "tvraman". Depending on what completion framework you are using you might have to select "tvraman" as the first prompt even though it is the only choice. At the second prompt "tvraman" is the initial input, so it should always be possible to just confirm and be done with it.

By the way, it is not possible to change the *name* of fork. The name of the repository that is being forked is used. One reason for that is that Github doesn't allow setting the name at fork-time, so I didn't bother either.
