### ISSUE TITLE
Title: Doc Contribution: GitHub Fork, Pull-Request From Emacs

### ISSUE THREAD

**Issue by tvraman** [magit/forge#277]
Description
Hi Jonas,

Please include this in the forge online docs if you consider it
appropriate --- and thank you again for all your help as I navigated
this journey: https://emacspeak.blogspot.com/2020/05/github-standard-fork-and-pull-request.html

**Comment by tarsius** [comment]
Thanks for writing this up!

I am not sure yet where to add links to this tutorial but I will find some.

Cheers,
Jonas
