### ISSUE TITLE
Cannot determine forge repository (Github repository)

### ISSUE THREAD

**Issue by erwagasore** [magit/forge#280]
Cannot determine forge repository `git@er.github.com:erwagasore/.emacs.d.git` isn’t a forge url?

**Comment by tarsius** [comment]
```
git@er.github.com:erwagasore/.emacs.d.git
    ^^^ this doesn't seem right
```

**Comment by erwagasore** [comment]
You can configure git to use subdomain and associate each subdomain to a given SSH Key. Forge should allow such kinds of configurations aswell

**Comment by erwagasore** [comment]
[Here is the type of configuration that allows subdomain](https://stackoverflow.com/questions/3225862/multiple-github-accounts-ssh-config)

**Comment by tarsius** [comment]
[Forge needs to be configured accordingly as well.](https://github.com/magit/forge/wiki/Tips-and-Tricks#using-ssh-identities)
