### ISSUE TITLE
Format / Place for database

### ISSUE THREAD

**Issue by mgudemann** [magit/forge#282]
Hi, thanks a lot for forge, it's really great.

Could you please point me to the documentation where the contents of issues / PRs, i.e., the discussions are stored? My goal is to use forge to get a complete snapshot of a repository, including this data. Is this data accessible with vanilla git somehow?

**Comment by tarsius** [comment]
https://github-backup.branchable.com might be more suitable for that.

Forge uses a single database for all repositories but you can of course copy it somewhere else after importing only a single repository. The database is stored in `forge-database-file`. Forge does not fetch *all* the available data.

**Comment by mgudemann** [comment]
> https://github-backup.branchable.com might be more suitable for that.

unfortunately I need this for private repos which `github-backup` does not seem to support.

> The database is stored in `forge-database-file`. 

great, thanks! This is what I was looking for. A sqlite database is fine
