### ISSUE TITLE
forge-bug-reference-setup vs. Emacs 28 built-in setup

### ISSUE THREAD

**Issue by tsdh** [magit/forge#283]
I implemented some auto-setup for bug-reference-mode in the current Emacs master.  That will kick in only if `bug-reference-bug-regexp` and `bug-reference-url-format` haven't already been set after `bug-reference-mode-hook` has run.

That auto-setup is extensible, i.e., you can add your own rules.  So I added one for my workplace where we use a corporate Gitlab for code but JIRA for issues and wondered why it didn't work.  The reason is that `forge-bug-reference-setup` already ran in `bug-reference-mode-hook` and set the `bug-reference-url-format` wrongly (but it cannot know, of course).  Anyway, that suppresses the builtin bug-reference auto-setup which would do the right thing because I added a respective rule.

Well, the solution for me is to set `forge-bug-reference-hooks` to nil because the builtin setup achieves the same.  But as soon as Emacs 28 hits the masses (which is quite distant future), that issue will probably hit more users.  So I wanted to give you a heads-up.

- Announcement: https://lists.gnu.org/archive/html/emacs-devel/2020-06/msg00581.html
- Commit: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=5502eedf90d0da27df0c6c1fa33389d849d59a80

**Comment by tarsius** [comment]
> But as soon as Emacs 28 hits the masses (which is quite distant future), that issue will probably hit more users. So I wanted to give you a heads-up.

Thanks!

I forgot about this for a while. Even though I have seen it again now, I don't know when I will find the time to look into this.

**Comment by tsdh** [comment]
Hey Jonas, I've just found out by accident that forge also redefines `bug-reference-fontify` in order to inhibit fontification at BOL in magit status mode and forge notifications mode.  I guess that's because in the magit buffer you can have, e.g.:

```
Issues (65)
#2119 [mu4e bug] meson/ninja not installing mu4e-contacts.el and mu4e-search.el bug mu4e new
#2116 [mu bug] bug new mu
#2117 Saving Message to PDF with Attachment Names
...
```

But what's wrong with letting bug-reference highlight those bug numbers?  Then you'd also have the possibility to quickly browse the issue with the browser in addition to opening it in forge.

If it's just the too shiny face, you could do `(face-remap-add-relative 'link 'magit-dimmed)`.  But of course that would affect all links in the status buffer.

Anyhow, what I actually meant to say: please file an emacs bug report with what you need from bug-reference, e.g., maybe there could be a new variable `bug-reference-inhibit-fontification-functions` where you could add your check to, and/or bug-reference could define its own face (simply deriving from the `link` face) which would make the `face-remap-add-relative` think more viable.

I'd like to solve this all before emacs 28 goes into feature freeze.

**Comment by tarsius** [comment]
Right. Sorry for not having taken care of this yet. I'll try to do so and ping you when I need your help.

**Comment by tarsius** [comment]
Addressing the original issue was trivial. I should have done that a long time ago.

**Comment by tarsius** [comment]
> But what's wrong with letting bug-reference highlight those bug
> numbers?  Then you'd also have the possibility to quickly browse the
> issue with the browser in addition to opening it in forge.

> If it's just the too shiny face, you could do

The shiny face and that `RET` no longer does what it used to do at the beginning of the line. It's nice to be able to visit topics in magit *or* in a browser, but which it is should not be controlled by the location of the cursor in the line. On a topic section `RET` visits the topic in a separate buffer, while `C-c C-w` visits it using a browser.

Of course that does not affect bug-reference links in commit messages and such; those are always visited using a browser (I believe). It would be nice if something like `bug-reference-bug-visit-function` existed that forge could set; and a new alternative command on that always does what `C-c RET` currently does.

> Anyhow, what I actually meant to say: please file an emacs bug report with what you need from bug-reference,

The above would be nice for refs that appear in commit messages. But for complete topic sections under the control of `forge` I would prefer if things stayed under the control of `forge`.

So even if you implement the above I would still want to be able to tell `bug-reference-fontify` to ignore references that it finds at the beginning of a line in certain modes. I cannot think of a good name for that function right now, but it should be run by `bug-reference-fontify`, where my redefinition injects some code.

Is it really necessary that I open an emacs bug for this?

**Comment by tarsius** [comment]
> The shiny face and that `RET` no longer does what it used to do at the beginning of the line.

Err, it just sunk in that bug-reference actually uses `C-c RET`. But that doesn't really change anything; I don't think it makes sense for some key binding to be available on the ref-id part of the line but not in the rest of the line.

**Comment by tsdh** [comment]
@tarsius Couldn't you achieve the "don't highlight at BOL" behavior also by prepending `[^\n]` to `bug-reference-bug-regexp` in the buffers where you don't want highlighting and clickable links at BOL?

And bug-reference just calls `browse-url` so you might be able to add forge in `browse-url-default-handlers` so the bug-references are opened with forge.  debbugs.el does the same for the debbugs GNU instance.  (That's also new in emacs 28, I think.)

**Comment by tarsius** [comment]
> Couldn't you achieve the "don't highlight at BOL" behavior
> also by prepending `[^\n]` to `bug-reference-bug-regexp` in the
> buffers where you don't want highlighting and clickable links at BOL?

This works but causes that additional non-newline character to be highlighted as well. This could be addressed by only highlighting the first submatch, but that might cause backward compatibility issues.

But worse, to try this out I had to revert my previous change. If `forge` isn't allowed to set the regexp, then it also cannot control whether that regexp begins with `[^\n]`. I tried to let the new auto-setup set the regexp and the add `[^\n]` at its front like so:

``` emacs-lisp
(defun forge-bug-reference-setup ()
  (magit--with-safe-default-directory nil
    (when-let ((repo (forge-get-repository 'full)))
      (add-hook 'bug-reference-mode-hook
                (lambda ()
                  (setq bug-reference-bug-regexp
                        (concat "[^\n]" bug-reference-bug-regexp)))
                nil t)
      (if (derived-mode-p 'prog-mode)
          (bug-reference-prog-mode 1)
        (bug-reference-mode 1))
      (add-hook 'completion-at-point-functions
                'forge-topic-completion-at-point nil t))))
```

That does not work. The fontification happens before the regexp is modified.

**Comment by tarsius** [comment]
Well this would work:

``` emacs-lisp
(defun forge-bug-reference-setup ()
  (magit--with-safe-default-directory nil
    (when-let ((repo (forge-get-repository 'full)))
      (setq-local
       bug-reference-auto-setup-functions
       (let ((functions bug-reference-auto-setup-functions))
         (list (lambda ()
                 (catch 'setup
                   (dolist (f functions)
                     (when (funcall f)
                       (setq bug-reference-bug-regexp
                             (concat "[^\n]" bug-reference-bug-regexp))
                       (throw 'setup t))))))))
      (if (derived-mode-p 'prog-mode)
          (bug-reference-prog-mode 1)
        (bug-reference-mode 1))
      (add-hook 'completion-at-point-functions
                'forge-topic-completion-at-point nil t))))
```

By the way, why isn't `bug-reference--run-auto-setup` using `run-hook-with-args-until-success`?

**Comment by tsdh** [comment]
Creative approach.  I can't come up with something strictly better.

And yes, `run-hook-with-args-until-success` would be better.  I've changed that.
And I've also implemented the group-99-highlighting feature, so with the regexp `(concat "[^\n]\\(?99:" bug-reference-bug-regexp "\\)")` it should work now.

**Comment by tarsius** [comment]
@Thaodan I don't see how using a function could be used to address the raised issues. I've you have an idea, please show me.

(The original implementation used a function for gitlab, and for older emacsen I intend to keep that code path.)

**Comment by Thaodan** [comment]
If there is a function that uses a map of keywords -> URL 
those can be setup without conflicting between different 
bug trackers e..g those from forge or those from else 
like the JIRA of the reporter.

Functional those are the same in the end except that in 
emacs 28 this can sit on top of the emacs 
implementation.

**Comment by tsdh** [comment]
@Thaodan I can't follow.  The emacs 28 bug-reference auto-setup uses some functions looking at different things and some customizable alists figure things out.  For example, one function checks the version control URL of a file and an accompanying alist then defines that for github, the issues/PRs have to be resolved this way, for gitlab in that way, and for sr.ht in that other way.

What topic of this issue are you referring to?  The main thing was that emacs 28 has the auto-setup feature which forge implemented on its own so the forge-implementation is now inactive if emacs 28 is in use.

The second topic was that I suggested that forge shouldn't redefine a bug-reference function and here we also found a way to make that happen.

**Comment by runejuhl** [comment]
For users that get this error you can disable the use of forge in a repository with `M-x forge-remove-repository`.

**Comment by tsdh** [comment]
@runejuhl What error are you referring to?

**Comment by runejuhl** [comment]
Oh sorry, I guess that wasn't clear at all. With emacs `28.0.50` from Guix I get the following message and magit fails when running `magit-status` on a repository that has previously been configured to use forge:

~~~
run-hooks: Symbol’s value as variable is void: bug-reference-auto-setup-functions
~~~

Removing the offending repository from forge using `forge-remove-repository` makes magit work again, without forge of course.

**Comment by tsdh** [comment]
@runejuhl Ah, ok.  Well, that means that this emacs 28 snapshot is older than Sun May 16 09:21:48 2021, so really quite old.  But thanks for mentioning it here so others might find it if they get that error.
