### ISSUE TITLE
forge-create-pullreq doesn't have a sensible default?

### ISSUE THREAD

**Issue by benwainwright** [magit/forge#284]
Perhaps I'm missing a configuration setting; but when I run `forge-create-pullreq`, I'd expect it to create a pull request based on the currently checked out branch, but instead, I'm asked to specify the source and target. Am I missing something?

**Comment by tarsius** [comment]
> I'm asked to specify the source and target. Am I missing something?

It should provide *good* defaults, which you just have to confirm.

https://emacs.stackexchange.com/questions/46983/how-to-configure-git-and-magit-to-stream-line-making-pull-requests/47454#47454

**Comment by benwainwright** [comment]
@tarsius That isn't helpful at all. My options are:

* `pp pushRemote, setting that`. There is no default here, if I press enter I get a warning bell
* `pu ${upstream}, creating it`. This defaults to `origin/master`. That is not a "good default"; already today I've accidentally pushed commits from a branch directly into master on GitHub because of thist default.

**Comment by tarsius** [comment]
Many people find those very useful. If you don't then that is perfectly fine. There is documentation available on how to use something else. Please consult that documentation.

**Comment by benwainwright** [comment]
@tarsius I mean fair enough; but I really am interested to know what the use case for setting a branch upstream to master would be? Why would you possibly do that?

**Comment by benwainwright** [comment]
Is it not possible to make the default configurable?

**Comment by tarsius** [comment]
> I really am interested to know what the use case for setting a branch upstream to master would be?

The link above takes you to a question along with my answer, which in turn contains a link to a page about [the two remotes](https://magit.vc/manual/magit/The-Two-Remotes.html). That answers that question.
