### ISSUE TITLE
Wizard fails

### ISSUE THREAD

**Issue by franburstall** [magit/forge#286]
With a fresh install of `forge`, I open the local copy of a github repo, fire `magit` and hit `fy`.

What I expect: a wizard to fire up and help me get the api token.

What happens: I get the following error message:
````
ghub--token: Required Nil token ("franburstall^forge" for "api.github.com") does not exist.
See https://magit.vc/manual/ghub/Support-for-Other-Forges.html for instructions.
````
Emacs: GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-06-19
Magit: 20200706.1352
Forge: 20200705.1603

**Comment by tarsius** [comment]
> That I expect: a wizard to fire up and help me get the api token.

Yes, no. I am afraid I had to remove that.
See #113.

I have just updated the quoted error message to mention this.
