### ISSUE TITLE
forge-pull self-hosted GitLab instance issues

### ISSUE THREAD

**Issue by tru2dagame** [magit/forge#289]
Hi,
I am able to run `forge-pull` with my self-hosted GitLab instance with no errors. But it only add the `repository` to sqlite database.

![image](https://user-images.githubusercontent.com/1673006/88417093-ddda6780-ce13-11ea-9b77-3d04cd364c9a.png)

![image](https://user-images.githubusercontent.com/1673006/88417008-c3a08980-ce13-11ea-918c-45c928ebee5c.png)

The token and setup works with the GitLab api because I am able to create issues with forge. But can't see it in forge.

**Comment by tarsius** [comment]
And with gitlab.com and github.com it works as expected?

**Comment by tru2dagame** [comment]
Hi @tarsius, I haven't tried gitlab.com.
And yes, github.com and I also have a GitHub Enterprise instance, they do works as expected.

![image](https://user-images.githubusercontent.com/1673006/88450315-a6ee6b00-ce80-11ea-8cad-13d25f1309e6.png)


![image](https://user-images.githubusercontent.com/1673006/88450274-5c6cee80-ce80-11ea-89d1-d77a9f6877f4.png)

**Comment by tru2dagame** [comment]
@tarsius just tried gitlab.com. It doesn't work for me.

**Comment by tarsius** [comment]
I'm afraid I have no idea what might be wrong.

**Comment by tru2dagame** [comment]
Hi @tarsius As the GitLab api has already support graphql api, any chance we could upgrade the GitLab to use that?

**Comment by tarsius** [comment]
When did *that* happen?

**Comment by tru2dagame** [comment]
@tarsius 

> https://docs.gitlab.com/ee/api/graphql/

According to the docs, I think that start it from version 11.0 and always enabled in GitLab 12.1.

Now the latest version of GitLab is 13.3.

**Comment by tarsius** [comment]
Some more meta information:

- https://docs.gitlab.com/ee/development/fe_guide/graphql.html
- https://docs.gitlab.com/ee/api/README.html#road-to-graphql

> According to the docs, I think that start it from version 11.0 and always enabled in GitLab 12.1.

Yeah, stumbled into a sentence that implies that too. But so far no luck locating a release announcement that talks about it. Neither of these two release announcements do as far as I can tell. Ah well.

**Comment by tarsius** [comment]
So anyway... I probably won't work on it soon.

**Comment by tru2dagame** [comment]
Thanks. Got it.

By the way, do you have any suggest how I can debug my issue?

It seems no request is sent at all, so I got no error in the MESSAGE buffer.

**Comment by tarsius** [comment]
Nothing beyond "sprinkle on some debug statements until you have figured out where things start going wrong". :grin:

**Comment by tarsius** [comment]
Please check if 18f03a743739e30dbcdfcae663d03c3dd24278e6 fixes this.
