### ISSUE TITLE
Fetch PRs from upstream repository

### ISSUE THREAD

**Issue by ipa-mtb** [magit/forge#29]
When I have multiple remotes defined  `origin`  (my own fork) and `upstream` (the original repo) I can only fetch the PR's on my fork but not the ones of the upstream repo. 
`(oref repo remote)` always evaluates to `origin`.

**Comment by tarsius** [comment]
You can explicitly specify the remote to be considered the upstream.  From the manual:

> The convention is to name the upstream remote ~origin~.  If you follow
> this convention, then you have to do nothing else and the remote by
> that name is automatically used, provided it exists and regardless of
> whether other remotes exist.  If it does not exist, then no other
> remotes are tried.

> If you do not follow the naming convention, then you have to inform
> Forge about that by setting the Git variable ~forge.remote~ to the name
> that you instead use for upstream remotes.  If this variable is set,
> then Forge uses the remote by that name, if it exists, the same way
> it may have used ~origin~ if the the variable were undefined.  I.e. it
> does not fall through to try ~origin~ if no remote by your chosen name
> exists.

But I recommend following the convention instead.
