### ISSUE TITLE
Show commits for merged PRs

### ISSUE THREAD

**Issue by geza-herman** [magit/forge#297]
A minor usability feature: it seems that forge doesn't show commits for merged PRs. However, this would be a helpful feature to have. For example, when cherry picking an already merged PR to another branch. This can already be done in some other way of course (like getting a log of the PR's branch), but it would be the best if commit list were always available, not just for open PRs.

**Comment by tarsius** [comment]
Implemented in a3cf64de66b26d8b40e31227e968e7845ae55761.
