### ISSUE TITLE
Expose URL of issue, commit, or pull request at point

### ISSUE THREAD

**Issue by diamond-lizard** [magit/forge#307]
Quite often, when I'm commenting on an issue, I'll need to reference other issues, commits, or pull requests.

Currently, I have to switch out of magit/forge to get such links and switch back to it to insert the link.

It would be great if I could just stay in magit and get the URL of the issue, commit, or pull request at point.

**Comment by tarsius** [comment]
So now you can just insert a "#" and then while point is right after that invoke `complete-symbol'.

Following the link currently takes you to a webpage, but I am already working on that.

**Comment by diamond-lizard** [comment]
> So now you can just insert a "#" and then while point is right after that invoke `complete-symbol'.

I'm sorry, but I don't understand.  Let's say I'm looking at a list of issues, commits, or pull requests in a magit status buffer, and I want to get the URL to one of the issues at point.

Where am I inserting a #?

**Comment by tarsius** [comment]
> I'm sorry, but I don't understand. Let's say I'm looking at a list of issues, commits, or pull requests in a magit status buffer, and I want to get the URL to one of these items at point.

I didn't get that from you previous message. This could be implemented by improving or shadowing `magit-copy-section-value`.

Based on the following I though you were talking about when you are in the buffer into which you type the comment.

> when I'm commenting on an issue

**Comment by diamond-lizard** [comment]
> Based on the following I though you were talking about when you are in the buffer into which you type the comment.

That is the destination buffer, but I need to get the URL to other issues, commits, and pull requests on so I can refer to them in the comment.

**Comment by tarsius** [comment]
> Could we reopen this issue?

Yes we can do that, but...

> That is the destination buffer, but I need to get the URL to other issues, commits, and pull requests on so I can refer to them in the comment.

Yes, I have understood now that this is what you want to do. It's currently not supported so you might want to try out the feature that I have mentioned. You are supposed to get list of completion candidates with heading sorted by most recently updated. That can do the trick when trying to reference a recent topic. (Unfortunately some completion frameworks appear to discard the ordering.)

**Comment by agzam** [comment]
@tarsius I think this is related, let me know if I should create a separate issue for this (unless there's already one and I missed it)

It would be nice to add a method for storing org-links from a forge-topic. Right now calling `org-store-link` from a topic says: "No method for storing a link from this buffer"

**Comment by tarsius** [comment]
Like [`orgit-forge`](https://github.com/magit/orgit-forge)?

**Comment by agzam** [comment]
Oh, wait. I did not know it existed. I just need to use that? I knew about orgit, but not that one. Thank you Jonas. I'll give it a try

**Comment by cmacrae** [comment]
I'm not sure if this potentially fits in as part of this work, but I'd love to be able to have the URL be copied to the killring when creating a PR, perhaps with a hook?  

Our team's flow at work is to post on Slack with the name & URL of the PR to ask for review.  
At the moment, I create the PR via forge, then browse the PR from the buffer to open it in my browser, then copy the url to switch to Slack and paste it. It'd be really nice to be able to eliminate that little hop.  
In fact, with a hook, I could potentially even use some Emacs Slack package to automatically post the message ✨ But I'm just getting ahead of myself now

**Comment by tarsius** [comment]
> Let's say I'm looking at a list of issues, commits, or pull requests in a magit status buffer, and I want to get the URL to one of these items at point.

In many places `C-c C-w` now does that and `C-c C-o` can be used to open the url in a browser.

**Comment by cmacrae** [comment]
Regarding my comment above, this is what I ended up writing to automatically yank the PR title and URL to the kill-ring:

``` elisp
(use-package forge
  :after magit
  :config
  (defun cm/forge-post-submit-callback-kill-info (value _headers _status _req)
    (when t
      (when-let ((url (alist-get 'html_url value))
                 (title (alist-get 'title value)))
        (kill-new (format "%s\n%s" title url)))))

  (add-hook 'forge-post-submit-callback-hook 'cm/forge-post-submit-callback-kill-info))
```
