### ISSUE TITLE
Got an error from the GitHub API (wrong-type-argument listp error)! when trying to CR

### ISSUE THREAD

**Issue by otavioschwanck** [magit/forge#309]
When i press @cr on a pull request o got:

Got an error from the GitHub API (wrong-type-argument listp error)!

I toggled  debug on error but don't showed any error.

Emacs 27.1
Magit 2fb3bf7, Git 2.27.0, Emacs 27.1, gnu/linux

I can see all pull requests but cannot review.

**Comment by tarsius** [comment]
> When i press @cr on a pull request o got:

Excuse me... what?

**Comment by otavioschwanck** [comment]
@tarsius Sorry, @ C R = Core Review!

![image](https://user-images.githubusercontent.com/9551316/99710936-ec622400-2a7f-11eb-8c0b-d031ad6bdaed.png)

`Try (setq debug-on-signal t) immediately before triggering the issue. That's more aggressive than debug-on-error and should give you a backtrace.`

Didn't work this debug.

**Comment by otavioschwanck** [comment]
> > When i press @cr on a pull request o got:
> 
> Excuse me... what?
> 
> > Got an error from the GitHub API (wrong-type-argument listp error)!
> 
> It's you who says "Got an error from the GitHub API", right? I.e. you should have written:
> 
> > Got an error from the GitHub API `(wrong-type-argument listp error)`!
> 
> No, the **Github API** does not return errors like `(wrong-type-argument listp error)`.
> 
> Try `(setq debug-on-signal t)` immediately before triggering the issue. That's more aggressive than `debug-on-error` and should give you a backtrace.

![image](https://user-images.githubusercontent.com/9551316/99711086-1ca9c280-2a80-11eb-9e02-5ef56810492e.png)

This  `(setq debug-on-signal t)` don't toggled debug.

The @ cr is review pull request, sorry!

**Comment by tarsius** [comment]
> The @ cr is review pull request, sorry!

So this too is a bug in the `github-review` package. Please report it there.
