### ISSUE TITLE
Improve pull-request-list-mode view

### ISSUE THREAD

**Issue by otavioschwanck** [magit/forge#312]
I work on a repository that more than 30 devs work.  Would be nice to add the ` | State | Created By | ` in this view.  Would be SUPER nice to  add  some filter commands to this screen to like:

Search by created_by 
Search only open
Search by assigned review to you
Search by review assigned to you

**Comment by tarsius** [comment]
Some of this is possible now.

**Comment by tarsius** [comment]
And now all of it is.
