### ISSUE TITLE
forge-pull silently fails for gitlab

### ISSUE THREAD

**Issue by ziprandom** [magit/forge#328]
I'm using magit-forge for private repositories of an organization on gitlab.com and have to pin forge at 269effb4954071f590954c0e5b4faba3f27d03d0 (i haven't figured out whether this is really the last working commit). 

For current versions of forge I can't sync with the repository anymore. calling `forge-pull` will start the process, says `pulling issues` for an instant before doing the git pull and finish without an error and without showing any issues or pull requests. 

This also happens when I delete the database and start from scratch. I'm not sure whether this might be related to authentication, but the tokens & setup work flawless for the earlier version. 

There's no error, nothing in `*Messages*`, just no output in the magit ui. 

Using the same version of forge fit a github repository works so I assume this is related to the gitlab connector.

**Comment by tarsius** [comment]
> says `pulling issues` for an instant

What does it say exactly? It should say something like `Pulling foo/bar issues`. If it says just `Pulling  issues`, then that it at least narrows down the issue a bit. Otherwise make sure that `foo/bar` actually identifies the upstream repository and not your fork for example.

**Comment by ziprandom** [comment]
@tarsius thanks for your quick reply!

```
Pulling <org>/<repo> done
Storing <org>/<repo>...done
Running git fetch origin
Git finished
```

and shows

```
Stashes (8)...
Recent commits...
<-- end of buffer -->
```

**Comment by tarsius** [comment]
Maybe there aren't actually any open issues and pull-requests?

**Comment by ziprandom** [comment]
I'm comparing againste the same repository using the sam api token 

The only difference is the version of forge. The old version shows plenty of Issues/PR's.

**Comment by tarsius** [comment]
I suggest you sprinkle debug statements to find out where things start going south.

**Comment by tarsius** [comment]
Does `M-x forge-list-topics` list all the topics that it should list?

**Comment by ziprandom** [comment]
`M-x forge-list-topics` doesn't list any topics. 

I also tried with `HOME=$(mktemp -d) emacs -q` to make sure no effects from the rest of my config occur. 

From what I experience it should not work for any gitlab user. The fact that I'm the only one to report it indicates it's only my though problem ..

**Comment by tarsius** [comment]
... yeah, I can't really think any tip beyond debug statements to figure out what (if any) steps are unexpectedly omitted.

**Comment by tarsius** [comment]
Please check if 18f03a743739e30dbcdfcae663d03c3dd24278e6 fixes this.

**Comment by ziprandom** [comment]
it does indeed!
