### ISSUE TITLE
Gitlab: forge-pull stuck on pullreqs

### ISSUE THREAD

**Issue by jkdufair** [magit/forge#335]
When I start with an empty forge database and `forge-pull`from Gitlab, issues pull correctly, per modeline updates and then forge stalls on "Pulling pullreq 1/x". In the modeline. I see in the *Process List* that the gitlab.com process is opening and destroying process buffers every second or so.

I have version 20210303.1711 installed from melpa. Let me know if I can help troubleshoot.

**Comment by tarsius** [comment]
Fixed. I have rewritten history to remove the faulty commit. Uhuh. I hope that Melpa picks it up.

**Comment by jkdufair** [comment]
That was fast! Thank you!
