### ISSUE TITLE
Weird hyperlink in documention

### ISSUE THREAD

**Issue by C-Entropy** [magit/forge#336]
[here](https://magit.vc/manual/ghub.html#Storing-a-Token), you should see the text `password 012345` been linked to [pixiv](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=012345), which looks like a bug.

**Comment by tarsius** [comment]
I don't see that. Can you provide more information; maybe a screenshot?

**Comment by C-Entropy** [comment]
![image](https://user-images.githubusercontent.com/23580174/110114040-f7528180-7dee-11eb-87fd-1dc13ebda263.png)
![image](https://user-images.githubusercontent.com/23580174/110114108-118c5f80-7def-11eb-930f-6937bbb69e08.png)

**Comment by C-Entropy** [comment]
Emm, I have visited manual on my phone, which doesn't have the link too. Maybe it has something to do with my firefox? I suppose it has nothing to do with Magit itself.
