### ISSUE TITLE
`FOREIGN KEY constraint failed` for large topic sets?

### ISSUE THREAD

**Issue by fosskers** [magit/forge#369]
When attempting to pull the topics of https://github.com/rustwasm/wasm-bindgen/, the fetching process gets about 20 pages in until I see the following in `*Messages*`:

> error in process filter: peculiar error: "FOREIGN KEY constraint failed" [2 times]

And then none of the topics end up getting stored.

Thanks again for Magit and Forge, and please let me know if there's any other information I can provide.

**Comment by tarsius** [comment]
This could be a duplicate of #294. Please test if the proposed workaround does the trick for you.

**Comment by tarsius** [comment]
Closing in favor of #294 and #489.
