### ISSUE TITLE
Cannot determine forge repository.  No url configured for "origin"

### ISSUE THREAD

**Issue by Linuus** [magit/forge#38]
As the title suggests, when I run `F y` in the Magit buffer I get this message.  If I look at the remotes I can see that the `remote.origin.url` variable is set.

![screenshot 2018-12-22 at 20 46 09](https://user-images.githubusercontent.com/379823/50378131-e1e84700-062a-11e9-992c-ca96c17a323d.png)

Have I missed some configuration?

**Comment by tarsius** [comment]
I don't see how this can happen. This is the relevant code:

```emacs-lisp
(cl-defmethod forge-get-repository ((demand symbol) &optional remote)
  "Return the forge repository for the current Git repository."
  (magit--with-refresh-cache
      (list default-directory 'forge-get-repository demand)
    (let* ((remotes (magit-list-remotes))
           (remote (or remote
                       (if (cdr remotes)
                           (car (member (or (magit-get "forge.remote") "origin")
                                        remotes))
                         (car remotes)))))
      (if-let ((url (and remote (magit-git-string "remote" "get-url" remote))))
          (forge-get-repository url remote demand)
        (when (memq demand forge--signal-no-entry)
          (error "Cannot determine forge repository.  %s"
                 (cond (remote  (format "No url configured for %S" remote))
                       (remotes "Cannot decide on remote to use")
                       (t       "No remote configured"))))))))
```

What is the output of `git remote get-url origin` and `git remote get-url origin --all`? (Make sure to include weird whitespace, if any, in what you post here.)

**Comment by Linuus** [comment]
Sorry, I was using an old version of git which didn't have the `get-url` command.

Thank you for the reply and merry christmas!

**Comment by tarsius** [comment]
What version was that? Might have to bump a dependency somewhere.

**Comment by Linuus** [comment]
I had git version 2.5.0 and upgraded to 2.19.0.

**Comment by tarsius** [comment]
It was added in `2.7.0`. I added an assert for that a long time ago.
