### ISSUE TITLE
.github/pull_request_template.md not showing up in new pull request buffers

### ISSUE THREAD

**Issue by cwlbraa** [magit/forge#382]
When I make a new PR using forge-create-pullreq, the pull request template in my repository doesn't appear in the buffer. I think this has been [an issue previously](https://github.com/magit/forge/issues/327), so I made sure I'm on the most recent SHA of forge and it's still happening. I tried debug-on-error, but so far as I can tell it does not error, the content of the template just doesn't show up. Any tips to debug?

**Comment by tarsius** [comment]
Could you point me to a repository that has that file so that  I could use that for testing purposes?

> Any tips to debug?

Add debug statements to `forge--topic-templates` (the one at line 640 in `forge-github.el`).

**Comment by cwlbraa** [comment]
> Could you point me to a repository that has that file so that I could use that for testing purposes?

unfortunately the repos I work on that have PR templates are private, but I cloned this one to check it out, and the template doesn't load for forge either. If it's of any interest, I'm on DOOM emacs & emacs-mac 27.2. When I have more time I'll have to poke at forge--topic-templates.

**Comment by tarsius** [comment]
It works for me. Make sure you use a recent `forge` version. Is `yaml` installed?

**Comment by cwlbraa** [comment]
`yaml` is installed and I am on the most recent forge version.

**Comment by tarsius** [comment]
Since it works for me, my suggestion is still to add debug statements to figure out where things start to break.

**Comment by catap** [comment]
@tarsius I found a private repo where this issues seems to be easy to reproduce: https://github.com/macports/macports-ports

It just doesn't read it template.

I'm using:
 - magit/magit@73530108
 - magit/forge@9e7d6835
 - yoshiki/yaml-mode@3a57058

**Comment by tarsius** [comment]
> I found a private repo where this issues seems to be easy to reproduce:

For me it works with that repository too. I can only repeat the recommendation to inject debug statements.

**Comment by catap** [comment]
@tarsius can you provide an example debug statments which you needed?

**Comment by tarsius** [comment]
```diff
diff --git a/lisp/forge-post.el b/lisp/forge-post.el
index 701f93d0..93256adc 100644
--- a/lisp/forge-post.el
+++ b/lisp/forge-post.el
@@ -129,6 +129,7 @@ (defvar-local forge--cancel-post-function nil)
 (defvar-local forge--pre-post-buffer nil)
 
 (defun forge--prepare-post-buffer (filename &optional header source target)
+  (message "-- forge--prepare-post-buffer")
   (let ((file (magit-git-dir
                (convert-standard-filename
                 (concat "magit/posts/" filename)))))
@@ -149,7 +150,10 @@ (defun forge--prepare-post-buffer (filename &optional header source target)
                   (?d "[d]iscard draft and start over" t))
             (erase-buffer)
             (setq resume nil)))
+        (message "---- %s %s" resume filename)
         (when (and (not resume) (string-prefix-p "new" filename))
+          (message "---- do")
+          ;; If we never get here, then add more debug statements above.
           (let-alist (forge--topic-template
                       (forge-get-repository t)
                       (if source 'forge-pullreq 'forge-issue))
diff --git a/lisp/forge-topic.el b/lisp/forge-topic.el
index c83aeadd..b9781c88 100644
--- a/lisp/forge-topic.el
+++ b/lisp/forge-topic.el
@@ -832,7 +832,11 @@ (defun forge--topic-templates-data (repo class)
 
 (cl-defmethod forge--topic-template ((repo forge-repository)
                                      (class (subclass forge-topic)))
+  (message "-- forge--topic-template %s" class)
   (let ((choices (forge--topic-templates-data repo class)))
+    (message "---- %s" (length choices))
+    ;; If this is 0, then also add debug statements to
+    ;; forge--topic-templates-data.
     (if (cdr choices)
         (let ((c (magit-completing-read
                   (if (eq class 'forge-pullreq)
```

**Comment by catap** [comment]
@tarsius I've extended your debug info with
```
diff --git a/lisp/forge-topic.el b/lisp/forge-topic.el
index 1f6dcb5..70823a4 100644
--- a/lisp/forge-topic.el
+++ b/lisp/forge-topic.el
@@ -822,6 +822,7 @@ alist, containing just `text' and `position'.")
 
 (defun forge--topic-templates-data (repo class)
   (let ((branch (oref repo default-branch)))
+    (message "----  branch: %s" branch)
     (mapcan (lambda (f)
               (with-temp-buffer
                 (magit-git-insert "cat-file" "-p" (concat branch ":" f))
```
and has such output:
```
forge--topic-templates-data
(No changes need to be saved)
-- forge--prepare-post-buffer
(New file)
markdown-mode math support enabled
---- nil new-pullreq
---- do
-- forge--topic-template forge-pullreq
----  branch: nil
---- 0
```

**Comment by catap** [comment]
BTW I can confirm that pull request is created via this new buffer.

**Comment by tarsius** [comment]
Well that explains it. Hurray!

Next step is figuring out *why* that is nil. Please add:

```diff
diff --git a/lisp/forge-github.el b/lisp/forge-github.el
index a04b61b4..38a72924 100644
--- a/lisp/forge-github.el
+++ b/lisp/forge-github.el
@@ -60,7 +60,9 @@ (cl-defmethod forge--pull ((repo forge-github-repository) until
        (forge--msg repo t nil "Storing REPO")
        (emacsql-with-transaction (forge-db)
          (let-alist data
+           (message "A %s" (oref repo default-branch))
            (forge--update-repository repo data)
+           (message "C %s" (oref repo default-branch))
            (forge--update-assignees  repo .assignableUsers)
            (forge--update-forks      repo .forks)
            (forge--update-labels     repo .labels)
@@ -109,6 +111,7 @@ (cl-defmethod forge--pull-topic ((repo forge-github-repository) n
 
 (cl-defmethod forge--update-repository ((repo forge-github-repository) data)
   (let-alist data
+    (message "B %s %S" .defaultBranchRef.name .defaultBranchRef)
     (oset repo created        .createdAt)
     (oset repo updated        .updatedAt)
     (oset repo pushed         .pushedAt)
```

and then pull using `f y`.

**Comment by tarsius** [comment]
But before you do take not of how long ago you last pulled:

```
Pull requests (60)
#12199 py-bottlenose: new port type: enhancement type: submission
#12198 new port: micronucleus type: submission
...
```

**Comment by catap** [comment]
@tarsius well... it requires to fetch all macport's PR which has more than 12K... It requires some time.

**Comment by catap** [comment]
@tarsius `py-bottlenose` was created from emacs. I just inserted template by hand to test that it isn't something inside this template that brokes forge.

Nope, it doesn't.

All another PR from me to this repo is created by hand via github web UI.

**Comment by catap** [comment]
@tarsius here the new debug:
```
Pulling macports/macports-ports...done
Storing macports/macports-ports...
A nil
B master ((name . "master"))
C master
error in process filter: ghub--handle-response-headers: BUG: missing headers
  See https://github.com/magit/ghub/issues/81.
  url: https://api.github.com/graphql
  headers: 0
  status: nil
  buffer: #<buffer  *http api.github.com:443*-87136>
error in process filter: BUG: missing headers
  See https://github.com/magit/ghub/issues/81.
  url: https://api.github.com/graphql
  headers: 0
  status: nil
  buffer: #<buffer  *http api.github.com:443*-87136>
error in process filter: Quit [2 times]
```

**Comment by tarsius** [comment]
> well... it requires to fetch all macport's PR which has more than 12K... It requires some time.

Ah! Another useful detail.

So you used `forge-add-repository` and the chose to not fetch all topics. I'll have to change that to fetch at least information about the repository itself.

**Comment by tarsius** [comment]
> here the new debug:

Yeah... that's another issue. Github sometimes just returns an empty response (or so we assume, it might also be a bug in `url.el`).

**Comment by catap** [comment]
@tarsius or it might be a sort of bot or DDoS protection because fetching more than 12K topics quite a task.

To avoid that I have to selected to not fetch everything.

But I'm fetching it now, I let you know when it's finished. It's on page 121 now.

**Comment by catap** [comment]
@tarsius I've fetch everyhting. Now I can provide requested debug:
```
Pulling macports/macports-ports...done
Storing macports/macports-ports...
A master
B master ((name . "master"))
C master
Storing macports/macports-ports...done
```

**Comment by catap** [comment]
@tarsius yay, fetching everyhing fixes the issue on the first place.

I guess it is the root cause of the issue.

**Comment by cwlbraa** [comment]
Ah, yeah! this explains it on my end as well, the primary repository where I have this issue has so many issues & PRs that I cannot successfully download all issues without getting rate-limited by github.

**Comment by tarsius** [comment]
Forge now fetches basic data for a repository even if we don't fetch topics and such.

To benefit from that you have to update both `forge` and `ghub` and then you have to "fetch" in each such sparse (aka "selective") repository to fetch the basic metadata. After that you have access to the topic templates even for such sparse repositories.

If you only update `forge` but not `ghub`, and there unfortunately (due to limitations of Melpa) will be quite a few people who do that, then you get this error when fetching forge data for *any* repository:

```
Keyword argument :sparse not one of (:username :auth :host :forge :headers :errorback)
```

I am posting that error message here, so that users who pasted that into a search engine are directed to the solution:

*To fix that error, simply update `ghub`.*

**Comment by catap** [comment]
@tarsius thanks, it is working!

Anyway, it starts to ask `Always pull all of XXX's topics going forward? yes/no` for each created pull request on such repositories.

Maybe it is good idea to suppress such  message?

**Comment by tarsius** [comment]
Well `forge-pull` is supposed to "Fetch all topics", so it makes sense for it to not fetch only one topic instead without making the user aware of that.

`forge-pull-topic` (`N f t`) does "Fetch one topic", and if point is on a topic or only one has been fetched so far, then that is offered as the default.

**Comment by catap** [comment]
@tarsius but if I selected before to not fetch all topics, it quite anoyeng to say `no` each pull request that I've created.

**Comment by tarsius** [comment]
But, as I just tried to explain, this only happens if you use the command that you are not supposed to use in this situation.

If forge is configured to only fetch certain topics for a given repository, then `forge-pull` does not fetch those topics. It only fetches the basic metadata about the repository itself, which is useful if you know or suspect that that information has changes, i.e. very seldomly.

To update a topic, you have to use `forge-pull-topic`. If you want to update multiple topics, then you have to use the command multiple times.

**Comment by catap** [comment]
@tarsius I'm creating a pull request via `' c p` where `'` is a command to go to this menu inside magit status:

![Screenshot 2021-09-28 at 22 13 10](https://user-images.githubusercontent.com/37775/135158923-12b2105c-96a4-4738-8f5a-54ee4fe76586.png)

after editing pull request (with template) and pressing `C-x C-s` (save PR) — it asks `Always pull all of XXX's topics going forward? yes/no`

**Comment by tarsius** [comment]
I see, that's not great. I'll see what I can do about it.

**Comment by tarsius** [comment]
Fixed.

(I might still change what `forge-pull` does when called interactively in a "selective" repository.)

**Comment by tarsius** [comment]
Ups, but apparently not committed.
