### ISSUE TITLE
Include imenu support

### ISSUE THREAD

**Issue by jdtsmith** [magit/forge#389]
Magit has imenu support which is wonderful.  It would be great for forge to extend that imenu support by including Pull Requests/Issues etc.  Ideally it would also trim the ` (#)` count suffix (see magit/magit#4477). Thanks for magit & forge!

**Comment by jdtsmith** [comment]
Thanks will give a try!

**Comment by jdtsmith** [comment]
I can tell this is going to be great, but right now this doesn't work reliably for me.  The issue is that `magit-imenu--index-function` sometimes finds the `status` section as the first section from the end of the status buffer.  Since it has no parent (presumably it _is_ the parent), this leads to:

```elisp
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  #f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x1fea7500f499>)(nil type)
  eieio-oref--closql-oref(#f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x1fea7500f499>) nil type)
  apply(eieio-oref--closql-oref #f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x1fea7500f499>) (nil type))
  eieio-oref(nil type)
  (oref parent type)
  (let* ((section (magit-current-section)) (type (oref section type)) (parent (oref section parent)) (parent-type (oref parent type))) (and (memq type entry-types) (memq parent-type menu-types)))
...
```

Sometimes this error occurs, other times it doesn't.  On a fresh startup with all status sections closed, all magit status buffers seem to exhibit the problem.  Once I _open_ a section and refresh, that section shows up in imenu, though other sections do not.  On magit 20210820.808.

**Comment by jdtsmith** [comment]
To clarify, this is actually 2 issues:

- On first startup of a magic-status, sometimes the (parent) status section is found at the end of the buffer, leading to the above error.
- When a section is collapsed, it is not always included in the imenu output. When no sections are expanded "Imenu is empty" is indicated. Expanding the section and then refreshing includes that section info (but not others).

**Comment by tarsius** [comment]
1. Fixed.

2. For performance reasons many collapsed sections don't populate their bodies until they are expanded. Expanding such a section creates the body/children and collapsing them again keeps the body/children. Refreshing while collapsed however removes them again (or rather it does not re-create them).

   It will remain that way until a (potentially) a complete rewrite. Meanwhile I do not intend to add any kludges to accommodate imenu, which (in magit buffers) I do not consider an important feature.

**Comment by jdtsmith** [comment]
Thanks.  Understood regarding section expansions, which are in any case just a `M-2` away.  The bigger concern was that after expansion, a refresh was still needed to populate imenu (likely because it cached the empty list and the cache remained valid), but that no longer seems to be the case with this fix.  

I wouldn't use imenu at all in magit were it not for consult-imenu.  The ability to narrow down and select issues/etc. with orderless, export a subset to a list with embark, and visit them later, etc. is very convenient.
