### ISSUE TITLE
docs: `M-x forge-pull-pullreq` [No match]

### ISSUE THREAD

**Issue by erikmd** [magit/forge#390]
Hi @tarsius,

I've just installed `forge`, following the documentation of `forge` and `ghub`, but I was not able to find the command mentioned [here in the docs](https://magit.vc/manual/forge/Pulling.html): `M-x forge-pull-pullreq`.

I believe this command has been renamed to `forge-pull-topic` by d490ceaf95cac25a8234753a560e651160e5faa1 but the documentation was not yet updated.

**Comment by tarsius** [comment]
Thanks for the hint!
