### ISSUE TITLE
Pull request comments that require resolution not showing up in "visit topic" buffer

### ISSUE THREAD

**Issue by BigTheta** [magit/forge#396]
I understand that resolving conversations from within forge is not support right now, but we should at least be able to _see_ the comments when we are viewing the PR in forge?

How to reproduce:

1. Create a pull-request
2. In github: 
     a. Leave a comment on the pull-request
     b. Select "add a single comment"
     c. leave another comment
     d. Select "Start a review" and select the "request changes" bubble before confirming
3. From forge: 
    a. Pull topics
    b. Visit the pull request in forge

The comments requiring resolution are not included in the topic view, while the single comment is.

**Comment by tarsius** [comment]
Yes review comments aren't supported. See #75.
