### ISSUE TITLE
Error in forge--post-submit-callback when delete-by-moving-to-trash

### ISSUE THREAD

**Issue by unhammer** [magit/forge#397]
I'm getting `delete-directory: (file-error "Renaming" "Not a directory" "/home/me/arepo/.git/magit/posts" "/home/me/.local/share/Trash/files/postsJfzffP")` from
https://github.com/magit/forge/blob/a3e6f8aab16a8213cd389fe79d8c02300d26cab7/lisp/forge-post.el#L251
in emacs 28.0.50 (a9560a2b51191bbd832641fb8b0f9d88e89b5d36).

Note this comment from the definition of delete-directory:
```
     ((and delete-by-moving-to-trash trash)
      ;; Move non-empty dir to trash only if recursive deletion was
      ;; requested.  This mimics the non-`delete-by-moving-to-trash'
      ;; case, where the operation fails in delete-directory-internal.
      ;; As `move-file-to-trash' trashes directories (empty or
      ;; otherwise) as a unit, we do not need to recurse here.
```

while delete-directory is called from forge with recurse=nil but trash=t. Should probably have trash=nil – trashing empty directories doesn't make much sense?

**Comment by tarsius** [comment]
Thanks for the report!
