### ISSUE TITLE
Can't checkout to pull request without `master` branch

### ISSUE THREAD

**Issue by catap** [magit/forge#414]
When I try to checkout to pull request when repository hasn't got `master` branch, only `origin/master` it fails, because it tried to setup upstream to simple `master`, not `origin/master`.

**Comment by tarsius** [comment]
Would you prefer to use `origin/master` as the upstream even if `master` did in fact exist? If so, then change the value of `magit-branch-prefer-remote-upstream`.

**Comment by catap** [comment]
@tarsius can it be per-repository settings? Because today some repos using `master`, some `main`, some I have no idea that... `develop`?

**Comment by tarsius** [comment]
The name is not hardcoded. When a pull-request is created, then one has to specify which branch X to merge into which branch Y. `forge` gets that information using the forge's API and sets the branch relation based on that.

If uses `<remote>/<Y>` or `<Y>` based on the variable `magit-branch-prefer-remote-upstream`. And with the latest commit (f97bc47e9e2a2a6300dd267bdd67a88254f65aa7) it falls back to `<remote>/<Y>` when `<Y>` does not exist, even if the variable says to use the former.

**Comment by catap** [comment]
@tarsius thanks, I'm looking for behaviour which was inroduced at f97bc47
