### ISSUE TITLE
No results in forge-list-labeled-issues

### ISSUE THREAD

**Issue by lvlts** [magit/forge#430]
Whenever using `forge-list-labeled-issues`, using the gitlab (custom host) forge I get no output whenever auto-completing the LABEL name. I'm running Doom Emacs, and I believe the LABEL is selected using the `ivy` package, but I am not convinced. The LABEL comes back as a list/cons cell, and therefore no results are present.

I have managed to fix it locally by changing https://github.com/magit/forge/blob/72b29bd7bc4172705b55bdd2a5070202ec154069/lisp/forge-list.el#L256 

Into:

```
 id (car label))))) 
```

Is this an issue with my Emacs distribution, or is it something that is affecting `forge` ?

**Comment by tarsius** [comment]
Thanks for the report!
