### ISSUE TITLE
Invalid base64 data when doing forge-pull

### ISSUE THREAD

**Issue by m1-key** [magit/forge#435]
As given in the manual, I created a .authinfo file with all the details. But whenever I try to use forge, it says invalid base64 data.  
In a few repositories, it worked well, but in most of the repositories, it's not working.  
This is my .authinfo content : 
`machine api.github.com login m1-key^forge password my_personal_token` ( my_personal token is a value which I got from Github )
What should I do?

**Comment by tarsius** [comment]
What Forge version are you using? I suspect it's one that doesn't contain 483baae56df8b1d8f1a9136512d23e106c831c0b.

**Comment by m1-key** [comment]
How can I find the version of Forge? 
This is mine magit log : `Magit 20210913.1931 [>= 3.2.1], Git 2.33.1, Emacs 27.2, gnu/linux`

**Comment by tarsius** [comment]
See https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html to learn more about installing, updating and querying packages.

Based on the magit version you are using I am guessing that you use a forge version that is too old.

**Comment by m1-key** [comment]
Thanks a lot, @tarsius, it was the version issue as you said. I updated the version, but it was still using the same old version, so I removed all the packages, reinstalled them via init.el and it worked perfectly fine.
