### ISSUE TITLE
Make forge-pull-topics and related actions non-blocking or periodic

### ISSUE THREAD

**Issue by DaniruKun** [magit/forge#437]
As a user coming from using VSCode and other IDEs, I expect that actions related to working with e.g. a Github forge's topics do not block my main Git workflow.

Here is an example from a real situation I had at work this week:
I am pair programming on a large monolithic project, and am creating some new commits to be pushed to remote. I also decide to initialise a forge for the repo and pull the topics (to be used later). When I do `forge-pull-topics` or similar, it **takes over 5 minutes** for the blocking command to finish and let me do anything useful. Even when running Emacs in server mode, this makes all clients useless until the command completes.

A comparison is made to a git push/pull interactive workflow in the documentation, but I disagree - forge topics are a secondary workflow and shouldn't block the primary git workflow (and ideally, should poll a forge remote regularly).

**Comment by tarsius** [comment]
> As a user coming from using VSCode and other IDEs, I expect that actions related to working with e.g. a Github forge's topics do not block my main Git workflow.

You have to adjust your expectations. Microsoft is a billion dollar company and I am a single human being. My design decisions were guided by the needs of foss-sized repositories, not proprietary monorepos.

You can add a repository without fetching any data using `n a` and then answering that you want to fetch only individual repositories. You can then create new topics as usual (and later fetch updates for them individually using `n f t`). I though you could already fetch any *existing* topic individually but apparently I haven't implemented that yet. I have now added that to my private todo list.

**Comment by tarsius** [comment]
Turns out I have implemented that, but there's a regression. Should be fixed fairly soon.

**Comment by tarsius** [comment]
Fixed. Any topic can be fetched with `n f t` in selective repositories again.
