### ISSUE TITLE
Problem setting up forge for self-hosted gitlab instance with SSH identities

### ISSUE THREAD

**Issue by phiadaarr** [magit/forge#439]
I would like to use forge together with SSH identities on a self-hosted gitlab instance.

For this, according to https://github.com/magit/forge/wiki/Tips-and-Tricks#teaching-forge-about-ssh-identities, I set `forge-alist` to:
```
(custom-set-variables
 '(forge-alist
   '(("gitlab.mpcdf.mpg.de" "gitlab.mpcdf.mpg.de/api/v4" "gitlab.mpcdf.mpg.de" forge-gitlab-repository)
     ("gl" "gitlab.mpcdf.mpg.de/api/v4" "gitlab.mpcdf.mpg.de" forge-gitlab-repository)
     ("github.com" "api.github.com" "github.com" forge-github-repository)
     ("gitlab.com" "gitlab.com/api/v4" "gitlab.com" forge-gitlab-repository)
     ("salsa.debian.org" "salsa.debian.org/api/v4" "salsa.debian.org" forge-gitlab-repository)
     ("framagit.org" "framagit.org/api/v4" "framagit.org" forge-gitlab-repository)
     ("gitlab.gnome.org" "gitlab.gnome.org/api/v4" "gitlab.gnome.org" forge-gitlab-repository)
     ("codeberg.org" "codeberg.org/api/v1" "codeberg.org" forge-gitea-repository)
     ("code.orgmode.org" "code.orgmode.org/api/v1" "code.orgmode.org" forge-gogs-repository)
     ("bitbucket.org" "api.bitbucket.org/2.0" "bitbucket.org" forge-bitbucket-repository)
     ("git.savannah.gnu.org" nil "git.savannah.gnu.org" forge-cgit**-repository)
     ("git.kernel.org" nil "git.kernel.org" forge-cgit-repository)
     ("repo.or.cz" nil "repo.or.cz" forge-repoorcz-repository)
     ("git.suckless.org" nil "git.suckless.org" forge-stagit-repository)
     ("git.sr.ht" nil "git.sr.ht" forge-srht-repository))))
```
I have set up the gitlab token in `.authinfo.gpg`. If I run `forge-pull` on a repository that has been cloned without SSH identites (e.g. `https://gitlab.mpcdf.mpg.de/ift/nifty`), everything works as expected. If I run `forge-pull` on a repository, that has been cloned *with* SSH identities (e.g. `gl:ift/nifty`), I get:
```
Cannot determine forge repository.   gl:ift/nifty isn't a forge url
```

Based on previous issues, I checked the output of `forge--split-url`:
```
(forge--split-url "https://gitlab.mpcdf.mpg.de/ift/nifty")
-->
("gitlab.mpcdf.mpg.de" "ift" "nifty")

(forge--split-url "gl:ift/nifty")
->
nil
```
Do you have an idea what could be going wrong?

My emacs version is 27.2 and I use doom emacs (v.21.12.0-alpha). I use the `forge` checkout `41efa674cff0b447efbc103494fd61ec9b9156ae` (one behind current `m̀aster`) and the `ghub` checkout `fb2ecd726577b0049cd56883649c6ccb8072ae63` (current `master`).

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by phiadaarr** [comment]
Thanks a lot for your quick answer! However, I am afraid this does not solve my problem. I have updated forge to 98e8ee6c854d944a99725c32912351af850216d3 and now I get a worse result:

```
(forge--split-url "https://gitlab.mpcdf.mpg.de/ift/nifty")
-->
nil

(forge--split-url "https://gitlab.mpcdf.mpg.de/ift/nifty")
-->
nil

(forge--split-url "gl:ift/nifty")
->
nil
```

**Comment by tarsius** [comment]
Works for me. Does your `~/.ssh/config` contain:

```
Host gl
     HostName gitlab.mpcdf.mpg.de
```

?

**Comment by phiadaarr** [comment]
Ohh, sorry, my previous comment was a mistake. I have to omit that I do not fully understand how doom-emacs works. I had to open magit once to trigger its initialization and defining its functions. The `forge--split-url` commands give the expected results now. Thanks a lot!
However, during `forge-pull` my whole emacs hangs until I abort whatever it is doing with C-g. But I am pretty sure that this is a problem on my side. Thanks a lot for your help!

**Comment by phiadaarr** [comment]
> However, during forge-pull my whole emacs hangs until I abort whatever it is doing with C-g. But I am pretty sure that this is a problem on my side. Thanks a lot for your help!

I tried to track down this problem and I could not make any progress.

emacs asks for my gpg passphrase and tells me: `Decrypting /home/<user>/.authinfo.gpg...done`. This looks good. But then emacs just hangs and does not respond to anything except `C-g`. Do you have an idea how I can get more information what is going on?

Any help is very much appreciated! If you think this should go into a separate issue, I am happy to open a new one.

**Comment by tarsius** [comment]
I am so very tired of these issues. I understand it is annoying for you but imagine having to do this over and over again because there is always someone new with an unusual usecase or who has misconfigured something. So please keep banging on it by yourself for a while.

**Comment by tarsius** [comment]
That being said, maybe you just did not notice that in the mode-line (not the minibuffer) it says that stuff is being pulled. Wait for that to finish.
