### ISSUE TITLE
ssh .config aliases for hosts not expanded when matching against forge-alist

### ISSUE THREAD

**Issue by dusek** [magit/forge#44]
My `~/.ssh/config` file contains:

```
Host gh
        Hostname github.com
        User git

Host gl
        Hostname gitlab.com
        User git
```

This is so that I do not have to type `git@github.com` and `git@gitlab.com` on the command line, and can instead do e.g. `git remote add dusek gl:dusek/repo`. I have been using magit itself for at least 2 years with these ssh "shortcuts" with no issue.

However when attempting to create a pull request on gitlab.com for the `gitlab-ce` repository (with `' p`), I get this message from forge:

```
Cannot determine forge repository.  gl:dusek/gitlab-ce.git isn’t a forge url
```

Here `dusek/gitlab-ce.git` is my fork of "parent" `gitlab-org/gitlab-ce.git`, and I want to merge a fork's branch into the master branch of the "parent" repository (i.e. the typical external contributor workflow). The output of `git remove -v` is:

```
origin	gl:dusek/gitlab-ce.git (fetch)
origin	gl:dusek/gitlab-ce.git (push)
upstream	https://gitlab.com/gitlab-org/gitlab-ce.git (fetch)
upstream	none (push)
```

Forge could in principle figure out (just like git or ssh does) that `gl` is just an alias configured in `~/.ssh/config` to actually mean `git@gitlab.com`. I do not know however if there is e.g. some `ssh` command that could output an "expanded" connection string (e.g. something like `ssh-expand gl` which would output `git@gitlab.com`), or some alternative way.

**Comment by YoungFrog** [comment]
"ssh -G gl" might help:

>      -G      Causes ssh to print its configuration after evaluating Host and Match
>              blocks and exit.

**Comment by dusek** [comment]
@YoungFrog thanks!

```
$ ssh -G gl
user git
hostname gitlab.com
port 22
addkeystoagent false
addressfamily any
[...63 analogically-formatted lines...]
```

**Comment by dusek** [comment]
Thanks for the suggestion. Since I use the `gh` and `gl` ssh aliases really only for git, it is a very usable solution to instead configure them in git's global configuration.

I removed the `gh` and `gl` from my `~/.ssh/config`, and instead added this to my `~/.gitconfig`:

```
[url "git@gitlab.com:"]
        insteadOf="gl:"
        pushInsteadOf="gl:"
[url "git@github.com:"]
        insteadOf="gh:"
        pushInsteadOf="gh:"
```

When e.g. pushing with magit (using `P p`), the line that  previously read `Pushing to gl:dusek/gitlab-ce.git` in the `magit-process: ...` buffer now changed to `git@gitlab.com:dusek/gitlab-ce.git` and it works (I get to selecting the pull-request template).

**Comment by tarsius** [comment]
Closing for now. *If* it turns out that there are users that actually need to do this at the ssh level (beside my own minor use-case), then I might reconsider.

**Comment by alexgaribay** [comment]
I have a use-case where I need to use a specific SSH key for a GitHub project and I'm doing that by adding an entry in the SSH config file to use that key for a custom host. Is there a way to use forge with that type of configuration?

This is what my config looks like
```
Host github.com-org
  HostName github.com
  IdentityFile ~/.ssh/other_ssh_key
```

**Comment by YoungFrog** [comment]
@alexgaribay I think you can simply add an entry to `forge-alist`. IIUC it would look like:
`(add-to-list 'forge-alist '("github.com-org" "api.github.com" "github.com" forge-github-repository) 'append)`

**Comment by tarsius** [comment]
@YoungFrog Indeed.

I think I knew about this at some point, otherwise I would not have added this to `forge-alist`'s doc-string: "There can be multiple elements that only differ in GITHOST.". But that's easily missed and doesn't mention why you might want to add such an entry. I have added some information about this to https://github.com/magit/forge/wiki/Tips-and-Tricks

**Comment by bvraghav** [comment]
Thank you @tarsius 
https://github.com/magit/forge/wiki/Tips-and-Tricks is very informative, and an excellent design.
