### ISSUE TITLE
`while: Invalid search bound (wrong side of point)` after called `forge-pull-notifications`

### ISSUE THREAD

**Issue by damoncro** [magit/forge#444]
Part of the backtrace:

```
Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-forward("^\\([^:]*\\): \\(.+\\)" #<marker at 1 in  *http api.github.com:443*-882243> t)
  (while (re-search-forward "^\\([^:]*\\): \\(.+\\)" url-http-end-of-headers t) (push (cons (match-string 1) (match-string 2)) headers))
  (let (headers) (when (memq url-http-end-of-headers '(nil 0)) (setq url-debug t) (let ((print-escape-newlines nil)) (error "BUG: missing headers\n  See https://github.com/magi..." (url-recreate-url (ghub--req-url req)) url-http-end-of-headers status (current-buffer)))) (while (re-search-forward "^\\([^:]*\\): \\(.+\\)" url-http-end-of-headers t) (push (cons (match-string 1) (match-string 2)) headers)) (setq headers (nreverse headers)) (goto-char (1+ url-http-end-of-headers)) (if (and req (or (ghub--req-callback req) (ghub--req-errorback req))) (setq-local ghub-response-headers headers) (setq-default ghub-response-headers headers)) headers)

```

**Comment by tarsius** [comment]
That doesn't happen for me. Does it always happen for you?

**Comment by damoncro** [comment]
But I do not have any notifications tough.

**Comment by damoncro** [comment]
Error is from this function: `ghub--handle-response-headers: Invalid search bound (wrong side of point)`

**Comment by damoncro** [comment]
I found it happened when no new notifications arrived (If i read it, error will generate again).

**Comment by damoncro** [comment]
It also happens in `github-review-start`. Error is from `ghub--handle-response-headers`, `re-search-forward`'s BOUND `url-http-end-of-headers` is invalid.

**Comment by tarsius** [comment]
If you look at that function you can see that it tries to catch an elusive bug. I suspect that what you are seeing is a mutation of that bug. Please add debug statements to that function to gain more insight into this mutation and post your findings here.
