### ISSUE TITLE
magit-visit-thing-at-point doesn't follow links hidden in rendered markdown

### ISSUE THREAD

**Issue by dabrahams** [magit/forge#452]
(Filed as a bug because the link text is hidden and thus very hard to access, but could be considered a feature request.  Possibly also related to #307)

I expected to hit `RET' on a link in an issue body and be offered a way to view that webpage.

Instead I got:
```
user-error: There is no thing at point that could be visited
```
To reproduce, create an issue whose body contains a markdown link (e.g. `[this](http://whatever…)`), visit the issue in forge, put the point over the square-bracketed word (the URL is hidden), and hit `RET'.

Backtrace is pretty minimal:

```
  magit-visit-thing()
  funcall-interactively(magit-visit-thing)
  call-interactively(magit-visit-thing nil nil)
  command-execute(magit-visit-thing)
```

Thanks for magit!

**Comment by tarsius** [comment]
[Here](https://github.com) is such a link.

**Comment by tarsius** [comment]
And also mention someone: @dabrahams.

**Comment by tarsius** [comment]
I've implemented a minimal viable version. Also see #53.

**Comment by dabrahams** [comment]
Nice, thanks!
