### ISSUE TITLE
While fetchiing the ocaml/ocaml repository I got the followin error:

### ISSUE THREAD

**Issue by shindere** [magit/forge#454]
```
error in process filter: HTTP Error: 502, "Bad gateway", "/graphql",
((data) (e\rrors ((message . "Something went wrong while executing your
query. This may be\ the result of a timeout, or it could be a GitHub
bug. Please include `8118:0F6\B:7862:5B32C:61DDB7AC` when reporting this issue."))))
```

Do you need a backtrace here?

**Comment by shindere** [comment]
Sorry for the noise. Ilooked at the most recent issues because I never
had this problem before, but I didn't think aobut looking to the FAQ. My
bad.

**Comment by tarsius** [comment]
No problem. Happy retries ;-)

**Comment by shindere** [comment]
Jonas Bernoulli (2022/01/11 11:36 -0800):
> No problem. Happy retries ;-)

Thanks. It ended up working. Really fascinating that retrying can
sometimes work.
