### ISSUE TITLE
Creating custom views (lists of topics)

### ISSUE THREAD

**Issue by shindere** [magit/forge#455]
I would like to build lists of topics, a bit similar to what is already
possible for pull requests or issues, but without distinguishing one
from another. So for isntance a list of assinged topics, no matter
whether they are issues or pull requests.

Also, I would like to be able to customize how each line is printed. It
could be via % formatters but if it's not that powerful, I'm fine.

For instance, I'd be able to see entries like

1583io: title by author

where the three first fields are the number of the topic, its type
(issue or merge request) and its status.

Would that be doable?

Many thanks because that's would be an amazing help for me, I realsied
today I always wanted to be able to explore repos that way but was
unable to state it, until I read forge's docuemntation again recently.

**Comment by tarsius** [comment]
> I would like to build lists of topics, a bit similar to what is
> already possible for pull requests or issues, but without
> distinguishing one from another. So for isntance a list of assinged
> topics, no matter whether they are issues or pull requests.

I've just pushed a big change, which includes this.

The new entry point is `n t`.  That lists all open topics in a new buffer and at the same time displays a menu, which lets you limit to just issue or pull-requests, or do other filtering.  You can leave just the menu with `C-g`, or the menu and the list with `q`. To bring up the menu while the list is still the current buffer, use `n`.
 
> Also, I would like to be able to customize how each line is
> printed. It could be via % formatters but if it's not that powerful,
> I'm fine.

The `forge-topic-list-columns` and `forge-global-topic-list-columns` options can be used for that.  (The former already existed for a few years, but it wasn't advertised as an option and lacked documentation.)

**Comment by shindere** [comment]
I couldn't give this a try yet but I would like to express deep gratitude
for the project in general and for the work presented here in
particular.

**Comment by tarsius** [comment]
Thanks! I appreciate that.

**Comment by shindere** [comment]
Jonas Bernoulli (2023/12/21 12:56 -0800):
> Thanks! I appreciate that.

That's the least one can do!
