### ISSUE TITLE
error building forge.html on MacOS

### ISSUE THREAD

**Issue by slyrus** [magit/forge#46]
On MacOS, I see two problems. First, I have to use homebrew's makeinfo, That's easy enough to fix. But then when I use that, I see the following error:

```
...
Generating forge.info
Generating dir
Generating forge.html
sed: 1: "/<link rel="stylesheet" ...": command a expects \ followed by text
make[1]: *** [forge.html] Error 1
make: *** [docs] Error 2
```

**Comment by tarsius** [comment]
Sounds like your `make` interprets "\" at the end of a line as quoting the following newline character, while mine uses it as a character in its own right.  Try doubling the backquote and/or using Gnu's Make.

**Comment by tarsius** [comment]
Sorry but I am not really interested in investigating how to fix this incompatibility myself. If you figure it out, then please submit a pull-request. I don't think many users generate the html manuals at all, so it is acceptable if that fails on some platforms / implementations of the involved tools. Not great, but there are so many more important things to do.
