### ISSUE TITLE
Search failed: "^title: " when trying to create an issue

### ISSUE THREAD

**Issue by ccressent** [magit/forge#481]
While working on https://github.com/sensu/sensu-go, if I call `forge-create-issue`, after selecting an issue template I get the following error and nothing else happens:
```
Search failed: "^title: "
```

I'm assuming this is because the templates in that repo do not have a `title:` key while the forge code assumes they should?
See:
- https://raw.githubusercontent.com/sensu/sensu-go/main/.github/ISSUE_TEMPLATE/bug_template.md
- https://github.com/magit/forge/blob/master/lisp/forge-post.el#L163-L166

Creating a pull request from [the template in that repo](https://raw.githubusercontent.com/sensu/sensu-go/main/.github/PULL_REQUEST_TEMPLATE.md) works fine. I'm assuming that's because it doesn't have any special key/values at the top of the template.

I've tried creating a backtrace to include here, but after toggling debug on error with `toggle-debug-on-error` and running `forge-create-issue` again, all I get is a different message:
```
Attempt to set a constant symbol: nil
```

Is there something else I can do to help get to the bottom of this?

**Comment by tarsius** [comment]
Thanks for the report!

Yes it was because of the missing `title:`.
