### ISSUE TITLE
forge--pull-notifications passes a not sequencep boolean when pulling notifications

### ISSUE THREAD

**Issue by kimjetwav** [magit/forge#484]
- Error:

When pulling notifications from a github repo, the forge command errors with `Wrong type argument: sequencep, t`, rather than pulling the notifications.

- Details:

Forge built from commit https://github.com/magit/forge/commit/22c43d3471760dfe00cff0f27e8349ce0e3cb247 (under emacs 29.0.50 master) encounters an error when attempting to pull notifications (via either `N f n` or `N f f`).

This is a result of https://github.com/magit/forge/blob/22c43d3471760dfe00cff0f27e8349ce0e3cb247/lisp/forge-github.el#L340-L341

This was introduced in https://github.com/magit/forge/commit/d8773c8de4a7e903a978d1ae36b63a76a257141d. Ultimately the `t` val of this param pair is passed on to `url-hexify-string` which is not defined for this type.

- Stack trace:

``` elisp
Debugger entered--Lisp error: (wrong-type-argument sequencep t)
  url-hexify-string(t)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_20>((all . t))
  ghub--url-encode-params(((all . t)))
  ghub-request("GET" "/notifications" ((all . t)) :query nil :payload nil :headers nil :silent nil :unpaginate t :noerror nil :reader nil :username nil :auth forge :host "api.github.com" :callback nil :errorback nil :extra nil)
  ghub-get("/notifications" ((all . t)) :host "api.github.com" :auth forge :query nil :payload nil :headers nil :silent nil :unpaginate t :noerror nil :reader nil :callback nil :errorback nil)
  forge--ghub-get(nil "/notifications" ((all . t)) :host "api.github.com" :unpaginate t)
  #f(compiled-function (class githost &optional callback) #<bytecode -0xa5b52432fa934cc>)(forge-github-repository "github.com")
  apply(#f(compiled-function (class githost &optional callback) #<bytecode -0xa5b52432fa934cc>) forge-github-repository "github.com")
  forge--pull-notifications(forge-github-repository "github.com")
  forge-pull-notifications()
  funcall-interactively(forge-pull-notifications)
  command-execute(forge-pull-notifications)
```

**Comment by tarsius** [comment]
Thanks for the report!
