### ISSUE TITLE
FOREIGN KEY constraint failed on large Gitlab repo

### ISSUE THREAD

**Issue by MichaelXavier** [magit/forge#486]
I'm trying to pull the MRs for a large, private gitlab repo. Forge takes a while because there's about 1500 MRs when you include closed issues. This takes quite a while but when it starts inserting them into the database I get `"FOREIGN KEY constraint failed" [2 times]`. I've tried running forge-reset-database but that didn't help. Unfortunately the repo is private so I'm not able to share a link. Are there any workarounds? I honestly would be fine if it didn't pull closed MRs or if it just made a best effort on saving to the database, especially if it could do it incrementally. Here's the trace I got from the error:

I'm a bit hesitant to produce the whole backtrace to avoid unintentionally leaking sensitive data but I can try to get any info that would help with debugging. Thanks!

**Comment by tarsius** [comment]
Check if the kludge in #294 fixes it for you.

**Comment by tarsius** [comment]
Closing in favor of #294 and #489.
