### ISSUE TITLE
Support for inserting videos in PRs and issues (e.g. in Gitlab)

### ISSUE THREAD

**Issue by dusek** [magit/forge#49]
Analogically to inserting images in #41, it is sometimes useful to insert videos in a comment in a PR or issue (typically a screencast of a software's buggy behavior or behavior after a proposed code change).

Github [does not support it at all](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (I also tested it by pasting an `.mp4` video file into comment field - I got a warning the file type is not supported and that only those listed in the link provided are supported).

Gitlab supports inserting videos similarly like images (i.e. attach a video file from using the "Attach a file" linke, it takes a few seconds to upload and the appropriate URL is then immediately inserted; the video is then displayed inline in the result (Preview tab or after sending the comment) because Gitlab exports it to HTML as a `video` element). The only difference really is that pasting an image is possible also by pasting the image file directly from clipboard; for video, that method just inserts the filename as plain text, and the "Attach a file" method above needs to be used to actually insert a video.

**Comment by tarsius** [comment]
> it is sometimes useful to insert videos in a comment 

With an emphasis on *sometimes*. More often not, it is rather annoying and a proper description would have been more useful than forcing the maintainer to watch a video over and over again until they see the thing the user wanted them to see. ;-)

I don't think we need a separate issue for this. I assume this works pretty much exactly as for images, i.e. a video is just a "moving picture".
