### ISSUE TITLE
HTTP Error: 400, "Bad Request" updated_after is invalid

### ISSUE THREAD

**Issue by intpl** [magit/forge#491]
Hi! I get this error when trying to do an initial `forge-pull`.

```
error in process filter: ghub--errorback: HTTP Error: 400, "Bad Request", "/api/v4/projects/my-site/issues?per_page=100&order_by=updated_at&updated_after=false", ((error . "updated_after is invalid"))
error in process filter: HTTP Error: 400, "Bad Request", "/api/v4/projects/my-site/issues?per_page=100&order_by=updated_at&updated_after=false", ((error . "updated_after is invalid"))
```

According to specs this should be a datetime, not a boolean: https://docs.gitlab.com/ee/api/issues.html

**Comment by tarsius** [comment]
Try updating to after 0ca0ca8ac55f46f48a27cb8a690078380f6d5703.

**Comment by intpl** [comment]
hi, thank you for the reply. it worked, but now i get this error when i try to see my gitlab stuff:
![image](https://user-images.githubusercontent.com/8034626/166111364-182577a3-6ada-402a-b32a-59adee3afb3d.png)

i'll create a new issue for that
