### ISSUE TITLE
forge browse issue and MR for self hosted http gitlab

### ISSUE THREAD

**Issue by ctaque** [magit/forge#501]
Hi,
I installed forge and configured it for a self hosted gitlab without https. (https://github.com/magit/forge/wiki/Tips-and-Tricks#accessing-private-gitlab-instances-via-http)
I can pull topics and create issues.
I expected to browse issues and merge requests via http,
But when browsing an issue or MR it opens a browser with a **https** url.

**Comment by ctaque** [comment]
Would it be easy to add the topic url to its buffer to use `browse-url-at-point` instead of `forge-browse-topic` as a workaround ?

**Comment by tarsius** [comment]
> But when browsing an issue or MR it opens a browser with a https url.

I don't see how that can happen. I quickly followed the stack from `forge-browse-issue` to `forge--format`, which, in this case, uses the format string stored in the `issue-url-format` slot. For the class you copied, the value is `"http://%h/%o/%n/issues/%i"`.

I suggest you add debug statements along the way, or use a debugger, to find out where things start to have unexpected values.
