### ISSUE TITLE
Got error while creating a merge request

### ISSUE THREAD

**Issue by ctaque** [magit/forge#502]
I'm trying to create a pull request with `forge-create-pull-req`
again with self hosted gitlab, http

The pull req is not created, I get this error instead :  

```progn: Cannot determine forge repository.  No url configured for ".".
See https://magit.vc/manual/forge/Repository-Detection.html.
```

I read the documentation "Repository Detection" and read that I need to set the git variable forge.remote, which is created :  
`git config --list` from my repository :  
```forge.remote=origin```

**Comment by tarsius** [comment]
The full error message is being created using:

```elisp
      (message "Ignored forge.remote=%s; no such remote.\nSee %s." config
               "https://magit.vc/manual/forge/Repository-Detection.html"))
```

Check if the value filled in for the first `%s` is really `origin`. Does that remote really exist?
