### ISSUE TITLE
External dependency `sqlite3` for `forge--db-dump` not documented

### ISSUE THREAD

**Issue by realcomplex** [magit/forge#505]
This is somewhere between a bug and a documentation issue; hopefully I didn't miss anything obvious.

The `forge--db-dump` function (and the `forge--db-restore` for that matter) depend on the external program `sqlite3` (line 526 in `forge-db.el`: `(call-process "sqlite3" ...)`). This obviously fails when `sqlite3` is not found / installed. That happened to me when the database schema was updated and I answered "yes" to backing up the database before updating the schema (`forge--db-maybe-update`).

To a dummy like me it wasn't very obvious what happened at first. I got a "no such file or directory" type error but at first I thought it might concern some emacs package dependency I was missing or a faulty installation, and I went digging in my emacs configuration. Only later after looking at the source code did I figure out that I was simply missing the external dependency.

To make a long story short, maybe it would be an idea to:
- Give a more helpful error message when the "sqlite3" program is not found, OR (inclusive),
- Document the external dependency in the forge manual.

Thanks for the great package!

**Comment by tarsius** [comment]
Thanks for the report!
