### ISSUE TITLE
Checkout a PR branch without resetting anything

### ISSUE THREAD

**Issue by DamienCassou** [magit/forge#518]
### Discussed in https://github.com/magit/forge/discussions/511

<div type='discussions-op-text'>

<sup>Originally posted by **DamienCassou** August 19, 2022</sup>
I would like to be able to checkout the already existing local branch corresponding to the PR at point in magit-status. Currently, <key>b f</key> (`M-x forge-checkout-pullreq`) also resets the branch and I don't want that.

Said differently, I would like the same as <key>b b</key> (`M-x magit-checkout`) but with a list of PRs (and the PR at point by default) instead of a list of branches.</div>

**Comment by sellout** [comment]
Just for clarity, would this add a fourth option to
```
A branch named "my-fix" already exists.

⋮

  [r]eset existing "my-fix" branch
  [c]reate new "pr-1234" branch instead
  [a]bort
```
something like `[u]se existing "my-fix" branch`?

Because that is a feature I would love.

**Comment by DamienCassou** [comment]
> Just for clarity, would this add a fourth option to

The [PR I sent](https://github.com/magit/forge/pull/519) avoids this choice and directly checks out the existing branch.

**Comment by DamienCassou** [comment]
Thank you very much @tarsius!
