### ISSUE TITLE
Cannot Add Multiple Labels to MR

### ISSUE THREAD

**Issue by stevemolitor** [magit/forge#520]
I cannot add multiple labels to a GitLab merge request using Forge. 

While viewing a MR in Forge, I can use "C-c C-e" on the label field to get a dropdown of available labels, and can select _one_. Selecting one label clears out any other labels previously selected. I can't figure out a way to add multiple labels.

Using quick actions is a workaround, but it'd be nice to be able to pick from Forge's label completion dropdown to avoid typos.

**Comment by tarsius** [comment]
You can insert multiple labels, separated by commas.
