### ISSUE TITLE
New common mistake: gitlab host for unix password-store

### ISSUE THREAD

**Issue by gabor-braun** [magit/forge#529]
I had troubles setting up forge to use Unix password store for a private GitLab instance.  What was unclear to me is to where to put the path (e.g., `/api/v4`) of the gitlab host in the password store.  What works for me: omitting it altogether.

Please add this to the page on common mistakes.  Perhaps also to the documentation of `ghub`.

Just to clarify, a working example (with private information replaced):

Init file:
```emacs-lisp
(require 'auth-source-pass)
(require 'forge

(setq auth-sources '(password-store))

(push
   '("git.example.com" "git.example.com/api/v4" "git.example.com" forge-gitlab-repository)
   forge-alist)
```

`~/.password-store/git.example.com/ziggy^forge.gpg` decrypted:
```
012345abcdef...
```

This is the analogue an  example form `ghub`'s documetation,
except that `/api/v4` is omitted.  It only appears in `forge-alist`.

Init file:
```emacs-lisp
  (setq auth-sources '("~/.authinfo"))
```

~/.authinfo:
```
 machine gitlab.com/api/v4 login ziggy^forge password 012345abcdef...
```

**Comment by tarsius** [comment]
I've added a brief note. Note that anyone can edit the wiki, so feel free to improve the entry.
