### ISSUE TITLE
Pull request created on wrong remote

### ISSUE THREAD

**Issue by dusek** [magit/forge#54]
# Steps to reproduce
1. In magit status buffer: `' p`
2. Source branch: confirm `origin/a11y-sign-in-up` (pre-selected)
3. Target branch: confirm `upstream/master` (pre-selected)
4. Select pull-request template: confirm whatever option (e.g. "Change documentation location")
5. Paste in my prepared Merge request (MR) description
6. Submit (`C-c C-c`)

# Expected results
MR is created on the `upstream` repo (i.e. [`gitlab-org/gitlab-ce`](https://gitlab.com/gitlab-org/gitlab-ce) repo on `gitlab.com`).

# Actual results
MR is [created](https://gitlab.com/dusek/gitlab-ce/merge_requests/1) on the `origin` (i.e. my fork, i.e. [`dusek/gitlab-ce`](https://gitlab.com/dusek/gitlab-ce) on `gitlab.com`) repo.

# Configuration
```
$ git remote -v
origin	git@gitlab.com:dusek/gitlab-ce.git (fetch)
origin	git@gitlab.com:dusek/gitlab-ce.git (push)
upstream	https://gitlab.com/gitlab-org/gitlab-ce.git (fetch)
upstream	none (push)
```

# Notes
Since the "target branch" is on "upstream", I would expect `forge` to deduce the MR should be created w.r.t. the `gitlab-org/gitlab-ce` repository (as is specified as `fetch` for `upstream` in `git remove -v` above). I never needed to set the `push` for `upstream` before (and I do not know if it would fix the issue) – fetching changes from upstream and rebasing my feature branches on top that and pushing them to my fork (origin) works fine in the above setup.

**Comment by tarsius** [comment]
Were you using a version of Forge that included 6705b962e26ba22279cd464666f6a2c4ccb03734 when that happened?

**Comment by dusek** [comment]
I think so. I had to update `forge` since I was first getting `forge-post-submit: forge--submit-post-function is nil` as Actual results (after `C-c C-c`). So I updated forge (`package-list`, `U`, `x`), did `load-file ~/.emacs.d/init.el` (my `init.el` contains a line saying `(require 'forge)`), and then did Steps to reproduce again, and this reported issue happened. My `forge` version is now reported in the `*packages*` buffer as `20181229.1644`. I checked in my `.emacs.d/elpa/forge-20181229.1644/forge-github.el` that the 3 changes from 6705b96 are all present.

Btw. the changes in that commit affect only something specific to Github (I presume from the filename, `forge-github.el`, mentioning Github specifically), but this issue concerns submit a PR (MR) to Gitlab (from Gitlab-hosted fork), so just pointing this out in case there is some confusion.

**Comment by tarsius** [comment]
I tried reproducing it on Gitlab but the correct forge was picked. Can you reproduce this when the upstream is named `origin`, i.e. when `forge.remote` isn't set?

**Comment by tarsius** [comment]
> 3. Target branch: confirm `upstream/master` (pre-selected)

Are you sure?  Due to incomplete upstream configuration the default was "origin/master" (despite the upstream being named "upstream") when I was testing and I almost didn't notice.  

By the way, I investigated why the default was "origin/master" and the reason was that that is the final fallback value used by `forge-create-pullreq`.  I could replace the hardcoded "origin" with the value of `forge.remote`, but don't think it is worth the complication.

While I see no need to do it, I think that naming the upstream repository something other than "origin" is reasonable.  But I don't see how naming your fork "origin" makes sense and don't want to add extra code to support that.  If the convention is to name the upstream "origin", then naming *another* remote "origin" *instead* is just asking for problems.

**Comment by dusek** [comment]
> > 1. Target branch: confirm `upstream/master` (pre-selected)
> 
> Are you sure?

Yes 😄 :

![magit_forge_54](https://user-images.githubusercontent.com/41975/50550078-82f98200-0c69-11e9-840d-ccc31ad9f99c.gif)

> While I see no need to do it, I think that naming the upstream repository something other than "origin" is reasonable. But I don't see how naming your fork "origin" makes sense and don't want to add extra code to support that. If the convention is to name the upstream "origin", then naming _another_ remote "origin" _instead_ is just asking for problems.

I tend to always use remote named `origin` for the upstream repo (because that is the repo I clone at first), and then use `dusek` as the name of the remote for my fork (if I actually get to forking (contributing) at all). However here I followed GitLab's guidance in [Option 1: Develop in a fork](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/set-up-gdk.md#option-1-develop-in-a-fork). At least I understood that option is for me, i.e. for the typical contributor scenario for merging my feature branch in my fork to the upstream repo (especially since I am not someone having write access to GitLab's upstream repos).

Having studied the [`set-gitlab-upstream` script](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/support/set-gitlab-upstream) and especially [the critical 2 lines during the `gdk update` command](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/Makefile#L244-245), I think that as far as GitLab's development setup is concerned, I can just rename my remotes the way I wish (the names `origin` or `upstream` are not relied upon anywhere during the `gdk update`), the only important thing is that the fetch remote for the `master` branch to be set to point to the upstream repository so that plain `git pull --ff-only` while on `master` updates `master` from the upstream repository. So I have just renamed `origin` to `dusek`, and `upstream` to `origin`.

> Can you reproduce this when the upstream is named `origin`, i.e. when `forge.remote` isn't set?

Is there a way to test this without actually submitting a PR/MR (i.e. put some logging somewhere in place of the actual act of submission)? I would like to test with the actual repos/remotes involved, but at the same time would like to avoid polluting the upstream repo with testing MRs (and I do not have some another MR lined up ready to actually submit).

P.S.: Now doing `F y` after the rename, and hitting another bug, so please brace yourself for another report from me 😄.

**Comment by tarsius** [comment]
> Is there a way to test this without actually submitting a PR/MR

``` diff
diff --git a/lisp/forge-gitlab.el b/lisp/forge-gitlab.el
index fb133af..859c624 100644
--- a/lisp/forge-gitlab.el
+++ b/lisp/forge-gitlab.el
@@ -415,16 +415,13 @@ (cl-defmethod forge--submit-create-pullreq ((_ forge-gitlab-repository) base-rep
                  (`(,head-remote . ,head-branch)
                   (magit-split-branch-name forge--buffer-head-branch))
                  (head-repo (forge-get-repository 'stub head-remote)))
-      (forge--glab-post head-repo "/projects/:project/merge_requests"
-        `(,@(and (not (equal head-remote base-remote))
-                 `((target_project_id . ,(oref base-repo forge-id))))
-          (target_branch . ,base-branch)
-          (source_branch . ,head-branch)
-          (title         . , .title)
-          (description   . , .body)
-          (allow_collaboration . t))
-        :callback  (forge--post-submit-callback)
-        :errorback (forge--post-submit-errorback)))))
+      (message "base: %s/%s %s/%s" base-remote base-branch
+               (oref base-repo owner)
+               (oref base-repo name))
+      (message "head: %s/%s %s/%s" head-remote head-branch
+               (oref head-repo owner)
+               (oref head-repo name))
+      )))
 
 (cl-defmethod forge--submit-create-issue ((_ forge-gitlab-repository) repo)
   (let-alist (forge--topic-parse-buffer)
```

>     (forge--glab-post head-repo "/projects/:project/merge_requests"

I find it weird that with Gitlab one has to create a pr "*from* the source/head repository".  With Github (and I think the other forges) one creates a pr "*into* the target/base repository".  Gitlab's way doesn't make sense and isn't documented explicitly, but because there is a `target_project_id` parameter it seems obvious that the resource must contain the source repository/project.
