### ISSUE TITLE
Tree-sitter hooks for markdown mode cause errors when creating an issue

### ISSUE THREAD

**Issue by mslw** [magit/forge#541]
I need to preface the issue by saying that I started using Forge recently, and my first impressions are really nice! I'm not 100% sure if this issue really falls under a bug report here (because it's an interaction with the tree-sitter package), so feel free to redirect me elsewhere.

I am using Emacs 27.1 (on Debian) with tree-sitter package. This is my tree-sitter configuration from `init.el`:
``` elisp
(use-package tree-sitter
  :hook ((python-mode . tree-sitter-mode)
	 (python-mode . tree-sitter-hl-mode)
	 (markdown-mode . tree-sitter-mode)
	 (markdown-mode . tree-sitter-hl-mode)))
```

When I try to create a new issue in a project using Forge (open Magit status buffer `C-x g`, create new issue with Forge `N`, `c i`), I get the following error:

```
Debugger entered--Lisp error: (error "No language registered for major mode ‘forge-post-...")
  signal(error ("No language registered for major mode ‘forge-post-..."))
  error("No language registered for major mode `%s'" forge-post-mode)
  tree-sitter--setup()
  tree-sitter-mode()
  tree-sitter-hl-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook markdown-mode-hook gfm-mode-hook forge-post-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook markdown-mode-hook gfm-mode-hook forge-post-mode-hook))
  run-mode-hooks(forge-post-mode-hook)
  forge-post-mode()
  forge--prepare-post-buffer("new-issue" "Create new issue on datalad/datalad-redcap")
  forge-create-issue()
  funcall-interactively(forge-create-issue)
  call-interactively(forge-create-issue nil nil)
  command-execute(forge-create-issue)
```

A `new-issue` buffer still gets created, but it is empty (i.e. no "Create new issue" on top and no `#` on first line) and I'm not automatically placed there (I can navigate to it from the buffer list).

When I remove the markdown mode hooks mentioned above, everything works as expected, and I can create a new issue with Forge.

**Comment by tarsius** [comment]
`forge-post-mode` derives from `gfs-mode`, which derives from `markdown-mode`. Apparently that is enough for `tree-sitter` to decide it has to enable itself, but then that fails because the functions to do so are not on `forge-post-mode-hook`. That shouldn't matter because hooks of parent modes are also run, but maybe `tree-sitter` also checks whether the expected functions are members of the most local mode hook for some reason.

That's just speculation, but it is worth trying to add these functions to `forge-post-mode-hook`. If that doesn't work, you should have better luck asking on `tree-sitter`'s issue tracker.

**Comment by mslw** [comment]
Thanks for speculating! FTR, I get the same error when I add the function to `forge-post-mode-hook`. But reading your comment and searching a bit more made me realize that when a hook function is run (and it is in this case, because of parent mode), `tree-sitter` looks up the required language in the variable `tree-sitter-major-mode-language-alist` (defined in `tree-sitter.el`) based on the *current major mode*.

So it's up to `tree-sitter` to decide which major modes are supported out of the box - and for me the solution is to edit this variable after loading `tree-sitter` - with `use-package` this did the trick:

```
(use-package tree-sitter
  :hook ((markdown-mode . tree-sitter-mode)
	 (markdown-mode . tree-sitter-hl-mode))
  :config
  (push '(forge-post-mode . markdown) tree-sitter-major-mode-language-alist)
  )
```

Thanks again - I'm closing the issue.
