### ISSUE TITLE
Fails to checkout merged branch. `fatal: 'origin/' is not a valid branch name.`

### ISSUE THREAD

**Issue by flamingbear** [magit/forge#56]
I've seen two different behaviors when I try to `checkout pull-request`.
Sometimes it succeeds, sometimes it doesn't.  When it doesn't it's always tells me.
`fatal: 'origin/' is not a valid branch name`

If I set debug-on-error to t, I get the following output when I try to check out a "bad branch"

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`heads/\\(.+\\)" nil)
  magit-checkout(nil)
  forge-checkout-pullreq(#<forge-pullreq forge-pullreq>)
  funcall-interactively(forge-checkout-pullreq #<forge-pullreq forge-pullreq>)
  call-interactively(forge-checkout-pullreq)
  magit-invoke-popup-action(121)
  funcall-interactively(magit-invoke-popup-action 121)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

A particular PR that fails is https://github.com/idl-coyote/coyote/pull/23 

But https://github.com/idl-coyote/coyote/pull/20 works as expected from the documentation.

this is with `forge-20181230.1810` and `magit-20181229.1434` and ` magit-popup-20181204.2031` on 
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30

**Comment by flamingbear** [comment]
as a note, the closed prs on my config repo also show the same behavior.
Bad:
https://github.com/flamingbear/emacs-config/pull/2
and
https://github.com/flamingbear/emacs-config/pull/1

Fine:
https://github.com/flamingbear/emacs-config/pull/3

**Comment by flamingbear** [comment]
Thanks, this is obviously not a high priority for me, I was just letting you know I found this while test driving the new features.

Also, an additional thanks, I ❤️ your software.

**Comment by tarsius** [comment]
This should work now.
