### ISSUE TITLE
Notifications list doesn't match github notifications

### ISSUE THREAD

**Issue by Lenbok** [magit/forge#578]
I am a fairly new user of forge. I fetched notifications `N f n` (I had probably also done this in the past) followed by list notifications `N l n`, and am presented with a list of about thirty repositories containing about fourty notifications. However, when I visit my github notifications page, I see two notifications, one which is read and one which is unread.

I would expect that the notifications list would match what is visible on the github notifications page, so there must be some bug here. If these extra notifications are in some sense "old", how can I remove them?

**Comment by tarsius** [comment]
I have changed it to only pull (and list) "unseen" notifications (where "unseen" is defined as "unseen in a browser").

> I would expect that the notifications list would match what is visible on the github notifications page, so there must be some bug here.

So would I. The bug is that the respective API endpoint sucks. See the commit message for details.

**Comment by Lenbok** [comment]
Thanks, I'll take a look at that too!
