### ISSUE TITLE
Disable adding refs/pullreqs/*?

### ISSUE THREAD

**Issue by antifuchs** [magit/forge#59]
Me again with the gigantic monorepo problems from #57 (-:

Those 120k pull requests I mentioned are also present as refs, so I'd like to disable fetching them: If the `fetch = +refs/pull/*/head:refs/pullreqs/*` config entry is present, every fetch takes tens of minutes (and the initial fetch spams a lot of lines in the `magit-process` buffer, slowing the fetch down even more).

I'd like to disable that config setting for now, but forge `F y` seems to keep adding it back. Can we get a variable to disable that? (:

**Comment by antifuchs** [comment]
I've also been thinking a little about how to do this in a world where only certain PRs are relevant: Maybe forge can create `fetch` entries for PRs that it finds updated, and remove them when the PR closes?

**Comment by tarsius** [comment]
I've added the option `forge-add-pullreq-refspec` for this.

**Comment by tarsius** [comment]
Setting it locally is how I would use this variable too.

**Comment by Atemu** [comment]
> I don't think so but if, after reading about `<refspec>` in the `git-fetch` manpage and/or elsewhere, you come to a different conclusion, then let me know.

I meant for forge to not configure git to fetch these refspecs in the first place.

Now that I think about it, changing the git configuration in this way when merely opening forge is surprising behaviour in and of itself and should probably not work like that by default in any case.

> Please open an `idea` discussion. I cannot deal with this right now and without such a reminder I will forget about it.

Totally understandable; I'll open an `idea` discussion. Thanks for your work :)
