### ISSUE TITLE
SQLite syncs very often while fetching large data sets

### ISSUE THREAD

**Issue by alphapapa** [magit/forge#6]
Hi Jonas,

Congratulations on, and thanks very much for, releasing Forge!

Something I noticed just now: The first operation I tried is fetching GitHub notifications.  There are...a lot of unread ones in my account, from having clicked "Watch" on way too many repos, before I realized how many notifications that would add up to.  Of course, on the Web UI, it doesn't matter much, but since Forge is fetching *all* of them...

I'm noticing an interesting pattern in my disk access (HDD not SSD): lots of little fsyncs as the SQLite database grows by a few KB at a time.  The fetch operation has been going on for over 5 minutes now, maybe 10, and the database file is only 176 KB.  I hear the disk head making lots of little seeks at intervals of 5-10 seconds--I'm guessing it's as Emacs gets the next batch of notifications.

It's not really a problem, but it is a lot of unnecessary fsyncing, so you might consider using a single transaction and only fsyncing at the end (if that's possible with emacsql).

Keep up the great work!

**Comment by alphapapa** [comment]
Update: I'm not sure if the SQLite fsyncing issue is causing this, but the initial pull for my GitHub account is simply taking far too long.  It's been over 40 minutes now, and the SQLite file is only 608 KB.  If I copy the file and look at it, here are some stats about tables:
```fish
$ cp forge-database.sqlite /tmp/test.sqlite; and for t in repository pullreq_post issue_post pullreq notification; echo $t (sqlite3 /tmp/test.sqlite "SELECT COUNT(id) FROM $t;"); end

repository 212
pullreq_post 49
issue_post 267
pullreq 16
notification 0
```
I still hear the disk seeking, and I can see the I/O stats in `atop` showing mild disk writing.  Worst, though, is that Emacs is effectively completely frozen.  I can sometimes see messages in the echo area from timers firing, but it's not responsive to keyboard input, except `C-g`.

So I guess if I left Emacs for enough hours, it would finish, but I don't think it's practical for me to do that now.

Not a complaint, just FYI.  :)  Let me know if I can help.

**Comment by alphapapa** [comment]
A well-deserved rest, my friend.  :)

**Comment by tarsius** [comment]
The numbers are certainly odd.  I would expect: `repositories <= 2 * pullreq + issue`.

Anyway, for the time being `forge-pull` no longer fetches notifications.

**Comment by tarsius** [comment]
I made some changes that should help at least knowing how much is being fetched. Please update and run `forge-pull-notifications`. Then post the last few lines from `*Messages*`.

**Comment by alphapapa** [comment]
Thanks, unfortunately it's still taking a very long time to fetch notifications.  After downloading data over the network, the SQL inserts begin, and the hard disk head churns constantly, with the `emacssql-sqlite` process keeping one CPU core in I/O-wait, while writing a few hundred kB/sec the whole time.  When I finally `C-g` to stop it, so I can use Emacs again, the only line in the messages buffer from it is `Pulling notifications...`.  Maybe when I have more time I can let it finish the process in the background.

So there seem to be two issues here:

1.  The SQLite process seems to fsync lots of small writes to the disk, causing the disk to churn.
2.  Possibly exacerbated by that, with a large number of notifications, the notification pulling takes a very long time.

**Comment by alphapapa** [comment]
I haven't used `closql` or `emacsql` much, so forgive me if this is just noise, but maybe part of the problem is that, while `forge--pull-notifications` wraps the whole operation in a transaction, for each notification it seems to call `closql-insert`, which also calls `emacsql-with-transaction`.

**Comment by alphapapa** [comment]
I discovered that the SQLite file was writing in journaled mode rather than WAL mode.  I ran this:
```el
(emacsql (forge-db) "PRAGMA journal_mode=WAL")
```
Then I ran `forge-pull-notifications` again.  Watching `~/.emacs.d`, I see the `-shm` and `-wal` SQLite files instead of the `journal` file that was there before.

After pulling the GraphQL data over the network, the WAL file grew rapidly (relative to journaled mode) to 4 MB.  Now the `emacsql-sqlite` process continues churning , with the `.sqlite` file very slowly growing, now at 200 KB, after over 5 minutes have passed, and Emacs is still blocked on `Pulling notifications...`.

So WAL improves performance a lot, but I'm guessing that after insertion, it's doing something else that's very slow...?

Thanks.

**Comment by alphapapa** [comment]
A bit more investigation: I did this to dump SQL queries to disk as they happen:
```el
(defvar forge-sql-debug-file "/tmp/forge-db.sql")

(defun forge-sql (sql &rest args)
  (with-temp-buffer
    (prin1 sql (current-buffer))
    (when args
      (insert "\n")
      (prin1 args (current-buffer)))
    (insert "\n\n")
    (let ((write-region-inhibit-fsync t))
      (write-region nil nil forge-sql-debug-file
                    'append)))
  (if (stringp sql)
      (emacsql (forge-db) (apply #'format sql args))
    (apply #'emacsql (forge-db) sql args)))
```
Now after fetching the data over the network, the first queries I see are a lot of repeated SELECTs, like:
```el
[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "jwiegley" "use-package")

[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "joaotavora" "eglot")

[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "melpa" "melpa")

[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "melpa" "melpa")

[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "Wilfred" "remacs")

[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "hlissner" "doom-emacs")

[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "hlissner" "doom-emacs")

[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "hlissner" "doom-emacs")
```

**Comment by alphapapa** [comment]
Another data point, in case it helps.  (Assuming that this is the same issue or closely related.)

Just now, I did this:

1.  `magit-status` in a project repo.  I think I had previously fetched topics in that repo, but the `forge` topic sections were not yet displayed in the `magit-status` buffer.
2.  `' f f` to fetch all topics.
3.  Checkout pull request, merge to master, push to master.
4.  After the `git push` process finished, Emacs did not unblock, and the disk thrashed heavily for a few minutes.  Looking at `atop`, I saw the kernel I/O thread for the disk writing at several MB/sec while the `emacs-sqlite` process was intermittently writing a few hundred KB/sec.  During this time, I frequently saw that the kernel thread would write over 40 MB in a 2-second polling period.

Usually when this happens, I use `C-g` to make Emacs responsive again.  This time I decided to let it finish to see how long it would take.

This pattern seems to happen with many Magit operations after I display topics in a `magit-status` buffer.  If I kill and recreate the buffer without displaying topics, it doesn't seem to happen, so it only seems to happen when `forge` sections are being displayed.  

I wonder, Jonas, by any chance, do you develop primarily on a machine with an SSD?   If so, that might explain why this issue seems less noticeable.

**Comment by tarsius** [comment]
> And it seems strange  that the `emacs-sqlite` process is writing data to the disk when I have not run a command to update `forge`.  AFAIK `forge` only updates its issues when the commands are explicitly run.  So why would the database be written to at any other time?

Yes, that's weird.

I am afraid I don't have time to investigate this any time soon. I suspect it is an issue in `emacsql`. If you or someone else could investigate this, I would appreciate that very much.

> In fact, when `magit-filenotify-mode` is enabled

I recommend you keep that disabled. I don't remember the details but I consider it unnecessary and it causes issues.

> I wonder, Jonas, by any chance, do you develop primarily on a machine with an SSD?

Yes of course.

**Comment by alphapapa** [comment]
I'm looking into this a little bit, and I'm not seeing anything obvious.  I'm not seeing any writes to the database during refreshes of the status buffer.  But I'll keep watching the SQL log while I continue using Magit and Forge tonight.

It might be that `magit-filenotify-mode` was causing excessive status buffer refreshes during the git pre-push hook's test run.  It seems that each time the status buffer is refreshed, there are 5 SELECT queries run:

```
2020-01-26 22:30:59 -0600
[:select * :from repository :where (and (= forge $s1) (= owner $s2) (= name $s3))]
("github.com" "alphapapa" "org-ql")

2020-01-26 22:30:59 -0600
[:select * :from $s1 :where (and (= repository $s2) (notnull unread-p))]
(pullreq "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTk5NDU5NDI2")

2020-01-26 22:30:59 -0600
[:select * :from $s1 :where (and (= repository $s2) (isnull closed)) :order-by [(desc updated)] :limit $s3]
(pullreq "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTk5NDU5NDI2" 60)

2020-01-26 22:30:59 -0600
[:select * :from $s1 :where (and (= repository $s2) (notnull unread-p))]
(issue "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTk5NDU5NDI2")

2020-01-26 22:30:59 -0600
[:select * :from $s1 :where (and (= repository $s2) (isnull closed)) :order-by [(desc updated)] :limit $s3]
(issue "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTk5NDU5NDI2" 60)
```
That's one for the repo itself, two for PRs, and two for issues, each with different criteria.

That doesn't seem entirely unreasonable.  However, this does seem like a fairly good candidate for caching.  Do we expect Forge to be the only writer to its database while Emacs is running?  If so, maybe the results of these queries could be cached while the database has not been written to.  What do you think?

Also I discovered another SQLite PRAGMA that seems relevant: synchronous.  I ran these two queries before testing this time, and it seems to reduce disk activity and improve performance:

```el
(emacsql (forge-db) "PRAGMA journal_mode=WAL")
(emacsql (forge-db) "PRAGMA synchronous=OFF")
```

Am I correct in my understanding that the Forge database is essentially a read-only local cache?  If so, could we assume that there are no potential data-loss issues and set these two pragmas and prevent fsync calls?  That seems to be the ultimate issue, that synchronous queries and fsync are causing SQLite and Forge to block Emacs unnecessarily.

Thanks.

**Comment by alphapapa** [comment]
Well, I just realized that INSERTs and UPDATEs are not being shown in my SQL log, which only modifies `forge-sql`, which is apparently not used for INSERTs.

Another potential issue I just noticed is that it seems that a new transaction is used for every topic insert, like:
```el
(cl-defmethod forge--update-issues ((repo forge-github-repository) data bump)
  (emacsql-with-transaction (forge-db)
    (mapc (lambda (e) (forge--update-issue repo e bump)) data)))

(cl-defmethod forge--update-issue ((repo forge-github-repository) data bump)
  (emacsql-with-transaction (forge-db)
    (let-alist data ...
```
I'm guessing that a single transaction should be used for an entire `forge-pull` call, which would probably significantly improve performance.  As it is, with default PRAGMAs, SQLite is fsyncing each topic insert separately, which means many tiny writes to the disk blocking SQLite and Emacs.

**Comment by tarsius** [comment]
I have implemented two new backends, both in https://github.com/emacscollective/emacsql-sqlite-builtin and I expect that using either of those fixes this issue. Forge doesn't force users to use one of those backends and I'll probably keep Emacsql's default SQLite backend as the default backend for this package for the foreseeable future. But I have been using these two backends for quite some time without any problems whatsoever, so I no longer consider them experimental I can recommend their use.

Let me know if you still experience this issue even when using one of the new backends.
