### ISSUE TITLE
Maybe support Gerrit

### ISSUE THREAD

**Issue by aspiers** [magit/forge#60]
Forge is AWESOME!  Thank you so much :-)

Are there any plans for adding support for Gerrit at any point?  Even if not yet, is it likely to be technically feasible?

**Comment by tarsius** [comment]
Are you aware of a public demo instance that I could play with?

I had a quick look at the [API documentation](https://gerrit-documentation.storage.googleapis.com/Documentation/2.16.2/rest-api-projects.html) but didn't see and "list issues/pull-requests of project/repository" or even "list posts on issue/pull-request" end-points. Maybe that stuff is just named differently.

Adding "visit commit/branch/project in a browser" should be trivial to implement (by someone having access to an instance), but if the API does not expose topics, then all the cool stuff cannot be implemented. Doing the former boils down to copying one of the classes defined in `forge-semi.el` and adjusting the various URL formats.

**Comment by vermiculus** [comment]
From what I see, Gerrit is only a code-review provider. I don't think there's any bug tracker or formal concept of a pull request.

Even then, I can't find any information in the linked API docs that would return any sort of review information – looks like it's mostly just information about the history itself along with a few access management tools.

**Comment by aspiers** [comment]
[**@tarsius**](https://github.com/tarsius) commented on [5 Jan 2019, 13:09 GMT](https://github.com/magit/forge/issues/60#issuecomment-451654098 "2019-01-05T13:09:28Z - Replied by Github Reply Comments"):
> Are you aware of a public demo instance that I could play with?

https://android-review.googlesource.com/q/status:open
https://chromium-review.googlesource.com/q/status:open
https://gerrit-review.googlesource.com/
http://gerrithub.io/
https://review.openstack.org/

> I had a quick look at the [API documentation](https://gerrit-documentation.storage.googleapis.com/Documentation/2.16.2/rest-api-projects.html) but didn't see any "list issues/pull-requests of project/repository" or even "list posts on issue/pull-request" end-points. Maybe that stuff is just named differently?

Yes, they are called "reviews" or "changes" not PRs.  In fact that's the first entry in a Rosetta stone I made:

https://ethercalc.openstack.org/github-gerrit

(Please be careful not to edit it accidentally; it's world-writable.)

> Adding "visit commit/branch/project in a browser" should be trivial to implement (by someone having access to an instance), but if the API does not expose topics, then all the cool stuff cannot be implemented.

It does expose topics:

https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#get-topic

but topics mean something different in Gerrit: it's a way of grouping related change reviews together.

**Comment by aspiers** [comment]
[**@vermiculus**](https://github.com/vermiculus) commented on [5 Jan 2019, 14:11 GMT](https://github.com/magit/forge/issues/60#issuecomment-451658893 "2019-01-05T14:11:00Z - Replied by Github Reply Comments"):
> From what I see, Gerrit is only a code-review provider.

Yes, that's its main function, but as a side-effect it hosts git repositories.

> I don't think there's any bug tracker

Correct.

> or formal concept of a pull request.

Incorrect; each change review is the equivalent of a PR.
 
> Even then, I can't find any information in the linked API docs that would return any sort of review information – looks like it's mostly just information about the history itself along with a few access management tools.

I guess you looked in the wrong place, because it's all there, e.g.

https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-change-comments

**Comment by tarsius** [comment]
While I did implement some new feature today, the current focus is fixing bugs.  Once I resume adding support for additional forges, the focus will be on Gitea and Gogs.  Only once that is done will I consider adding support for Gerrit.

Of course if someone else wants to add support for Gerrit, then I would welcome that.

**Comment by tarsius** [comment]
There's also [`magit-gerrit`](https://github.com/terranpro/magit-gerrit), but that hasn't seen a commit in three years, so it probably will need some work to get it to work with a contemporary Magit.

**Comment by aspiers** [comment]
[**@tarsius**](https://github.com/tarsius) commented on [April 2, 2019 1:37 PM](https://github.com/magit/forge/issues/60#issuecomment-478976175 "2019-04-02T12:37:41Z - Replied by Github Reply Comments"):
> There's also [`magit-gerrit`](https://github.com/terranpro/magit-gerrit), but that hasn't seen a commit in three years, so it probably will need some work to get it to play well with a contemporary Magit.

Yeah, I just did [some research on that](https://github.com/terranpro/magit-gerrit/issues/59#issuecomment-492205420) and filed some new issues:

- terranpro/magit-gerrit#62 (Now needs explicit dependency on magit-popup)
- somtin/magit-gerrit#1 (Now needs explicit dependency on magit-popup)

**Comment by dakra** [comment]
I use the fork of @darcylee at https://github.com/darcylee/magit-gerrit which uses transient instead of magit-popup and has also the other patches applied to make it work with newer magit versions.

**Comment by aspiers** [comment]
OK thanks, I've just added that: https://github.com/terranpro/magit-gerrit/issues/59#issuecomment-492412691.

**Comment by tarsius** [comment]
I don't think I will do this anytime soon. Maybe in a far away future.

**Comment by snogge** [comment]
There is also gerrithub.io, a gerrit front end to github.  I've not used it myself, but it seems up to date.

**Comment by aspiers** [comment]
GerritHub is just an uptodate deployment of Gerrit with some GitHub plugins enabled on the backend.  It's maintained by GerritForge, who are some of the leading contributors to Gerrit.  None of this is particularly relevant to this issue though.

IMHO it would be a real shame if magit didn't get good Gerrit support, given that a) [Gerrit is used by many hugely popular projects](https://en.wikipedia.org/wiki/Gerrit_(software)#Notable_users), and b) [Gerrit offers significantly superior code review to both GitHub and GitLab](https://ethercalc.openstack.org/github-gerrit) (and as mentioned above can be used as a code review frontend to GitHub).  But I appreciate that developer resources don't magically appear out of thin air, and it seems @tarsius isn't interested, so we'll have to try to clean up the horrible mess which currently exists with the various magit-gerrit forks.

**Comment by tarsius** [comment]
Resurrecting `magit-gerrit` seems like a good idea and I can help with that.

I have commented on https://github.com/terranpro/magit-gerrit/issues/59.

**Comment by domenzain** [comment]
@terranpro is willing to allow someone else to take over: https://github.com/terranpro/magit-gerrit/issues/59#issuecomment-568459238.
I can help with tests.

**Comment by hexmode** [comment]
I've done some work on terranpro/magit-gerrit#63

**Comment by tarsius** [comment]
I have added [a faq entry](https://github.com/magit/forge/wiki/FAQ#do-you-plan-to-addextend-support-forge-x) about the forges I plan or don't plan to support. Because I do not plan to implement support for this particular forge I am closing this issue. That doesn't mean that you cannot comment here or shouldn't discourage you from contributing support for favorite forge yourself.

**Comment by aspiers** [comment]
Thanks for the update.  That's entirely reasonable IMHO.

BTW for anyone who's never tried Gerrit, I highly recommend giving it a go.  IMHO it's *way* better than GitHub code review, for reasons shown in [the "Rosetta stone" matrix I linked above](https://github.com/magit/forge/issues/60#issuecomment-451662066).  And http://gerrithub.io/ lets you use it on any existing GitHub repo.
