### ISSUE TITLE
declared dependency on yaml 0.5.2

### ISSUE THREAD

**Issue by progfolio** [magit/forge#607]
forge declares a dependency on yaml 0.5.2:

https://github.com/magit/forge/blob/5dcca0e0c0378499b086543be2ec292ddd8beb5b/forge-pkg.el#L14

However it looks like the latest version is 0.5.1:

https://github.com/zkry/yaml.el/blob/fe08b8f5307af1e7b876ece64b7303213f04b63c/yaml.el#L6

Is there another version published elsewhere?

**Comment by tarsius** [comment]
> Is there another version published elsewhere?

The latest tag is v0.5.4:
- https://github.com/zkry/yaml.el/releases/tag/v0.5.4
- https://stable.melpa.org/#/yaml

Since you bring this up, I am guessing that Elpaca only looks at the `[Package-]Version` header. I would like to entourage you to use the latest tag instead (or also). Feel free to lift some code from Package-Build for that.

**Comment by progfolio** [comment]
> I am guessing that Elpaca only looks at the [Package-]Version header.

Currently it ignores it all together.
I'd like to 

> I would like to entourage you to use the latest tag instead (or also). Feel free to lift some code from Package-Build for that.

I think the elisp ecosystem really needs to rethink how this is done.
What's the actual version of a package? The one declared in `*-pkg.el`, the one declared in the main elisp file header, the latest git tag? Then, on top of that we have a bunch of bespoke versioning systems instead of just agreeing to use something like semver (or just a *single* versioning scheme). It's unnecessarily complicated and makes for slower package managers.

I appreciate the pointer and I'll look into working around all of the above.

**Comment by tarsius** [comment]
FYI, I do plan to pickup my work on that front again early next year.
