### ISSUE TITLE
emacsql dependency not satisfiable

### ISSUE THREAD

**Issue by jonathanunderwood** [magit/forge#624]
Using spacemacs I was updating packages which pulled in the latest forge package, which then caused the following problem:

```
An error occurred while installing forge (error: (error Need package ‘emacsql-20240125’, but only 20240124.1601 is available))
```

It seems like `emacsql-20240125` doesn't correspond to a release on melpa?

**Comment by xuan-w** [comment]
Yes, I have the same problem. Just commented on the commit.

**Comment by tarsius** [comment]
Sorry about that. Fixed but it will take a while for it to make it to Melpa.

**Comment by jonathanunderwood** [comment]
@tarsius thank you!
