### ISSUE TITLE
Use default branch from github as default target branch when creating PR

### ISSUE THREAD

**Issue by thomas-riccardi** [magit/forge#63]
When creating a PR on a github project where the default branch is not `master`, forge still suggests `origin/master` by default.

Also, it seems to even hardcode `origin` as remote name: https://github.com/magit/forge/blob/73494b1aed713d4370ce9956e928201e03909c1a/lisp/forge-commands.el#L271

**Comment by tarsius** [comment]
> When creating a PR on a github project where the default branch is not `master`, forge still suggests `origin/master` by default.

It suggests the source's upstream.  That's a reasonable thing to do because even if you are not going to create a pull-request it is still useful to see the commits you have created on your branch, which can be done by setting its upstream.

> Also, it seems to even hardcode `origin` as remote name:

Also see the preceding ten lines.  Only if everything else fails does it fall back to that as the default.

**Comment by thomas-riccardi** [comment]
OK, I have now RTFM (notably https://magit.vc/manual/magit/The-Two-Remotes.html), and discovered `magit-branch-config-popup` (`b C`) (this keybinding could maybe be documented on the previous doc).

Indeed forge behavior seems to be the sane one: use upstream branch.

So it's not really a forge issue anymore. At most forge could use the github default branch if the local branch has no defined upstream.

The real issue is that magit does not set the upstream in simple cases where maybe it could.

Here are 2 simple workflows I use, on a repository where the github default branch is named `stag` (for staging):
## scenario 1
- checkout `stag`, tracking `origin/stag`
- create branch `foo`: `b c RET foo RET` (create and checkout branch starting at stag)
- check branch `foo` config: `b C RET`: no upstream set
```
Configure foo
 d branch.foo.description unset
 u branch.foo.merge       unset
   branch.foo.remote      unset
 r branch.foo.rebase      [true|false|default:false]
 p branch.foo.pushRemote  [origin|remote.pushDefault:origin]
```
Expected result: maybe it would make sense for magit to set the same upstream as the source branch (`stag`): `origin/stag`

## scenario 2
- checkout `stag`, tracking `origin/stag`
- create a new commit
- spin-off a new branch: `b s foo RET`
- create branch `foo`: `b c RET foo RET` (create and checkout branch starting at stag)
- check branch `foo` config: `b C RET`: no upstream set
```
Configure foo
 d branch.foo.description unset
 u branch.foo.merge       unset
   branch.foo.remote      unset
 r branch.foo.rebase      [true|false|default:false]
 p branch.foo.pushRemote  [origin|remote.pushDefault:origin]
```
Expected result: maybe it would make sense for magit to set the same upstream as the source branch (`stag`): `origin/stag`


## meta
Should I move this part of the discussion to https://github.com/magit/magit ?

**Comment by tarsius** [comment]
> - create branch `foo`: `b c RET foo RET` (create and checkout branch starting at stag)

What value do you confirm with the first `RET`. (Please step through this again to make sure.)

**Comment by thomas-riccardi** [comment]
The first `RET` seems to select the first proposition (I use `ido` completion): `stag`.

I also tested by explicitly typing the source branch name `stag`: same result: no upstream is set.

Another test: if I select `origin/stag` on branch creation, it uses it a upstream; but it's not the default selection so I previously never did it.

**Comment by tarsius** [comment]
This is due to an unfortunate default for `branch.autoSetupMerge`.  I think it should default to `always` but it does default to `true`.

> branch.autoSetupMerge
>            Tells git branch and git checkout to set up new branches so that
>            git-pull(1) will appropriately merge from the starting point
>            branch. Note that even if this option is not set, this behavior can
>            be chosen per-branch using the --track and --no-track options. The
>            valid settings are: false — no automatic setup is done; true —
>            automatic setup is done when the starting point is a
>            remote-tracking branch; always —  automatic setup is done when the
>            starting point is either a local branch or remote-tracking branch.
>            This option defaults to true.

**Comment by thomas-riccardi** [comment]
OK, I confirm that my 2 scenarios now work as I expected with `branch.autoSetupMerge = always`.

I'm not sure what magit / forge can do to improve this: 
- maybe more documentation ? 
- maybe forge could use the default github branch if no upstream is defined, but it seems to be a lot of work compared to single global git config to set.

You can close this issue if you think nothing more can be done.

**Comment by tarsius** [comment]
> more documentation

Yeah, that.  And because nobody actually reads that also a blog post "important Git settings for Magit users (and others)".

Leaving this open until I have transferred it to a personal TODO list.

**Comment by thomas-riccardi** [comment]
Thanks for all your work !

**Comment by tarsius** [comment]
I've added this to https://github.com/magit/magit/wiki/Important-Git-settings.
