### ISSUE TITLE
Push local branch during pull request creation

### ISSUE THREAD

**Issue by thomas-riccardi** [magit/forge#64]
I often want to create a PR for a branch I have not yet pushed: the act of pushing the branch and creating a PR for it is a unit for me: I usually don't need to do these two actions separately.

Forge could help me by proposing local branches in the source refs list, and push them automatically on PR creation (maybe by asking on which remote to push, and maybe with which name; probably re-using the branch push sequence).

Currently, as a new forge user, I instinctively go first to the PR creation popup, to find out my branch is not there, then understand I have to manually first push the branch...

**Comment by tarsius** [comment]
> I often want to create a PR for a branch I have not yet pushed: the act of pushing the branch and creating a PR for it is a unit for me: I usually don't need to do these two actions separately.

What do you mean by "I usually don't need to"?  The only way to do that that I can see is to implement it in some tool (like Forge), i.e. *you* would only do one thing but in the background the tool does two things, push and open the pr.  Do you use a another tool that does that for you?

> Forge could help me by proposing local branches in the source refs list, and push them automatically on PR creation (maybe by asking on which remote to push, and maybe with which name; probably re-using the branch push sequence).

Many projects use automated tests that run when a new branch is created or new commits are pushed to an existing branch.  You should check the results of those tests before you open a pull-request, which is only possible if you separate the acts of pushing and pr creation.

----

I do not intend to implement "push+open-pr" as a single command.

**Comment by thomas-riccardi** [comment]
> > I often want to create a PR for a branch I have not yet pushed: the act of pushing the branch and creating a PR for it is a unit for me: I usually don't need to do these two actions separately.
> 
> What do you mean by "I usually don't need to"? 

I mean that most of the time I just want to create the PR, and the fact that I first have to push the branch is an implementation detail: "I don't need to" == "I have no use for (doing it manually in two steps)".

> The only way to do that that I can see is to implement it in some tool (like Forge), i.e. _you_ would only do one thing but in the background the tool does two things, push and open the pr. Do you use a another tool that does that for you?

Exactly: my suggestion was that Forge could do push+open-pr in one go.

> 
> > Forge could help me by proposing local branches in the source refs list, and push them automatically on PR creation (maybe by asking on which remote to push, and maybe with which name; probably re-using the branch push sequence).
> 
> Many projects use automated tests that run when a new branch is created or new commits are pushed to an existing branch. You should check the results of those tests before you open a pull-request, which is only possible if you separate the acts of pushing and pr creation.

Yes. But there are also many projects where automated tests are only executed once a pull-request is created (for example github + jenkins).

> 
> I do not intend to implement "push+open-pr" as a single command.

OK... Maybe more people are interested in this workflow, let's see !

Feel free to close this issue.

**Comment by danlamanna** [comment]
I respect the `wontadd` label here, I just wanted to add another data point in support of this. Hopefully the masses will follow suit :P.

> You should check the results of those tests before you open a pull-request, which is only possible if you separate the acts of pushing and pr creation.

I think that this is common but certainly not a statement that can be made generally, many projects handle pull requests in ways other than the mainstream fork-style workflow that GitHub encourages. In fact, Git**Lab** encourages and enables developers to create a merge request as part of their push, see https://docs.gitlab.com/12.9/ee/user/project/push_options.html#push-options-for-merge-requests for instance.
