### ISSUE TITLE
Probable typo in forge-topic.el

### ISSUE THREAD

**Issue by KingOnFire065** [magit/forge#641]
'forge-topic.el', line 151, may include a typo. Looks like changing ``` '(:foreground reset) ``` to  ``` `(:foreground ,reset) ``` fixes several diffuse errors with several other packages, all about ````Wrong type argument: stringp, reset```.

The original error showed up on [dimmers](https://github.com/gonewest818/dimmer.el)' side of things:
```
Debugger entered--Lisp error: (wrong-type-argument stringp reset)
  color-defined-p(reset)
  dimmer-face-color(forge-topic-header-line 0.3)
  dimmer-dim-buffer(#<buffer *Messages*> 0.3)
  dimmer-process-all(t)
  dimmer-config-change-handler()
  redisplay_internal\ \(C\ function\)()
  completing-read-default("M-x " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_56> #f(compiled-function (sym) #<bytecode 0xb9b6ea788fee036>) t nil extended-command-history nil nil)
  read-extended-command-1("M-x " nil)
  read-extended-command()
  byte-code("\302\30\11\303 \10)E\207" [execute-extended-command--last-typed current-prefix-arg nil read-extended-command] 3)
  command-execute(execute-extended-command)
```

Notice how 'forge-topic-header-line' is passed as a face color, eventually misevaluating as "reset".

I've never in my life worked with lisp/elisp or emacs, or sent an issue through github. The fix seemed simple enough to mention ad ho here; apologies if it's more involved.

**Comment by KingOnFire065** [comment]
Sorry, guys: premature.

**Comment by tarsius** [comment]
Duplicate of #629. It's an issue in dimmer, now tracked at https://github.com/gonewest818/dimmer.el/issues/68.

> diffuse errors with several other packages

If you know about other packages, beside `dimmer`, which do not handle the new `reset` value for face attributes, the please report that in the appropriate issue trackers. Thanks!
