### ISSUE TITLE
github: no longer refreshes to show reviewers after they are added

### ISSUE THREAD

**Issue by acaird** [magit/forge#654]
In prior versions of forge when I added a reviewer, it would refresh while I was in the PR screen and display that person's full "github name" 

In version 20240401.2312 this is no longer the behavior. I can refresh the PRs (N f f) and see the names, and they are appearing in the reviews part of the Github webpage

When setting debug-on-error there was no error to generate a backtrace.  I'm happy to provide other debugging information if you tell me what you want and how to get it.

Thank you.

To reproduce, open a PR at Github, add a reviewer, note that while you're in the PR edit screen it doesn't refresh to show the name.

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by acaird** [comment]
Thanks for the fast fix!
