### ISSUE TITLE
gitlab: typing Enter on a Pull Request brings up Issue with same number instead

### ISSUE THREAD

**Issue by kevin8t8** [magit/forge#655]
I'm using Forge with a Gitlab project.

On the Magit status window, positioning the cursor on a Pull Request, e.g.  '!165' and typing Enter brings up Issue 165 instead.

Bringing up the Pull Request list, by typing Enter on the "Pull Requests" section line, and then typing Enter on a Pull Request also brings up the corresponding Issue number instead of the Pull Request.

I can still view the Pull Request via forge-dispatch, N v p.

It's been quite a while since I've used Forge with this Gitlab project, so I don't know exactly when this stopped working.

Thank you.

**Comment by tarsius** [comment]
Thanks for the report!
(I'm also not using Gitlab very often, obviously.)
