### ISSUE TITLE
gitlab: fetch topics always retrieves all issues and pullreqs

### ISSUE THREAD

**Issue by kevin8t8** [magit/forge#657]
Thank you for your quick fix to the previous Gitlab bug I reported.

I've noticed another strange behavior, 'f n' now seems to be refetching all issues and pull requests each time.  I poked around a little bit and noticed the 'issues_until' and 'pullreqs_until' fields in the `repository` table are both empty/nil. 

It may be relevant that I removed the sqlite database file and completely refetched all issues/prs when I first started trying to get Forge to work with the project again, last week.  Perhaps updating those fields isn't working quite right for the first pull?

If there is any other information I can provide to help, please let me know.

Thank you.

**Comment by tarsius** [comment]
Thanks for another highly actionable bug report!
