### ISSUE TITLE
Graphql endpoint errors out for v3 github API

### ISSUE THREAD

**Issue by howdoicomputer** [magit/forge#66]
```
helm-M-x: HTTP Error: 404, "Not found", "/api/v3/graphql", ((message . "Not Found") (documentation_url . "https://developer.github.com/enterprise/2.12/v3"))
```

This is against a GitHub Enterprise instance.

**Comment by vermiculus** [comment]
The endpoint is incorrect; per [docs](https://developer.github.com/enterprise/2.15/v4/guides/forming-calls/#the-graphql-endpoint), it should be `http(s)://[hostname]/api/graphql`.

What is the value of `github.host` in your repository?

**Comment by vermiculus** [comment]
Oops, rather, what is the value of `forge-alist` for you? [(Relevant section of the docs.)](https://magit.vc/manual/forge/Token-Creation.html#Token-Creation)

**Comment by howdoicomputer** [comment]
I can actually authorize via

```
curl -H "Authorization: bearer token" -X POST -d " \
 { \
   \"query\": \"query { viewer { login }}\" \
 } \
" https://gh.internal.shutterfly.com/api/graphql
```

What is interesting is that if I set the `/api/v3` endpoint for Forge, it'll be able to create credentials for me and stick them in `~/.authinfo`. It's just that subsequent calls are broken.

Magithub does work for me but it is unable to create PR and issue entries in the magit status buffer.

**Comment by vermiculus** [comment]
Hmm, try removing the /graphql from your alist value. I think that would be added by forge at runtime. (what struck me is the endpoint noted in the ghub error.)

Magithub will be phasing out functionality duplicated in Forge once the latter is mature and implements all the main features of the former. You should still be able to create topics there though; check the dispatch popup (`H`). Magithub doesn't know about forge (yet?), though, so some things are going to be clunky. For example, you'll most likely need to forge-pull after posting your topic.

**Comment by howdoicomputer** [comment]
So I tried removing the `/graphql` portion and now I get `ghub--signal-error: HTTP Error: 404, "Not found", "/api/v3/graphql", ((message . "Not Found") (documentation_url . "https://developer.github.com/enterprise/2.12/v3"))`

**Comment by vermiculus** [comment]
How is it getting that `v3` bit? I assume that's not in your `forge-alist`?

**Comment by howdoicomputer** [comment]
It's not. I'm kind of confused as to what is going on, to be honest.

```
**(("gh.internal.shutterfly.com" "gh.internal.shutterfly.com/api" "gh.internal.shutterfly.com" forge-github-repository)
 ("github.com" "api.github.com" "github.com" forge-github-repository)
 ("gitlab.com" "gitlab.com/api/v4" "gitlab.com" forge-gitlab-repository)
 ("salsa.debian.org" "salsa.debian.org/api/v4" "salsa.debian.org" forge-gitlab-repository)
 ("teahub.io" "teahub.io/api/v1" "teahub.io" forge-gitea-repository)
 ("code.orgmode.org" "code.orgmode.org/api/v1" "code.orgmode.org" forge-gogs-repository)
 ("bitbucket.org" "api.bitbucket.org/2.0" "bitbucket.org" forge-bitbucket-repository)
 ("git.savannah.gnu.org" nil "git.savannah.gnu.org" forge-cgit*-repository)
 ("git.kernel.org" nil "git.kernel.org" forge-cgit-repository)
 ("repo.or.cz" nil "repo.or.cz" forge-repoorcz-repository)
 ("git.suckless.org" nil "git.suckless.org" forge-stagit-repository)
 ("git.sr.ht" nil "git.sr.ht" forge-srht-repository))
**
```

**Comment by tarsius** [comment]
Add a debug statement to `ghub-request` printing the values of `host` and `resource`.

**Comment by tarsius** [comment]
That `v3` must come from somewhere. Does it still make an appearance after restarting Emacs (which I assume has happened over the last dozen days anyway :-). If the above list really is the value of `forge-alist`, then I don't see how `ghub` or Forge could be responsible for the `v3`.

I am closing this because I don't see how I can help you with this from a distance. But feel free to comment here again if you have any new information.
