### ISSUE TITLE
Support for inline comments

### ISSUE THREAD

**Issue by shindere** [magit/forge#663]
I think GitHub does have an API to submit inline comments to PRs, thatis,
comments that are tied to oneprecise portionn of code. This is something
that owuld be very clumsy to do with a CLItool, but with emacs and forge, it
feels it could be very simple to just mark a region and then run a comment
to submit a comment associated to this region.

Would that be doable?

Not being able to use the web UI for that, I suffer a lot from not
having a way to submit inline comments.

**Comment by tarsius** [comment]
That's a feature that is frequently requested and I might eventually add support to Forge itself. There's an open issue about this: https://github.com/magit/forge/issues/75.

At least two separate packages exist that already implement this:
- github-review (from https://github.com/charignon/github-review) and
- code-review (which unfortunately isn't being maintained anymore, so you will have to use the version from this pull-request: https://github.com/wandersoncferreira/code-review/pull/246)
