### ISSUE TITLE
ghub-graphql-error "could not resolve to an issue with the number of ..."

### ISSUE THREAD

**Issue by zoechi** [magit/forge#669]
- Subscribe to a lot of GitHub repositories
- `(forge-reset-database)`
- Add one GitHub repository to forge
- Fetch all notifications
- Wait for error

I get the same error when I start all over again.

### Messages output
```
Pulling notifications (page 445/523)...
Pulling notifications (page 446/523)...
Pulling notifications (page 447/523)...
Pulling notifications (page 448/523)...
Entering debugger...
```

<details>
  <summary>Stack trace first lines</summary>
Debugger entered--Lisp error: (ghub-graphql-error ((type . "NOT_FOUND") (path "_Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTMyNDAyNTM2MTo5MzM1MTk0NjMy" "issue") (locations ((line . 444) (column . 5))) (message . "Could not resolve to an Issue with the number of 466.")))
  ghub--signal-error((ghub-graphql-error ((type . "NOT_FOUND") (path "_Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTMyNDAyNTM2MTo5MzM1MTk0NjMy" "issue") (locations ((line . 444) (column . 5))) (message . "Could not resolve to an Issue with the number of 466."))))
</details>

---- now delete this line and everything above ----

The error looks like https://github.com/cli/cli/issues/157
I also found #80

```
"GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)"
```
magit-forge 0.3.2

**Comment by tarsius** [comment]
Incidentally I pushed a solution for that issue just last night (2c0171db6a632c4dd38ab080ed58ecd97dbf880d). :grinning:
