### ISSUE TITLE
new pullreq not created after `forge-post-submit`

### ISSUE THREAD

**Issue by ipocentro87** [magit/forge#675]
Hi all,
When `forge-create-pullreq` is invoked and Forge-Post buffer is shown to type title and description, I do `forge-post-submit` to actually send the pull request to the server. For some reasons this command has no impact other than just writing to `.git/magit/posts/new-pullreq`. Also it doesn't close the Forge-Post buffer as it should. It was working before and now I have no idea why it's no longer the case.
I am with forge `20231011.2149` and magit `20231010.1103`, I am using gitlab.

I tried again with `debug-on-error` but no error is shown.

I'd be curious to know whether someone else has had the same issue :thinking:

**Comment by tarsius** [comment]
> I am with forge `20231011.2149` and magit `20231010.1103`, I am using gitlab.

It works with the latest revisions. I just tried with both github and gitlab.

**Comment by ipocentro87** [comment]
I've got the same problem with the latest versions as well:
```
forge              20240702.1601
magit              20240704.2248
```

**Comment by tarsius** [comment]
Make sure ghub is also up-to-date. If it wasn't, restart Emacs after updating.

The next step is to figure out where things start to go south. A good first step to narrow things down is to add a debug statement in `forge--submit-create-pullreq`, right before the call to `forge--ghub-post repo`.

**Comment by tarsius** [comment]
Also, have you tried with github, and if by "gitlab" you mean "my companies gitlab instance", with gitlab.com?
