### ISSUE TITLE
error in process filter: EmacSQL had an unhandled condition: "table issue has 22 columns but 23 values were supplied"

### ISSUE THREAD

**Issue by notmgsk** [magit/forge#68]
Seeing this when doing `forge-pull`: `error in process filter: EmacSQL had an unhandled condition: "table issue has 22 columns but 23 values were supplied"`

**Comment by tarsius** [comment]
Did you try the package a while back? If so you need to delete the database and start over. Going forward I bump the db version and warn the user (and possibly offer to mitrate) when the schemata are changed, but before the first release I didn't do that.

**Comment by tarsius** [comment]
I'm gonna assume that is so.

**Comment by notmgsk** [comment]
Apologies for not replying sooner. I had a bunch of packages that needed updating. After doing that, things worked.
