### ISSUE TITLE
Forge-pull hangs on initial pull

### ISSUE THREAD

**Issue by gabrielsaldana** [magit/forge#682]
Recently when trying to run `forge-pull` on a repository (github or gitlab), emacs either hangs or takes a long time (hours) to complete the initial pull, even on brand new repositories. The last message I see in the Messages buffer is: `uncompressing publicsuffix.txt.gz...done`

After reinstalling `forge`, the process just hangs or does nothing. The `uncompressing publicsuffix.txt.gz` message no longer shows but doesn't fix the problem, emacs still hangs or takes hours to finish. 

Using emacs 29.3 (macOS)

I'm not sure how to provide additional details, as I don't see anything else in the Messages buffer and there is no error, just hangs.

**Comment by tarsius** [comment]
First do `M-x toggle-debug-on-signal` and then when Emacs hangs press `C-g`. That might give you a backtrace.

> `uncompressing publicsuffix.txt.gz...done`

I don't know what that is. Do you know the purpose of this file is? (If not, search for it and have a look. You might also want to grep `~/.config/emacs` for `publicsuffix`.)

**Comment by tarsius** [comment]
@MoskitoHero Could also be #720. I intend to fix that later this week.
