### ISSUE TITLE
cl-no-applicable-method: No applicable method: clone, nil

### ISSUE THREAD

**Issue by hexmode** [magit/forge#684]
I got multiple errors about the lack of `clone`:

``` console
error in process sentinel: cl-no-applicable-method: No applicable method: clone, nil
```

until I turned on backtrace on error and discovered that `forge--buffer-topics-spec` was not set. After finding the symbol, I saw that I needed to call `forge--init-buffer-topics-spec` to populate it, but the function wasn't defined. evaling the function allowed me to populate the buffer-local variable in my `magit-status` buffer.

Looking at forge-topic.el, it seems this file is not being loaded.

For reference, this is with a freshly cloned and compiled emacs with a freshly cloned via straight magit and forge repositories.

**Comment by tarsius** [comment]
This has already been reported in #681 and should be fixed by 03d012ae24eafa89a1a5ba7d9ed4069b05d54e21.

You need to update Forge and restart Emacs.
