### ISSUE TITLE
`forge-insert-requested-reviews` is gone?

### ISSUE THREAD

**Issue by Lenbok** [magit/forge#685]
I have this in my forge setup:

```lisp
  (add-hook 'magit-status-sections-hook 'forge-insert-requested-reviews 89)
```

But when I updated forge this now gives an error, and it seems that these functions have vanished. It (and other similarly deleted functions) are still documented at https://magit.vc/manual/forge/Listing-Topics-and-Notifications.html#index-forge_002dinsert_002drequested_002dreviews

I guess that the "bug report" is that the documentation needs updating, but what is the expected way to achieve the same functionality of an additional status section showing just the topics matching the criteria (in this cases review requested)

**Comment by tarsius** [comment]
See #676.
