### ISSUE TITLE
Changes are not reflected in the `Review-Requests` field

### ISSUE THREAD

**Issue by jroimartin** [magit/forge#686]
When editing the `Review-Requests` field of a pull request with `C-c C-e`, changes are sent to GitHub but not reflected in the forge UI.

Versions used:

- GNU Emacs 29.4 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0) of 2024-07-16
- forge 20240726.1807
- ghub 20240713.1918

**Comment by tarsius** [comment]
Thanks for the report. This should work going forward, however, pull-requests won't auto-repair until they are edited again somehow. You can fetch an *individual* pr to ensure this value is correct.
