### ISSUE TITLE
forge-pull hits rate limits

### ISSUE THREAD

**Issue by aspiers** [magit/forge#69]
I hit `F y` to `forge-pull`, and after some seconds I got this:

```
error in process filter: if: HTTP Error: 403, "Forbidden", "/graphql", ((documentation_url . "https://developer.github.com/v3/#abuse-rate-limits") (message . "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."))
```

It would be great if rate limiting was built in to avoid this.

**Comment by vermiculus** [comment]
Rate limiting is a bit difficult with graphql as the cost of a query is calculated at run time. Forge's current methodology of always pulling the entire repository's information won't play well with this in the end.

**Comment by vermiculus** [comment]
I say that with the confidence of someone who knows what they're talking about – but I don't actually. I'm just 'pretty sure' about forge's behavior from a slightly-firmer-than-vague recollection from weeks ago.

**Comment by tarsius** [comment]
Is this when trying to fetch a huge repository? I'm actually a bit surprised this happened. I had some debug statements that printed the relevant information and it never got even close to being close to the limit.

But it should be possible to slow down when getting close to the limit. It might be a while until I implement that.

**Comment by kommen** [comment]
I also wanted to give forge a try, but the `forge-pull` with the same error as posted above for me as well.

This is a large, but not very large repository with ~2000 PRs (~20 open) and 1700 issues (~200 open).

**Comment by vermiculus** [comment]
> This is a large, but not very large repository with ~2000 PRs (~20 open) and 1700 issues (~200 open).

Isn't magit itself about this size?

**Comment by aspiers** [comment]
[**@tarsius**](https://github.com/tarsius) commented on [null](https://github.com/magit/forge/issues/69#issuecomment-455179253 "2019-01-17T13:53:26Z - Replied by Github Reply Comments"):
> Is this when trying to fetch a huge repository?

I don't think so but unfortunately I can't remember which repo I ran it on - apologies for not being able to provide more details.  It was pretty much the first time I tried Forge so I thought maybe it's not hard to reproduce - but tried again just now with (IIRC) a much bigger repo and it was fine, even though it took ~60s or so to fetch almost 2k PRs, as opposed to only a few seconds when I originally saw the error from the rate limiting.  Maybe there was some other factor at play, e.g. the mess I made of initial token creation (as mentioned in https://github.com/magit/ghub/pull/78).

**Comment by tarsius** [comment]
I don't consider that a huge repository and it is indeed at the same magnitude as Magit.

It's weird that you hit the rate limit. While neither `ghub` nor `forge` deal with rate limiting properly I did use some temporary debug statements for a while and that indicated that Forge didn't get even close to going over the limit when fetching such a repository for the first time.

**Comment by tarsius** [comment]
We should consider the rate limiting headers and report when we get close. Most of that probably has to be implemented in `ghub`.

**Comment by vermiculus** [comment]
> We should consider the rate limiting headers and report when we get close.

Do learn from my lessons in `ghubp-ratelimit` – namely that GHE instances often have rate-limiting disabled and `/rate_limit` will return 404 if so.

**Comment by agzam** [comment]
I'm hitting the same error while with one of our private repos:
```
error in process filter: ghub--signal-error: HTTP Error: 403, "Forbidden", "/graphql", ((documentation_url . "https://developer.github.com/v3/#abuse-rate-limits") (message . "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."))
```

**Comment by mpereira** [comment]
Same here. It worked after a few tries:
```
Pulling mesosphere/dcos-commons...
error in process filter: ghub--signal-error: HTTP Error: 403, "Forbidden", "/graphql", ((documentation_url . "https://developer.github.com/v3/#abuse-rate-limits") (message . "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."))
error in process filter: HTTP Error: 403, "Forbidden", "/graphql", ((documentation_url . "https://developer.github.com/v3/#abuse-rate-limits") (message . "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."))
Pulling mesosphere/dcos-commons...done
Storing mesosphere/dcos-commons...done
```

**Comment by timor** [comment]
I am currently trying to `forge-pull` NixOS/nixpkgs.  On the first try, I got a 502 (see #20).  On the second invocation (couple of minutes later), I got this 403 with a an "abuse detection triggered" message.

(Magit 20190228.2035, Git 2.18.1, Emacs 26.1, gnu/linux)

**Comment by mbolivar** [comment]
I also hit this issue trying to pull https://github.com/zephyrproject-rtos/zephyr (roughly 9800 closed PRs, 400 open PRs, 5500 closed issues, 800 open issues), even with multiple retries. I am successfully able to forge-pull a much smaller repository.

Here are the `*Messages*` errors:

```
error in process filter: HTTP Error: 403, "Forbidden", "/graphql", ((documentation_url . "https://developer.github.com/v3/#abuse-rate-limits") (message . "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."))

error in process filter: ghub--signal-error: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `FCB5:1DC5:81A5B9:11A3BC7:5CF7E463` when reporting this issue."))))

error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `FCB5:1DC5:81A5B9:11A3BC7:5CF7E463` when reporting this issue."))))

error in process filter: ghub--signal-error: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `FCB5:1DC5:81B920:11A42E1:5CF7E46D` when reporting this issue."))))
```

**Comment by mbolivar** [comment]
According to their info pages, I am using:

- Forge version 0.1.0 (v0.1.0-113-g9a4ce77+1)
- Magit version 2.90.1 (v2.90.1-670-g01efbb2de+1).
- Ghub version 3.2.0 (v3.2.0-10-g9017033+1).

**Comment by Silex** [comment]
This happens to me on https://github.com/bbatsov/projectile if you want to debug.

**Comment by amjoseph-nixpkgs** [comment]
I too am getting errors on [nixpkgs](https://github.com/nixos/nixpkgs).

```
error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data) (errors ((message . "Something went wrong while executing your query. This may be the \
result of a timeout, or it could be a GitHub bug. Please include `B34A:3998:DBEFB7:E97D62:62DBC025` when reporting this issue."))))
```

**Comment by mrcnski** [comment]
Same error here. Does this not work for large repos (7000+ issues/PRs)?

**Comment by tarsius** [comment]
> I've set this to 50 in a few repositories in which I used to sometimes get a 502, and I cannot remember seeing any such errors since.

Okay... jinxed it. Got one right now.

**Comment by mrcnski** [comment]
I got the same error with `50`, but `20` seems to have worked for me, though it took a while. (And it only displays 65 PRs/issues, not sure if that is expected or not.) The repo is https://github.com/paritytech/polkadot if it helps.

Random idea, but could it be because I generated a "classic" non-expiring token?

**Comment by tarsius** [comment]
> I got the same error with `50`, but `20` seems to have worked for me

I have now set the default to 50, which seems like a reasonable compromise. That might not be enough in a few repositories, but I don't think using something as low as 20 *as the default*, would be reasonable.

> Edit: another idea, maybe it has to do with the amount of activity per issue/PR?

Yes, that was my conclusion in https://github.com/magit/forge/issues/69#issuecomment-1572402440 as well.

**Comment by glasserc** [comment]
I still routinely hit this issue at work. I've tried changing the value of `forge.graphqlItemLimit` and it seems to change the behavior but not sufficiently to finish fetching. It would be great if there was some way to detect that we hit a rate limit and pause, or to be able to fetch incrementally such that a failure still allowed us to make progress. In the meantime I worked around the behavior by putting a `(sleep-for 3)` call in the `ghub--graphql-retrieve` method (thanks @choppsv1 for the idea).

**Comment by agzam** [comment]
I don't know what the heck GitHub been doing lately, but gh-notify can't pull things out anymore. I keep hitting:

error in process sentinel: ghub--handle-response-error: HTTP Error: 403, "Forbidden", "https://api.github.com/graphql", nil
error in process sentinel: HTTP Error: 403, "Forbidden", "https://api.github.com/graphql", nil
