### ISSUE TITLE
No GitHub OAuth scope repo:org

### ISSUE THREAD

**Issue by mavit** [magit/forge#690]
https://magit.vc/manual/forge/Setup-for-Another-Github-Instance.html says:

> Follow a link to "Settings", from there to "Developer settings", from there to "Personal access tokens", and finally to "Tokens (classic)".  On that page generate a new token using the repo, user and repo:org scopes.

However, I do not see a scope of name `repo:org`.  Could this be a typo for `read:org`, perhaps?

**Comment by tarsius** [comment]
Thanks for the report!
