### ISSUE TITLE
forge-add-repository: Aborts the whole process if a single topic pull fails

### ISSUE THREAD

**Issue by philn** [magit/forge#694]
Importing this Gitlab MR failed and aborted the whole (3 hours long) forge-add-repository task:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1323

```
error in process filter: ghub--signal-error: HTTP Error: 500, "Internal server error", "/api/v4/projects/1357/merge_requests/1323/notes?per_page=100", ((message . "500 Internal Server Error"))
error in process filter: HTTP Error: 500, "Internal server error", "/api/v4/projects/1357/merge_requests/1323/notes?per_page=100", ((message . "500 Internal Server Error"))
```

Please include a backtrace in your report.  In most cases doing:

    M-x toggle-debug-on-error RET

Sorry I'm not going to do this again :(

**Comment by tarsius** [comment]
Yeah that sucks. Unfortunately there currently isn't anything we can do about it at this time (see my "callback hell has to be refactored" comment in the other discussion). I recommend you try again *over night* and hope for the best.

I'm afraid Gitlab support lags behind Github support quite a bit. The APIs are very different, so supporting two forges is about three times as much work. It probably will be quite a while until Gitlab support has caught up.

**Comment by philn** [comment]
Even the gitlab web UI displays red banners on that MR. I suppose i've reached a dead-end :(

**Comment by philn** [comment]
I suppose that if gitlab had some graphql API it would simplify your life?

**Comment by tarsius** [comment]
> Even the gitlab web UI displays red banners on that MR. I suppose i've reached a dead-end :(

:(

I'll close this as `wonfix` and "it's their fault" then.

**Comment by tarsius** [comment]
> I suppose that if gitlab had some graphql API it would simplify your life?

If I remember correctly, they said they would add that, but I have seen nothing so far.

And yes, it would of course help if the two supported forges didn't use completely different API types.
