### ISSUE TITLE
Pre-fill pull request with commit message 

### ISSUE THREAD

**Issue by thomas-riccardi** [magit/forge#70]
On Github when we create a pull request from a branch it tries to pre-fill the PR title and description:
1. if the PR has only one commit: it uses the commit message (then appends the github template to the resulting description)
2. if the PR has multiple commits: it converts the branch name to a sentence (capitalize, replace `-_` by spaces...) and uses it as the PR title (then uses the github template as PR description)

This could be a useful feature to implement in Forge.

**Comment by vermiculus** [comment]
I think this would be forge-agnostic; i.e. we wouldn't need separate implementations for github/gitlab/...

I might like to tackle this. Here's an open question though -- something I considered during magithub development but decided to ignore. What should be done, if anything with the branch description (`b C d`)?

**Comment by thomas-riccardi** [comment]
Hmm, maybe use it for PR title in scenario `2.`, and if unset fallback to what github does.
I believe scenario `1.` should be left as is.

**Comment by tarsius** [comment]
When tackling this we should also look into how the initial title is set.

Currently we begin the buffer with `# <point is here>` which should be fairly obvious. Except if a template is used, then we just insert that. Templates are supposed to have a `title: ` in the yaml front-matter and we place point there. However templates might lack `title: ` (magit's did), in which case we should insert it yourselves.

We might even want to always insert the yaml front-matter with at lest `title` (on Github, don't know about the others). That would be more consistent.

If we *don't* tackle this at the same thing as the feature requested here (which certainly is an option), then I think we should never insert *anything* beside the template (if any). When opening an issue using Github's web interface then nothing else is inserted beside the template either, if I am not mistaken.

**Comment by glasser** [comment]
This is the biggest thing I miss from magit-gh-pulls.

**Comment by miguelbernadi** [comment]
Is there currently a way to customize the buffer's initial contents? I'd like to hack a solution for my workflow but I haven't written anything of elisp yet.

**Comment by humitos** [comment]
@miguelbernadi in case you want to give it a try, this is the relevant part of the code that needs to be modified: https://github.com/magit/forge//blob/3b662e165805e34807dd9d0a73ec65e75e2c7a6f/lisp/forge-topic.el#L621

If you find out a hacky way of doing it, please share your solution!

**Comment by tarsius** [comment]
The message of the source branch's tip is now inserted when creating a pull-requests.  Like on Github the message is inserted before the instructions.  Unlike on Github this is done even when the pr consists of multiple commits.

**Comment by mjhoy** [comment]
Sorry to be unearthing this now, but I didn't find another issue. Did something about this feature change? I recently upgraded forge (https://github.com/magit/forge/compare/e8bb47d8313e7c083887902c20e321c8e1937301...d139e9ecae6df514dfb3c3ae06115df96a1b8392) and now my new pull requests don't pre-populate with the commit message if there is a single commit.

**Comment by tarsius** [comment]
> Sorry if I'm misunderstanding, but by `This should work again`, do you mean that `forge` should populate the new pullreq summary with the single commit message?

Yes and I just verified again that it does do that.

> I'm using `20250703.1603` and it's not, it's putting it at the end of the pullreq buffer after a comment

If it insert the commit message *and* something else, that doesn't change the fact that it *does* insert the commit message.

The "comment" that is also inserted are the instructions that the maintainer of the repository wants you to read when you create a pull-request. Depending on the project, it might even be a template/form that the maintainer expects you to fill out.

If such a "template" exists, then Forge always inserts it. I have intentionally not implemented as a hook function that is part of `forge-edit-post-hook` default value and could thus be removed from that hook. If a maintainer wants contributors to read some instructions, Forge should not make it possible to circumvent that.

(Maybe Forge didn't do that in the past, I don't remember. If that is so, then the current behavior is a bug fix, not a regression.)

This is what the commit message buffer looks like by default, when there is a template and a single commit:

```
# heading from template

body
from
template

<!-- Message of single commit: -->

only commit title

only
commit
body
```

**Comment by drlkf** [comment]
I see. Is there any way I can modify the aforementioned hook to replicate the old behavior?

Also [obligatory xkcd](https://xkcd.com/1172/)

**Comment by tarsius** [comment]
> Is there any way I can modify the aforementioned hook to replicate the old behavior?

No:

> If a maintainer wants contributors to read some instructions, Forge should not make it possible to circumvent that.
