### ISSUE TITLE
Hide issues if disabled

### ISSUE THREAD

**Issue by Linuus** [magit/forge#71]
In one of my projects at work we had issues enabled on Github and a while ago we disabled them. Now, when I fetch topics with Forge, I get all the issues we previously had. if I try to visit them I get a 404.

Perhaps this is a bug in the Github API? Perhaps Forge can see if issues are enabled and ignore them if so?

EDIT:
I think you can check the `hasIssuesEnabled` field on the repository.

**Comment by tarsius** [comment]
It turned out that the `package` table already contained a column for this information but that these values were not being set yet.  If the database had not been ready, then this change would have had to wait for the next schemata update; luckily we got around that.

**Comment by Linuus** [comment]
Cool, thanks! 👍
