### ISSUE TITLE
GIthub repository https://github.com/kjambunathan/org-mode-ox-odt/ issue 276 is not displayed completely

### ISSUE THREAD

**Issue by ouboub** [magit/forge#714]
Hi
I am on GNU emacs 29.4, using magit version **v4.1.0-2-g4d054196-dirty**

1. I added the repository repository https://github.com/kjambunathan/org-mode-ox-odt/
2. i run `(forge-list-issues)`
3. I open issue 276
4. It is only displayed till the word **so**, I attach a screenshot
![forge-issue](https://github.com/user-attachments/assets/d52de610-2df9-4efd-b0df-31b2310c5e40)
Regards

Uwe Brauer

**Comment by tarsius** [comment]
I cannot reproduce that.

Make sure you are using the latest `ghub` and `forge` versions.
