### ISSUE TITLE
I cannot quit forge.

### ISSUE THREAD

**Issue by ouboub** [magit/forge#717]
I run
1.     `M-x find-file` (open a local cloned github repository) 
2.      `M-x forge-add-repository`
3.     `M-x forge-list-issues`
4.   `q`
5.  `ibuffer` shows (attach screenshot)
6. I visit these forge buffers trying to use `q` or `C-q` or `C-g` but they are still there,
7.  I could simply kill these buffers from `ibuffer`, but that might be a bad idea.

So how can I quit visiting that repository with forge?
![forge-issue](https://github.com/user-attachments/assets/f9de67a9-030e-4757-8e04-426e99175099)

**Comment by tarsius** [comment]
Forge's buffers are technically "Magit buffers", i.e., their major-modes derive from `magit-mode`, so [this documentation](https://magit.vc/manual/magit/Quitting-Windows.html) applies.

So you could always use `C-u q`, or customize `magit-bury-buffer-function`. You could also change the binding in `forge-topics-mode-map`, if you want the behavior to differ between this mode and other magit/forge buffers. (There currently is no `forge-mode` from which all other forge modes derive, so you would have to change multiple keymaps to make all forge buffers behave differently from magit buffers.)
