### ISSUE TITLE
Installing `forge` with `straight.el` results in missing `closql` dependency

### ISSUE THREAD

**Issue by matthew-piziak** [magit/forge#72]
# To Reproduce

```
M-x straight-use-package forge
M-x forge-pull
```

# Error

```
byte-code: Cannot open load file: Not a directory, closql
```

# Version

```

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.2) of 2019-01-14
```

**Comment by tarsius** [comment]
That's not a `forge` issue though.

The problem might be that the libraries are located in `lisp/` while `forge-pkg.el` (metadata) is located at the top-level.

/cc @raxod502

**Comment by matthew-piziak** [comment]
Looks like it's resolved already, cheers: https://github.com/raxod502/straight.el/issues/336

**Comment by raxod502** [comment]
Whoops, sorry about that :o 
Definitely a problem on my end.
