### ISSUE TITLE
Rework the documentation

### ISSUE THREAD

**Issue by tarsius** [magit/forge#78]
There's too much "also see ..." going on currently for users to actually do it.

Maybe we should have sections:

* Initial configuration for Github.com
* Initial configuration for other Github instances
* Initial configuration for other forges (with no setup wizard)

**Comment by tarsius** [comment]
It is also worth considering moving Forges improved configuration mechanism to `ghub` to avoid confusing about e.g. `ghub.host`. I haven't done that because it would be an incompatible change and things relying on `ghub` directly would break.

**Comment by vermiculus** [comment]
Re backwards compatibility, it should be possible to support both methods -- at least temporarily.

Would it then be possible to show a persistent/annoying warning for those using the deprecated method?

**Comment by plumenator** [comment]
Is the documentation outdated? None of the keybindings don't work for me. Other than `'` for `forge-dispatch`, that is.

**Comment by tarsius** [comment]
The documentation is up-to-date. Maybe you haven't updated Magit in a long time and it still uses `magit-popup` instead of `transient`.

**Comment by plumenator** [comment]
Umm.. I did. Is there a way to check if it's using magit-popup? Because i definitely have transient installed as a dependency

**Comment by muihlinn** [comment]
Given the amount of bugs outside this package's scope which can affect its setup, I'm sure that a small step by step tutorial on setting up a forge (wizzard and manually) with possible pitfalls will help inmensely. Documentation as is now is fine once you have figured the main lines but fails giving a general view.
