### ISSUE TITLE
URL schema like `gitlab:username/repo.git`

### ISSUE THREAD

**Issue by bvraghav** [magit/forge#81]
My repositories use the following schema `gitlab:username/repo.git` for a gitlab based forge. I define the meaning of `gitlab:` in `~/.ssh/config` using `host, hostname, user, identityfile [...]` directives...
**But this url is not recognized as a valid forge**

As far as I can see [here](https://github.com/magit/forge/blob/master/lisp/forge-core.el#L212); the regexp, broadly speaking, searches for a URL with 4 parts as follows:

1. protocol followed by a username
2. one of the defined services
3. a separator followed by path
4. optional `.git` extension

Clearly, my URL schema does not fit this description.

I had thought of adding an alternate expression like `(the-forge-style-url\\|my-style-url)`; But that does not clearly solve the purpose, when I see that the matching groups of URL matching are later used. If there is a my-style-url; it will match the alternate expression, but will contain empty first and second  groups, which in turn breaks [this](https://github.com/magit/forge/blob/master/lisp/forge-core.el#L224).

Is there a way I can fork away with an alternate url schema and parser, and merge back into the forge pipeline (as early as possible)

**Comment by bvraghav** [comment]
**In retrospect**

[This location](https://docs.gitlab.com/ee/ssh/#working-with-non-default-ssh-key-pair-paths) clearly states that the endorsed suggestion to setup a repository conforms to `the-forge-style-url` and has comparative levels of ease of setup. And I follow it for the ease of `forge`

**Comment by tarsius** [comment]
Re #44.

See https://github.com/magit/forge/wiki/Tips-and-Tricks. It explains how to teach Forge about such ssh identities.
