### ISSUE TITLE
Support for "reviewers" as well as "assignees"?

### ISSUE THREAD

**Issue by stig** [magit/forge#82]
Could we please have support for setting "reviewers" as well as assignees? The company I work for do not use assignees at all (it's implicit that the PR creator owns it, and is thus assigned) but we use reviewers extensively to request reviews from specific people.

**Comment by tarsius** [comment]
So I thought "lets quickly tackle this", expecting to be able to pretty much copy-paste the assignee implementation. It seems I was wrong. "Reviewers" appear to be more complex and less intuitive than assignees, and also not sufficiently documented.

I'll need to reverse engineer this. Could you please point me to a few fairly active but preferably small repositories making extensive use of review requests?

**Comment by glittershark** [comment]
@tarsius Do you mean via Github's API? The following GQL query works for me:
```
repository(owner: "magit", name: "forge") {
    pullRequests(first:5) {
      nodes {
        reviewRequests(first:5) {
          nodes {
            requestedReviewer {
              ...on User {
                name
              }
            }
          }
        }
      }
    }
  }
```

**Comment by tarsius** [comment]
No I mean a *repository* that actually uses review requests so that I can test whether the code that I have written actually works. (And yes, I have figured out too that I have to use inline fragments (and implement support for that in `gsexp.el`.)

**Comment by tarsius** [comment]
Question that I have are:

- What happens if the requested review is performed?
- Does the respective `requestedReviewer` disappear?
- If not, then why is there no `status` field on `requestedReviewer`?
- Does it matter if the pr is approved or "needs work IMO"?

**Comment by stig** [comment]
Here is a few modestly-sized public repos that uses review requests: 

- https://github.com/CircleCI-Public/slack-orb
- https://github.com/CircleCI-Public/circleci-cli
- https://github.com/CircleCI-Public/circleci-orbs

(I've no affiliation -- though I have contributed to at least one.)

**Comment by tarsius** [comment]
I have added basic support for *review requests*. Only Github is supported because Gitlab doesn't have that feature. You can request a review, see who was asked to perform a review while looking at it in a dedicated buffer, and revoke a request. Basically you can do what you can do when assigning an issue except that the feature is called "review requests" instead of "assignees". In other words what has been requested here.

There is no support for actually performing a review (~ #75) or listing prs you have been asked to review (~ #79). At least the latter I plan to tackle soonish.

**Comment by dcaixinha** [comment]
@tarsius sorry for necrobumping a closed issue, but related to what was described here, would it be possible to set the reviewer (or approver in GitLab) via `forge`? Just setting the user, not performing the review (similar to what's already possible by setting the assignee with `forge-edit-topic-assignees`)?
