### ISSUE TITLE
Could forge-browse-dwim be mapped to C-c C-o (same as org-mode)?

### ISSUE THREAD

**Issue by rudi** [magit/forge#83]
Hi, my fingers want to type `C-c C-o` to open a link at point in a browser, since that's what `org-open-at-point` and `markdown-follow-thing-at-point` are mapped to.  Would it be possible to have the `C-c C-o` keybinding for `forge-browse-dwim` as well, either instead of or in addition to `C-c C-w`?

**Comment by tarsius** [comment]
Makes sense. That change had to be made in `magit`, so you will have to update that.

**Comment by rudi** [comment]
Many thanks!

**Comment by vermiculus** [comment]
Cross-referencing for posterity https://github.com/magit/magit/commit/1e1193666a4e96b1284a7cf3d2da69c5c4249acf
