### ISSUE TITLE
Add function/shortcut to copy URLs when applicable

### ISSUE THREAD

**Issue by oceyral** [magit/forge#85]
Hi,

My workflow usually involves creating merge requests, and then copy-pasting their URLs into instant messaging to a colleague for review/merge. There doesn't seem to be a convenient function to do that in forge, and I have to visit the merge request in a browser to then copy and paste the URL, which is a bit tedious.

I'm moderately sure that other people would also have a use for copying the current topic's URL.

I have created a small function for that (modeled on `forge-browse-topic`) and could open a pull request if there is interest: 
```lisp
(defun forge-copy-topic-url ()
  "Add the current topic's URL to the `kill-ring'."
  (interactive)
  (if-let ((topic (forge-current-topic)))
      (if (forge-issue-p topic)
          (kill-new (forge--format-url topic 'issues-url-format))
        (kill-new (forge--format-url topic 'pullreq-url-format)))
    (user-error "There is no topic at point")))
```

I also looked into doing the same for commits and branches, but the functions for those look much more intimidating, and I'm not very familiar with lisp.

**Comment by vermiculus** [comment]
Would definitions like the following be useful?

``` emacs-lisp
(cl-defmethod forge-get-url ((repo forge-repository))
  (forge--format-url (or (magit-get "forge.remote") "origin")
                     'remote-url-format))

(cl-defmethod forge-get-url ((pullreq forge-pullreq))
  (forge--format-url pullreq 'pullreq-url-format))

(cl-defmethod forge-get-url ((issue forge-issue))
  (forge--format-url issue 'issue-url-format))
```

I plan to make a PR based on this shortly.
