### ISSUE TITLE
forge-create-pullreq used the wrong remote

### ISSUE THREAD

**Issue by r-darwish** [magit/forge#87]
I wanted to create a pull request to [this repo](https://github.com/drrlvn/.emacs.d) from [my fork](https://github.com/r-darwish/.emacs.d). The remotes are configured in my computer like this:

```
origin  https://github.com/r-darwish/.emacs.d.git (fetch)
origin  https://github.com/r-darwish/.emacs.d.git (push)
upstream        https://github.com/drrlvn/.emacs.d (fetch)
upstream        https://github.com/drrlvn/.emacs.d (push)
```

I created a side branch called `cargo-magit` and pushed it to `origin`. I called `forge-create-pullreq`, set the source branch to `origin/cargo-magit` and the target to `upstream/master`. However, a pull request was crated into `origin/master`: https://github.com/r-darwish/.emacs.d/pull/2

**Comment by tarsius** [comment]
From the manual:

> The convention is to name the upstream remote ~origin~.  If you follow
> this convention, then you have to do nothing else and the remote by
> that name is automatically used, provided it exists and regardless of
> whether other remotes exist.  If it does not exist, then no other
> remotes are tried.

> If you do not follow the naming convention, then you have to inform
> Forge about that by setting the Git variable ~forge.remote~ to the name
> that you instead use for upstream remotes.  If this variable is set,
> then Forge uses the remote by that name, if it exists, the same way
> it may have used ~origin~ if the the variable were undefined.  I.e. it
> does not fall through to try ~origin~ if no remote by your chosen name
> exists.

**Comment by jdtsmith** [comment]
This is, confusing when you consider GitHub's take on the same issue (as quoted in [this answer](https://stackoverflow.com/questions/9257533/what-is-the-difference-between-origin-and-upstream-on-github?rq=1)).

> When a repo is cloned, it has a default remote called origin that points to your fork on GitHub, not the original repo it was forked from.
To keep track of the original repo, you need to add another remote named upstream

**Comment by vermiculus** [comment]
That's if you clone the fork. If you clone the upstream repository, then obviously *that* would be `origin`.

There might be an argument to make to look for `upstream`, but there are a lot of assumptions throughout magit and its ecosystem were that change to be made.

**Comment by jdtsmith** [comment]
Good point.  Is it possible for Magithub/forge to get information on whether it’s in a cloned fork or the original repository?

**Comment by vermiculus** [comment]
That information is available from the API, but it would have to pulled down first.

**Comment by fkhodkov** [comment]
Hi, I got same problem recently: selected a source branch `origin/branchname` (where `origin` is my repo), then a target branch `upstream/master` (there `upstream` is the repo I forked from, another option was `origin/master`), but the pull request still went to `origin/master`.

It's rather confusing: why offer a user to create a pull request into `upstream` and then almost silently create it elsewhere?  If forge isn't going to create pull request into the `upstream` even when asked directly, it probably shouldn't list `upstream` branches as a possible target, so user at least will know they need to do some setting up in order to get what they want.

**Comment by jdtsmith** [comment]
I think the confusion here is that there are two quite distinct and incompatible prevailing uses of the concept of `upstream` on GitHub:

1. I have a clone of a fork that I intend to develop and release separately.  I've added new functionality outside of the scope of the original.  Maybe I've even renamed it.  But I want to pull new developments from that original as they occur; it is my `upstream` source.  I don't intend to merge with it.  `upstream` may even become abandoned.  But I will soldier on.
2. A group of us is working together to develop a package.  For simplicity, each of us works in our own personal fork of the original.  We check out the original as `origin`, but push our development branches back to our own personal `upstream` forks, and then generate pull requests that are merged into the original.  Our forks are truly `upstream` from the origin.  Sometimes other people not on our team do the same: clone, push to their personal fork, submit a pull request.

**Comment by tarsius** [comment]
> It's rather confusing: why offer a user to create a pull request into upstream and then almost silently create it elsewhere?

Agreed. I'll have to do something about that.

**Comment by titaniumbones** [comment]
After reading all the comments, I'm not sure if there's already a workaround for this scenario described by @jdtsmith :
> 2. A group of us is working together to develop a package. For simplicity, each of us works in our own personal fork of the original. We check out the original as origin, but push our development branches back to our own personal upstream forks, and then generate pull requests that are merged into the original. Our forks are truly upstream from the origin. Sometimes other people not on our team do the same: clone, push to their personal fork, submit a pull request.

In this situation, is it appropriate to follow the directions from the manual (quoted above by @tarsius and set `forge.remote` to `upstream` with `git config --local forge.remote upstream`? Or will that have undesired side effects? In my case, as a minor contributor to several projects (mostly just small bugfixes) I will want to do all branching etc. on my own fork of a project, but then occasionally submit a PR to the upstrream when I've made enough progress.

**Comment by Boruch-Baum** [comment]
> set forge.remote to upstream with git config --local forge.remote upstream

This advice seems to have helped in my case, in that now I'm properly retrieving the data, but even so, I'm still getting the same error message:
```
128 git … fetch upstream

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jdtsmith** [comment]
> In this situation, is it appropriate to follow the directions from the manual (quoted above by @tarsius and set `forge.remote` to `upstream` with `git config --local forge.remote upstream`? Or will that have undesired side effects? In my case, as a minor contributor to several projects (mostly just small bugfixes) I will want to do all branching etc. on my own fork of a project, but then occasionally submit a PR to the upstrream when I've made enough progress.

This worked for me, thanks!  I bet exposing a command which does `git config --local forge.remote choose-your-remote`, and adding an informational bit on which remote is targeted by forge under `'` would be enough for most people.

**Comment by tarsius** [comment]
`forge-create-pullreq` now only offers branches from the correct remote as completion candidates when selecting the target for a pull-request. It is not possible to select another branch.

Forge only supports using a single remote as "the remote that has issues and into which pull-requests are being merge" **at a time**. It **is** possible to create topics in multiple remotes but Forge can only ever deal with the topics of a single remote at a time.

To switch between different remotes the `forge.remote` variable has to be set.  This can now be done easily from the `forge-dispatch` prefix using.
