### ISSUE TITLE
Hide closed PRs in PR list

### ISSUE THREAD

**Issue by Linuus** [magit/forge#88]
In the magit status buffer there is a "Pull requests" section which lists the pull requests. The closed PRs are highlighted differently.

Is it possible to not show closed PRs at all in this list?

**Comment by vermiculus** [comment]
Related #42 #79

**Comment by tarsius** [comment]
You can customize `forge-topic-list-limit` to do that. Well almost, closed but unread topics are shown anyway.

**Comment by Linuus** [comment]
@tarsius Ah nice, so setting it to something like `(60 . 0)` should do it.

Thanks!
