### ISSUE TITLE
ghub--handle-response-headers: BUG: missing headers

### ISSUE THREAD

**Issue by floli** [magit/forge#94]
Hello,
I have installed the newest version of forge (today form MELPA: `forge-20190120.1902`), version of Emacs and Magit see below. Trying to create a GitHub Token (`F y` from magit status screen) gives me:

```
ghub--handle-response-headers: BUG: missing headers
  See https://github.com/magit/ghub/issues/81.
  headers: nil
  status: nil
  buffer: #<buffer  *http api.github.com:443*>
  buffer-string:
  ""
  --- end of buffer-string ---
```
```
Magit 20190122.503, Git 2.20.1, Emacs 26.1, gnu/linux
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
```
I have two factor auth activated for GitHub, but I think it worked with magit before.

I would be happy to provide any more information!

Best Thanks!

**Comment by vermiculus** [comment]
Did you look at the issue linked in the error?

**Comment by floli** [comment]
Sorry, my shame, I didn't. This issue can be closed then.

I will follow the linked bug and hope for a fix there.
