### ISSUE TITLE
Support forges behind HTTP Basic auth 

### ISSUE THREAD

**Issue by runejuhl** [magit/forge#98]
I'm using a private Gitlab instance hidden behind HTTP Basic auth. Usually URL handlers are able to transparently use HTTP Basic auth by prefixing the username and password to the URL, e.g. `https://runejuhl:mypassword@mygitlab.example.com`.

I've tried setting the API endpoint to `runejuhl:mypassword@mygitlab.example.com/api/v4`, but that just results in this message:

~~~
open-network-stream: mygitlab.example.com/443 Name or service not known
~~~

Would it be possible to add support for HTTP Basic auth? Let me know if I can do anything to help.

(and thank you for Forge :smile: )

**Comment by tarsius** [comment]
I do not plan to support that any time soon.
